//! The view table: for each view the camera numbers, the language string that names it,
//! whether the cinematic bars slide in, and whether it is from the cockpit.
//!
//! Generated by `src/tools/tablegen` from the payload executable's view table at
//! 0x004F72A8, 44 views. Do not edit by hand; run `make view-tables`.

pub const Record = struct {
    /// The language string that names the view, which the display shows at the top of the
    /// screen in every view but the one ahead from the cockpit.
    name: u16,
    /// Whether the cinematic bars slide in.
    bars: bool,
    /// Whether it is from the cockpit, so that the object's own model is not drawn.
    cockpit: bool,
};

/// Every view, indexed by its number.
pub const records = [_]Record{
    .{ .name = 170, .bars = false, .cockpit = true }, // 0x00
    .{ .name = 171, .bars = false, .cockpit = true }, // 0x01
    .{ .name = 172, .bars = false, .cockpit = true }, // 0x02
    .{ .name = 173, .bars = false, .cockpit = true }, // 0x03
    .{ .name = 181, .bars = false, .cockpit = false }, // 0x04
    .{ .name = 175, .bars = false, .cockpit = false }, // 0x05
    .{ .name = 176, .bars = false, .cockpit = false }, // 0x06
    .{ .name = 177, .bars = true, .cockpit = false }, // 0x07
    .{ .name = 178, .bars = true, .cockpit = false }, // 0x08
    .{ .name = 179, .bars = true, .cockpit = false }, // 0x09
    .{ .name = 179, .bars = true, .cockpit = false }, // 0x0A
    .{ .name = 179, .bars = true, .cockpit = false }, // 0x0B
    .{ .name = 180, .bars = false, .cockpit = false }, // 0x0C
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x0D
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x0E
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x0F
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x10
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x11
    .{ .name = 182, .bars = true, .cockpit = false }, // 0x12
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x13
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x14
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x15
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x16
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x17
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x18
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x19
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x1A
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x1B
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x1C
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x1D
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x1E
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x1F
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x20
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x21
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x22
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x23
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x24
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x25
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x26
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x27
    .{ .name = 181, .bars = false, .cockpit = false }, // 0x28
    .{ .name = 181, .bars = false, .cockpit = false }, // 0x29
    .{ .name = 181, .bars = false, .cockpit = false }, // 0x2A
    .{ .name = 181, .bars = true, .cockpit = false }, // 0x2B
};
