//! The words of `gun_stats` that the executable holds rather than `gunstats.bin`: for each
//! gun type, what a shot costs the ship, how large it is drawn, the sound it makes and how
//! often that sound is heard, and where its bolt lies in the shot texture.
//!
//! Generated by `src/tools/tablegen` from the payload executable's `gun_stats` at
//! 0x00500CA4, its sound periods at 0x00508700 and its texture spans at 0x00500FB0 and
//! 0x00500FEC. Do not edit by hand; run `make gun-tables`.

const guns = @import("../guns.zig");

/// What a gun type's record holds besides its figures from `gunstats.bin`.
pub const Static = struct {
    /// What a shot costs the ship.
    kind: guns.Kind,
    /// How large a shot is drawn: half its width, half its height, and its length
    /// (`guns.boltMesh`).
    bolt: [3]f32,
    /// The sound a shot makes (`bullet_fire`).
    sound: i32,
};

/// Every gun type's, by its number. Type 0 is no gun: no muzzle may name it.
pub const gun_types = [16]Static{
    // 0x00
    .{ .kind = .energy, .bolt = .{ 0, 0, 0 }, .sound = 0 },
    // 0x01
    .{ .kind = .energy, .bolt = .{ 30, 30, 1200 }, .sound = 0 },
    // 0x02
    .{ .kind = .energy, .bolt = .{ 30, 30, 800 }, .sound = 0 },
    // 0x03
    .{ .kind = .energy, .bolt = .{ 64, 64, 50 }, .sound = 1 },
    // 0x04
    .{ .kind = .energy, .bolt = .{ 50, 50, 1400 }, .sound = 2 },
    // 0x05
    .{ .kind = .energy, .bolt = .{ 30, 30, 800 }, .sound = 3 },
    // 0x06
    .{ .kind = .energy, .bolt = .{ 30, 30, 800 }, .sound = 4 },
    // 0x07
    .{ .kind = .energy, .bolt = .{ 30, 30, 800 }, .sound = 5 },
    // 0x08
    .{ .kind = .rounds, .bolt = .{ 30, 30, 800 }, .sound = 6 },
    // 0x09
    .{ .kind = .rounds, .bolt = .{ 30, 30, 800 }, .sound = 7 },
    // 0x0A
    .{ .kind = .rounds, .bolt = .{ 30, 30, 800 }, .sound = 8 },
    // 0x0B
    .{ .kind = .rounds, .bolt = .{ 30, 30, 800 }, .sound = 0 },
    // 0x0C
    .{ .kind = .rounds, .bolt = .{ 30, 30, 800 }, .sound = 2 },
    // 0x0D
    .{ .kind = .rounds, .bolt = .{ 30, 30, 800 }, .sound = 2 },
    // 0x0E
    .{ .kind = .rounds, .bolt = .{ 30, 30, 800 }, .sound = 9 },
    // 0x0F
    .{ .kind = .rounds, .bolt = .{ 30, 30, 800 }, .sound = 9 },
};

/// The steps a gun of each type fires between the sounds of its shots: the player's shots
/// are all heard, another ship's one in this many (`guns.heard`).
pub const sound_periods = [16]i32{
    0, // 0x00
    3, // 0x01
    4, // 0x02
    4, // 0x03
    3, // 0x04
    4, // 0x05
    1, // 0x06
    1, // 0x07
    1, // 0x08
    4, // 0x09
    1, // 0x0A
    1, // 0x0B
    1, // 0x0C
    1, // 0x0D
    1, // 0x0E
    1, // 0x0F
};

/// Where each gun type's bolt lies across the shot texture (`guns.boltTexture`): the texel
/// it begins at and how many it spans. Type 0 is no gun, and a type that begins below zero
/// is not drawn from it.
pub const atlas = [16][2]i32{
    .{ 0, 0 }, // 0x00
    .{ 0, 32 }, // 0x01
    .{ -1, 32 }, // 0x02
    .{ 32, 32 }, // 0x03
    .{ 64, 32 }, // 0x04
    .{ 96, 32 }, // 0x05
    .{ 224, 32 }, // 0x06
    .{ 160, 32 }, // 0x07
    .{ -1, 32 }, // 0x08
    .{ 192, 32 }, // 0x09
    .{ 64, 32 }, // 0x0A
    .{ 64, 32 }, // 0x0B
    .{ 64, 32 }, // 0x0C
    .{ 32, 32 }, // 0x0D
    .{ 32, 32 }, // 0x0E
    .{ 32, 0 }, // 0x0F
};
