//! The words of `gun_stats` that the executable holds rather than `gunstats.bin`: for each
//! gun type, what a shot costs the ship, the sound it makes and how often that sound is
//! heard.
//!
//! Generated by `src/tools/tablegen` from the payload executable's `gun_stats` at
//! 0x00500CA4 and its sound periods at 0x00508700. Do not edit by hand; run `make gun-tables`.

const guns = @import("../guns.zig");

/// What a gun type's record holds besides its figures from `gunstats.bin`.
pub const Static = struct {
    /// What a shot costs the ship.
    kind: guns.Kind,
    /// **Unknown.** Always the same as `_unknown_08`.
    _unknown_04: f32,
    /// **Unknown.**
    _unknown_08: f32,
    /// **Unknown.** Between 50 and 1400.
    _unknown_0c: f32,
    /// The sound a shot makes (`bullet_fire`).
    sound: i32,
};

/// Every gun type's, by its number. Type 0 is no gun: no muzzle may name it.
pub const gun_types = [16]Static{
    // 0x00
    .{ .kind = .energy, ._unknown_04 = 0, ._unknown_08 = 0, ._unknown_0c = 0, .sound = 0 },
    // 0x01
    .{ .kind = .energy, ._unknown_04 = 30, ._unknown_08 = 30, ._unknown_0c = 1200, .sound = 0 },
    // 0x02
    .{ .kind = .energy, ._unknown_04 = 30, ._unknown_08 = 30, ._unknown_0c = 800, .sound = 0 },
    // 0x03
    .{ .kind = .energy, ._unknown_04 = 64, ._unknown_08 = 64, ._unknown_0c = 50, .sound = 1 },
    // 0x04
    .{ .kind = .energy, ._unknown_04 = 50, ._unknown_08 = 50, ._unknown_0c = 1400, .sound = 2 },
    // 0x05
    .{ .kind = .energy, ._unknown_04 = 30, ._unknown_08 = 30, ._unknown_0c = 800, .sound = 3 },
    // 0x06
    .{ .kind = .energy, ._unknown_04 = 30, ._unknown_08 = 30, ._unknown_0c = 800, .sound = 4 },
    // 0x07
    .{ .kind = .energy, ._unknown_04 = 30, ._unknown_08 = 30, ._unknown_0c = 800, .sound = 5 },
    // 0x08
    .{ .kind = .rounds, ._unknown_04 = 30, ._unknown_08 = 30, ._unknown_0c = 800, .sound = 6 },
    // 0x09
    .{ .kind = .rounds, ._unknown_04 = 30, ._unknown_08 = 30, ._unknown_0c = 800, .sound = 7 },
    // 0x0A
    .{ .kind = .rounds, ._unknown_04 = 30, ._unknown_08 = 30, ._unknown_0c = 800, .sound = 8 },
    // 0x0B
    .{ .kind = .rounds, ._unknown_04 = 30, ._unknown_08 = 30, ._unknown_0c = 800, .sound = 0 },
    // 0x0C
    .{ .kind = .rounds, ._unknown_04 = 30, ._unknown_08 = 30, ._unknown_0c = 800, .sound = 2 },
    // 0x0D
    .{ .kind = .rounds, ._unknown_04 = 30, ._unknown_08 = 30, ._unknown_0c = 800, .sound = 2 },
    // 0x0E
    .{ .kind = .rounds, ._unknown_04 = 30, ._unknown_08 = 30, ._unknown_0c = 800, .sound = 9 },
    // 0x0F
    .{ .kind = .rounds, ._unknown_04 = 30, ._unknown_08 = 30, ._unknown_0c = 800, .sound = 9 },
};

/// The steps a gun of each type fires between the sounds of its shots: the player's shots
/// are all heard, another ship's one in this many (`guns.heard`).
pub const sound_periods = [16]i32{
    0, // 0x00
    3, // 0x01
    4, // 0x02
    4, // 0x03
    3, // 0x04
    4, // 0x05
    1, // 0x06
    1, // 0x07
    1, // 0x08
    4, // 0x09
    1, // 0x0A
    1, // 0x0B
    1, // 0x0C
    1, // 0x0D
    1, // 0x0E
    1, // 0x0F
};
