//! Names for the functions the VM reaches only through its tables: a row for each opcode handler
//! and each command implementation, in the form of `ghidra/names/LANCER.EXE.tsv`.

const std = @import("std");
const Io = std.Io;

const starlancer = @import("starlancer");
const dte = starlancer.dte;

pub fn write(w: *Io.Writer) Io.Writer.Error!void {
    try w.writeAll("# Generated by ghidragen names from src/formats/vm_opcodes.zig, vm_commands.zig and dte.Opcode.\n");
    try handlers(w);
    try commands(w);
}

/// A row per opcode handler, named `vm_` and its opcode's name. An opcode sharing its handler with
/// another is a `_alt` alias, so the handler takes the other's name.
fn handlers(w: *Io.Writer) Io.Writer.Error!void {
    for (dte.vm_opcodes.table, 0..) |info, index| {
        // Each handler once, under the first opcode that is not an alias.
        const name = dte.opcodeName(info.opcode) orelse continue;
        if (std.mem.endsWith(u8, name, "_alt")) continue;
        const first = for (dte.vm_opcodes.table[0..index]) |earlier| {
            if (earlier.handler != info.handler) continue;
            const earlier_name = dte.opcodeName(earlier.opcode) orelse continue;
            if (!std.mem.endsWith(u8, earlier_name, "_alt")) break false;
        } else true;
        if (!first) continue;

        try w.print("{x:0>8}\tfunction\tvm_{s}\tVmHandler\topcode 0x{X:0>2}", .{ info.handler, name, info.opcode });
        for (dte.vm_opcodes.table) |other| {
            if (other.handler == info.handler and other.opcode != info.opcode) {
                try w.print(", also 0x{X:0>2}", .{other.opcode});
            }
        }
        try w.writeByte('\n');
    }
}

/// A row per command implementation, named `cmd_` and the developers' name for the command, and
/// one for each command's per-ship callback, named after it with `_ship`. An implementation that is
/// also a callback, as the test command `PrintShipName`'s is, is named as the callback.
fn commands(w: *Io.Writer) Io.Writer.Error!void {
    for (dte.vm_commands.table, 0..) |command, index| {
        const callback_too = for (dte.vm_commands.table) |other| {
            if (other.per_ship == command.implementation) break true;
        } else false;
        if (!callback_too) {
            try w.print("{x:0>8}\tfunction\tcmd_{s}\tVmCommand\t", .{ command.implementation, command.name });
            try description(w, command.description);
            try w.print(" (command 0x{X:0>2})\n", .{index});
        }
        if (command.per_ship) |callback| {
            try w.print("{x:0>8}\tfunction\tcmd_{s}_ship\tVmShipCommand\t", .{ callback, command.name });
            try description(w, command.description);
            try w.print(", for each ship (command 0x{X:0>2})\n", .{index});
        }
    }
}

fn description(w: *Io.Writer, text: []const u8) Io.Writer.Error!void {
    for (text) |c| try w.writeByte(if (c == '\t' or c == '\n') ' ' else c);
}

test write {
    var buffer: [64 << 10]u8 = undefined;
    var w: Io.Writer = .fixed(&buffer);
    try write(&w);
    const rows = w.buffered();
    try std.testing.expect(std.mem.indexOf(u8, rows, "\tfunction\tvm_return\tVmHandler\topcode 0x43, also 0x25\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, rows, "vm_return_alt") == null);
    try std.testing.expect(std.mem.indexOf(u8, rows, "0045d210\tfunction\tcmd_CreateTimer\tVmCommand\t") != null);
    try std.testing.expect(std.mem.indexOf(u8, rows, "004588e0\tfunction\tcmd_ClearAI_ship\tVmShipCommand\t") != null);
}
