//! Names for the functions the payload reaches only through its tables, in the form of
//! `ghidra/names/LANCER.EXE.tsv`: a row for each VM opcode handler, command implementation, order
//! routine and maneuver opcode handler, and one for each group of the order table, the maneuver
//! tables and each maneuver's script.

const std = @import("std");
const Io = std.Io;

const openreliant = @import("openreliant");
const dte = openreliant.dte;
const lancer = openreliant.lancer;
const opcodes = lancer.vm.opcodes;
const command_table = lancer.game.executor.commands;
const orders = lancer.game.ai.orders;
const maneuvers = lancer.game.aidefend.maneuvers;

pub fn write(w: *Io.Writer) Io.Writer.Error!void {
    try w.writeAll("# Generated by ghidragen names from the opcode, command, order and maneuver tables of src/lancer and dte.Opcode.\n");
    try handlers(w);
    try commands(w);
    try orderGroups(w);
    try orderRoutines(w);
    try maneuverTables(w);
    try maneuverHandlers(w);
}

/// A row per opcode handler, named `vm_` and its opcode's name. An opcode sharing its handler with
/// another is a `_alt` alias, so the handler takes the other's name.
fn handlers(w: *Io.Writer) Io.Writer.Error!void {
    for (opcodes.table, 0..) |info, index| {
        // Each handler once, under the first opcode that is not an alias.
        const name = dte.opcodeName(info.opcode) orelse continue;
        if (std.mem.endsWith(u8, name, "_alt")) continue;
        const first = for (opcodes.table[0..index]) |earlier| {
            if (earlier.handler != info.handler) continue;
            const earlier_name = dte.opcodeName(earlier.opcode) orelse continue;
            if (!std.mem.endsWith(u8, earlier_name, "_alt")) break false;
        } else true;
        if (!first) continue;

        try w.print("{x:0>8}\tfunction\tvm_{s}\tVmHandler\topcode 0x{X:0>2}", .{ info.handler, name, info.opcode });
        for (opcodes.table) |other| {
            if (other.handler == info.handler and other.opcode != info.opcode) {
                try w.print(", also 0x{X:0>2}", .{other.opcode});
            }
        }
        try w.writeByte('\n');
    }
}

/// A row per command implementation, named `cmd_` and the developers' name for the command, and
/// one for each command's per-ship callback, named after it with `_ship`. An implementation that is
/// also a callback, as the test command `PrintShipName`'s is, is named as the callback.
fn commands(w: *Io.Writer) Io.Writer.Error!void {
    for (command_table.table, 0..) |command, index| {
        const callback_too = for (command_table.table) |other| {
            if (other.per_ship == command.implementation) break true;
        } else false;
        if (!callback_too) {
            try w.print("{x:0>8}\tfunction\tcmd_{s}\tVmCommand\t", .{ command.implementation, command.name });
            try description(w, command.description);
            try w.print(" (command 0x{X:0>2})\n", .{index});
        }
        if (command.per_ship) |callback| {
            try w.print("{x:0>8}\tfunction\tcmd_{s}_ship\tVmShipCommand\t", .{ callback, command.name });
            try description(w, command.description);
            try w.print(", for each ship (command 0x{X:0>2})\n", .{index});
        }
    }
}

/// A row labelling each group of the order table, `orders_` and the first order's number.
fn orderGroups(w: *Io.Writer) Io.Writer.Error!void {
    for (orders.groups) |group| {
        try w.print("{x:0>8}\tdata\torders_{d}\tOrderRecord[{d}]\tThe records of orders {d} to {d}\n", .{
            group.address, group.first, group.len, group.first, group.first + group.len - 1,
        });
    }
}

const Role = enum { init, update, exit };

/// A row per order routine, named `order_` and the order's identifier, with `_init` or `_exit` for
/// those. A routine that orders of different names share, or that serves in different roles, is
/// left to the hand-kept table.
fn orderRoutines(w: *Io.Writer) Io.Writer.Error!void {
    for (orders.table) |entry| {
        const identifier = std.enums.tagName(orders.Order, entry.order) orelse continue;
        inline for (comptime std.enums.values(Role)) |role| {
            if (@field(entry, @tagName(role))) |address| {
                if (namesRoutine(entry, role, address)) {
                    const suffix = switch (role) {
                        .init => "_init",
                        .update => "",
                        .exit => "_exit",
                    };
                    try w.print("{x:0>8}\tfunction\torder_{s}{s}\tObjectRoutine\tThe {s} of order {d}", .{
                        address, identifier, suffix, @tagName(role), @intFromEnum(entry.order),
                    });
                    if (entry.name.len != 0) try w.print(", {s}", .{entry.name});
                    for (orders.table) |other| {
                        if (@field(other, @tagName(role)) == address and other.order != entry.order) {
                            try w.print(", and of order {d}", .{@intFromEnum(other.order)});
                        }
                    }
                    try w.writeByte('\n');
                }
            }
        }
    }
}

/// Whether `entry` names the routine at `address`: it is the first order to use it, and every
/// order that does is named alike and uses it as the same routine.
fn namesRoutine(entry: orders.Info, role: Role, address: u32) bool {
    for (orders.table) |other| {
        inline for (comptime std.enums.values(Role)) |other_role| {
            if (@field(other, @tagName(other_role)) == address) {
                if (other_role != role or !std.mem.eql(u8, other.name, entry.name)) return false;
                if (@intFromEnum(other.order) < @intFromEnum(entry.order)) return false;
            }
        }
    }
    return true;
}

/// Rows labelling the maneuver table, the handler table and each maneuver's script, which ends
/// with a line without text.
fn maneuverTables(w: *Io.Writer) Io.Writer.Error!void {
    try w.print("{x:0>8}\tdata\tmaneuvers\tManeuverRecord[{d}]\tThe combat maneuvers the Fight order runs\n", .{
        maneuvers.addresses.table, maneuvers.table.len,
    });
    try w.print("{x:0>8}\tdata\tmaneuver_handlers\tManeuverHandlers[{d}]\tWhat each opcode of the maneuver scripts runs as it starts, and while it waits\n", .{
        maneuvers.addresses.handlers, maneuvers.handlers.values.len,
    });
    for (maneuvers.table) |entry| {
        const identifier = std.enums.tagName(maneuvers.Maneuver, entry.maneuver) orelse continue;
        try w.print("{x:0>8}\tdata\tmaneuver_script_{s}\tManeuverScriptLine[{d}]\tThe script of maneuver {d}, {s}\n", .{
            entry.script_address, identifier, entry.script.len + 1, @intFromEnum(entry.maneuver), entry.name,
        });
    }
}

const Stage = enum { start, run };

/// A row per maneuver opcode handler, named `maneuver_`, the opcode's name, and `_start` or `_run`.
/// A routine that serves several, such as the timer most waiting instructions start with, is left
/// to the hand-kept table.
fn maneuverHandlers(w: *Io.Writer) Io.Writer.Error!void {
    for (std.enums.values(maneuvers.Opcode)) |opcode| {
        const pair = maneuvers.handlers.get(opcode);
        inline for (comptime std.enums.values(Stage)) |stage| {
            if (@field(pair, @tagName(stage))) |address| {
                if (handlerUses(address) == 1) {
                    try w.print("{x:0>8}\tfunction\tmaneuver_{s}_{s}\tManeuverHandler\tThe {s} of a maneuver script's {s} instruction\n", .{
                        address, @tagName(opcode), @tagName(stage), @tagName(stage), @tagName(opcode),
                    });
                }
            }
        }
    }
}

/// How many opcode stages run the routine at `address`.
fn handlerUses(address: u32) usize {
    var uses: usize = 0;
    for (maneuvers.handlers.values) |pair| {
        inline for (comptime std.enums.values(Stage)) |stage| {
            if (@field(pair, @tagName(stage)) == address) uses += 1;
        }
    }
    return uses;
}

fn description(w: *Io.Writer, text: []const u8) Io.Writer.Error!void {
    for (text) |c| try w.writeByte(if (c == '\t' or c == '\n') ' ' else c);
}

test write {
    var buffer: [64 << 10]u8 = undefined;
    var w: Io.Writer = .fixed(&buffer);
    try write(&w);
    const rows = w.buffered();
    try std.testing.expect(std.mem.indexOf(u8, rows, "\tfunction\tvm_return\tVmHandler\topcode 0x43, also 0x25\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, rows, "vm_return_alt") == null);
    try std.testing.expect(std.mem.indexOf(u8, rows, "0045d210\tfunction\tcmd_CreateTimer\tVmCommand\t") != null);
    try std.testing.expect(std.mem.indexOf(u8, rows, "004588e0\tfunction\tcmd_ClearAI_ship\tVmShipCommand\t") != null);
}

test maneuverHandlers {
    var buffer: [16 << 10]u8 = undefined;
    var w: Io.Writer = .fixed(&buffer);
    try maneuverTables(&w);
    try maneuverHandlers(&w);
    const rows = w.buffered();
    try std.testing.expect(std.mem.indexOf(u8, rows, "\tdata\tmaneuvers\tManeuverRecord[") != null);
    try std.testing.expect(std.mem.indexOf(u8, rows, "\tdata\tmaneuver_script_loop_the_loop\tManeuverScriptLine[") != null);
    try std.testing.expect(std.mem.indexOf(u8, rows, "\tfunction\tmaneuver_set_yaw_start\tManeuverHandler\t") != null);
    // The timer that several waiting instructions start with is not named after any one of them.
    const timer = maneuvers.handlers.get(.wait).start.?;
    var address: [8]u8 = undefined;
    _ = try std.fmt.bufPrint(&address, "{x:0>8}", .{timer});
    try std.testing.expect(std.mem.indexOf(u8, rows, &address) == null);
}

test orderRoutines {
    var buffer: [64 << 10]u8 = undefined;
    var w: Io.Writer = .fixed(&buffer);
    try orderGroups(&w);
    try orderRoutines(&w);
    const rows = w.buffered();
    try std.testing.expect(std.mem.indexOf(u8, rows, "\tdata\torders_100\tOrderRecord[") != null);
    try std.testing.expect(std.mem.indexOf(u8, rows, "\tfunction\torder_fly_aimlessly_init\tObjectRoutine\tThe init of order 1, Fly Aimlessly\n") != null);
    // Orders 19 and 40 are both Jump In and share their routines, which take the first's name.
    try std.testing.expect(std.mem.indexOf(u8, rows, "\torder_jump_in\tObjectRoutine\tThe update of order 19, Jump In, and of order 40\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, rows, "order_jump_in_40") == null);
    // The empty routine that differently named orders share gets no order's name.
    try std.testing.expect(std.mem.indexOf(u8, rows, "004983a0") == null);
}
