//! The rows `ghidra/scripts/ApplySources.java` builds the Sources program tree from: a fragment for
//! each source file's known code, under modules for its directories; one for each stretch between
//! two files, under `unplaced`; and one for the C runtime. A row is a start, an end, and the
//! fragment's path in the tree, its modules and name separated by `/`.

const std = @import("std");
const Io = std.Io;

const openreliant = @import("openreliant");
const sources = openreliant.lancer.sources;
const libcmt = openreliant.lancer.libcmt;

/// The directory every path starts from, which the tree leaves out.
const root = "C:\\lancer\\";

pub fn write(w: *Io.Writer) Io.Writer.Error!void {
    try w.writeAll("# Generated by ghidragen sources from src/lancer/sources.zig: start, end (exclusive), tree path.\n");
    var previous: ?[]const u8 = null;
    var at: u32 = sources.first_function;
    for (sources.files) |file| {
        const range = file.code orelse continue;
        const name = baseName(file.path);
        if (range.start > at) try gap(w, at, range.start, previous, name);
        try w.print("{x:0>8}\t{x:0>8}\t", .{ range.start, range.end });
        try treePath(w, file.path);
        try w.writeByte('\n');
        at = range.end;
        previous = name;
    }
    if (libcmt.code.start > at) try gap(w, at, libcmt.code.start, previous, null);
    try w.print("{x:0>8}\t{x:0>8}\tLIBCMT\n", .{ libcmt.code.start, libcmt.code.end });
}

fn gap(w: *Io.Writer, start: u32, end: u32, before: ?[]const u8, after: ?[]const u8) Io.Writer.Error!void {
    try w.print("{x:0>8}\t{x:0>8}\tunplaced/", .{ start, end });
    if (before) |a| {
        if (after) |b| try w.print("{s} .. {s}\n", .{ a, b }) else try w.print("after {s}\n", .{a});
    } else {
        try w.print("before {s}\n", .{after.?});
    }
}

fn baseName(path: []const u8) []const u8 {
    const slash = std.mem.lastIndexOfScalar(u8, path, '\\') orelse return path;
    return path[slash + 1 ..];
}

/// The path below `root`, with `/` between its parts.
fn treePath(w: *Io.Writer, path: []const u8) Io.Writer.Error!void {
    const relative = if (std.ascii.startsWithIgnoreCase(path, root)) path[root.len..] else path;
    for (relative) |c| try w.writeByte(if (c == '\\') '/' else c);
}

test write {
    var buffer: [16 << 10]u8 = undefined;
    var w: Io.Writer = .fixed(&buffer);
    try write(&w);
    const rows = w.buffered();
    try std.testing.expect(std.mem.indexOf(u8, rows, "\tgame/Ai.cpp\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, rows, "\tinterface/loadout/loadout.cpp\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, rows, "\tsurrender/surrenderlib/srAPI.cpp\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, rows, "00401000\t") != null);
    try std.testing.expect(std.mem.indexOf(u8, rows, "\tunplaced/before Ai.cpp\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, rows, "\tunplaced/Ai.cpp .. aidefend.cpp\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, rows, "\tLIBCMT\n") != null);

    // The rows tile the code without overlapping.
    var lines = std.mem.splitScalar(u8, rows, '\n');
    var end: u32 = 0;
    while (lines.next()) |line| {
        if (line.len == 0 or line[0] == '#') continue;
        const start = try std.fmt.parseInt(u32, line[0..8], 16);
        try std.testing.expect(start >= end);
        end = try std.fmt.parseInt(u32, line[9..17], 16);
        try std.testing.expect(end > start);
    }
}
