//! The words of `ship_combat_stats` that the executable holds rather than `shipstats.bin`:
//! for each ship type, whether its objects can be targeted, the string that names it, its
//! class and its side.
//!
//! Generated by `src/tools/tablegen` from the payload executable's `ship_combat_stats` at
//! 0x004FC670. Do not edit by hand; run `make combat-tables`.

const create = @import("../create.zig");
const gameobj = @import("../gameobj.zig");

/// What a ship type's record holds besides its figures from `shipstats.bin`.
pub const Static = struct {
    /// Whether its objects can be picked as targets (`ShipCombat.Targeting`).
    targetable: bool,
    /// The language string that names it.
    name: u16,
    class: create.ShipCombat.Class,
    /// The side its objects start on.
    side: gameobj.Side(i16),
    /// **Unknown.** 0 or 1.
    unknown_2c: u32,
};

/// Every ship type's, by its number.
pub const ship_types = [256]Static{
    // 0x00
    .{ .targetable = true, .name = 8, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0x01
    .{ .targetable = true, .name = 3, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0x02
    .{ .targetable = true, .name = 17, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0x03
    .{ .targetable = true, .name = 16, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0x04
    .{ .targetable = true, .name = 19, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0x05
    .{ .targetable = true, .name = 15, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0x06
    .{ .targetable = true, .name = 142, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0x07
    .{ .targetable = true, .name = 141, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0x08
    .{ .targetable = true, .name = 18, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0x09
    .{ .targetable = true, .name = 21, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0x0A
    .{ .targetable = true, .name = 2, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0x0B
    .{ .targetable = true, .name = 1, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0x0C
    .{ .targetable = true, .name = 644, .class = .capital, .side = .friendly, .unknown_2c = 1 },
    // 0x0D
    .{ .targetable = true, .name = 4, .class = .capital, .side = .friendly, .unknown_2c = 1 },
    // 0x0E
    .{ .targetable = false, .name = 0, .class = .capital, .side = .friendly, .unknown_2c = 0 },
    // 0x0F
    .{ .targetable = true, .name = 156, .class = .capital, .side = .friendly, .unknown_2c = 1 },
    // 0x10
    .{ .targetable = false, .name = 0, .class = .capital, .side = .friendly, .unknown_2c = 0 },
    // 0x11
    .{ .targetable = true, .name = 159, .class = .capital, .side = .friendly, .unknown_2c = 1 },
    // 0x12
    .{ .targetable = true, .name = 1049, .class = .capital, .side = .friendly, .unknown_2c = 1 },
    // 0x13
    .{ .targetable = true, .name = 1050, .class = .capital, .side = .friendly, .unknown_2c = 1 },
    // 0x14
    .{ .targetable = true, .name = 155, .class = .capital, .side = .friendly, .unknown_2c = 1 },
    // 0x15
    .{ .targetable = false, .name = 0, .class = .capital, .side = .friendly, .unknown_2c = 0 },
    // 0x16
    .{ .targetable = true, .name = 143, .class = .capital, .side = .friendly, .unknown_2c = 1 },
    // 0x17
    .{ .targetable = true, .name = 7, .class = .support, .side = .friendly, .unknown_2c = 0 },
    // 0x18
    .{ .targetable = true, .name = 14, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0x19
    .{ .targetable = true, .name = 20, .class = .support, .side = .friendly, .unknown_2c = 0 },
    // 0x1A
    .{ .targetable = true, .name = 1053, .class = .support, .side = .friendly, .unknown_2c = 0 },
    // 0x1B
    .{ .targetable = false, .name = 0, .class = .support, .side = .friendly, .unknown_2c = 0 },
    // 0x1C
    .{ .targetable = true, .name = 1054, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0x1D
    .{ .targetable = true, .name = 163, .class = .support, .side = .friendly, .unknown_2c = 0 },
    // 0x1E
    .{ .targetable = true, .name = 149, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0x1F
    .{ .targetable = true, .name = 13, .class = .support, .side = .friendly, .unknown_2c = 0 },
    // 0x20
    .{ .targetable = true, .name = 157, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0x21
    .{ .targetable = true, .name = 148, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0x22
    .{ .targetable = false, .name = 0, .class = .support, .side = .friendly, .unknown_2c = 0 },
    // 0x23
    .{ .targetable = false, .name = 0, .class = .support, .side = .friendly, .unknown_2c = 0 },
    // 0x24
    .{ .targetable = false, .name = 0, .class = .support, .side = .friendly, .unknown_2c = 0 },
    // 0x25
    .{ .targetable = true, .name = 158, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0x26
    .{ .targetable = false, .name = 0, .class = .support, .side = .friendly, .unknown_2c = 0 },
    // 0x27
    .{ .targetable = true, .name = 1055, .class = .fighter, .side = .hostile, .unknown_2c = 0 },
    // 0x28
    .{ .targetable = true, .name = 5, .class = .fighter, .side = .hostile, .unknown_2c = 0 },
    // 0x29
    .{ .targetable = true, .name = 1062, .class = .fighter, .side = .hostile, .unknown_2c = 0 },
    // 0x2A
    .{ .targetable = true, .name = 1061, .class = .fighter, .side = .hostile, .unknown_2c = 0 },
    // 0x2B
    .{ .targetable = true, .name = 11, .class = .fighter, .side = .hostile, .unknown_2c = 0 },
    // 0x2C
    .{ .targetable = true, .name = 1056, .class = .fighter, .side = .hostile, .unknown_2c = 0 },
    // 0x2D
    .{ .targetable = true, .name = 1057, .class = .support, .side = .hostile, .unknown_2c = 0 },
    // 0x2E
    .{ .targetable = true, .name = 1058, .class = .fighter, .side = .hostile, .unknown_2c = 0 },
    // 0x2F
    .{ .targetable = false, .name = 0, .class = .fighter, .side = .hostile, .unknown_2c = 0 },
    // 0x30
    .{ .targetable = true, .name = 1059, .class = .fighter, .side = .hostile, .unknown_2c = 0 },
    // 0x31
    .{ .targetable = true, .name = 1060, .class = .fighter, .side = .hostile, .unknown_2c = 0 },
    // 0x32
    .{ .targetable = true, .name = 1063, .class = .fighter, .side = .hostile, .unknown_2c = 0 },
    // 0x33
    .{ .targetable = false, .name = 0, .class = .capital, .side = .hostile, .unknown_2c = 0 },
    // 0x34
    .{ .targetable = true, .name = 1064, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0x35
    .{ .targetable = true, .name = 1066, .class = .capital, .side = .hostile, .unknown_2c = 0 },
    // 0x36
    .{ .targetable = true, .name = 1071, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0x37
    .{ .targetable = true, .name = 12, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0x38
    .{ .targetable = true, .name = 1076, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0x39
    .{ .targetable = true, .name = 0, .class = .support, .side = .hostile, .unknown_2c = 0 },
    // 0x3A
    .{ .targetable = true, .name = 162, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x3B
    .{ .targetable = true, .name = 1077, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x3C
    .{ .targetable = true, .name = 10, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x3D
    .{ .targetable = true, .name = 1078, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x3E
    .{ .targetable = true, .name = 6, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x3F
    .{ .targetable = true, .name = 1079, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x40
    .{ .targetable = true, .name = 1074, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0x41
    .{ .targetable = true, .name = 1080, .class = .fighter, .side = .hostile, .unknown_2c = 0 },
    // 0x42
    .{ .targetable = true, .name = 1081, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x43
    .{ .targetable = true, .name = 1082, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x44
    .{ .targetable = true, .name = 1083, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x45
    .{ .targetable = true, .name = 1084, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x46
    .{ .targetable = true, .name = 151, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x47
    .{ .targetable = true, .name = 1085, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x48
    .{ .targetable = true, .name = 1086, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x49
    .{ .targetable = true, .name = 9, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x4A
    .{ .targetable = false, .name = 0, .class = .torpedo, .side = .friendly, .unknown_2c = 1 },
    // 0x4B
    .{ .targetable = false, .name = 0, .class = .other, .side = .friendly, .unknown_2c = 1 },
    // 0x4C
    .{ .targetable = false, .name = 0, .class = .other, .side = .friendly, .unknown_2c = 1 },
    // 0x4D
    .{ .targetable = true, .name = 1087, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0x4E
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x4F
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x50
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x51
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x52
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x53
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x54
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x55
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x56
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x57
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x58
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x59
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x5A
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x5B
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x5C
    .{ .targetable = true, .name = 150, .class = .torpedo, .side = .hostile, .unknown_2c = 1 },
    // 0x5D
    .{ .targetable = false, .name = 0, .class = .other, .side = .neutral, .unknown_2c = 1 },
    // 0x5E
    .{ .targetable = true, .name = 1089, .class = .capital, .side = .friendly, .unknown_2c = 1 },
    // 0x5F
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0x60
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0x61
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0x62
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0x63
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0x64
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0x65
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0x66
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0x67
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0x68
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0x69
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0x6A
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0x6B
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x6C
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x6D
    .{ .targetable = true, .name = 152, .class = .other, .side = .hostile, .unknown_2c = 1 },
    // 0x6E
    .{ .targetable = true, .name = 1091, .class = .other, .side = .hostile, .unknown_2c = 1 },
    // 0x6F
    .{ .targetable = true, .name = 160, .class = .mine, .side = .hostile, .unknown_2c = 1 },
    // 0x70
    .{ .targetable = true, .name = 161, .class = .other, .side = .neutral, .unknown_2c = 1 },
    // 0x71
    .{ .targetable = true, .name = 1092, .class = .other, .side = .friendly, .unknown_2c = 1 },
    // 0x72
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x73
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x74
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x75
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x76
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x77
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x78
    .{ .targetable = true, .name = 1067, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0x79
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x7A
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x7B
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x7C
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x7D
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x7E
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x7F
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x80
    .{ .targetable = true, .name = 1093, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0x81
    .{ .targetable = true, .name = 1094, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0x82
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x83
    .{ .targetable = true, .name = 1095, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x84
    .{ .targetable = true, .name = 1096, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0x85
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x86
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x87
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x88
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x89
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x8A
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x8B
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x8C
    .{ .targetable = false, .name = 0, .class = .other, .side = .neutral, .unknown_2c = 0 },
    // 0x8D
    .{ .targetable = true, .name = 1120, .class = .other, .side = .friendly, .unknown_2c = 1 },
    // 0x8E
    .{ .targetable = true, .name = 1097, .class = .other, .side = .friendly, .unknown_2c = 0 },
    // 0x8F
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x90
    .{ .targetable = true, .name = 1098, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x91
    .{ .targetable = true, .name = 643, .class = .other, .side = .friendly, .unknown_2c = 1 },
    // 0x92
    .{ .targetable = true, .name = 1101, .class = .other, .side = .hostile, .unknown_2c = 1 },
    // 0x93
    .{ .targetable = true, .name = 1102, .class = .other, .side = .hostile, .unknown_2c = 1 },
    // 0x94
    .{ .targetable = true, .name = 1103, .class = .other, .side = .hostile, .unknown_2c = 1 },
    // 0x95
    .{ .targetable = true, .name = 0, .class = .other, .side = .hostile, .unknown_2c = 1 },
    // 0x96
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0x97
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x98
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0x99
    .{ .targetable = true, .name = 1104, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x9A
    .{ .targetable = true, .name = 1075, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x9B
    .{ .targetable = true, .name = 1105, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0x9C
    .{ .targetable = true, .name = 1065, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0x9D
    .{ .targetable = false, .name = 1090, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0x9E
    .{ .targetable = true, .name = 1052, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0x9F
    .{ .targetable = true, .name = 1106, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0xA0
    .{ .targetable = true, .name = 1051, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0xA1
    .{ .targetable = true, .name = 1108, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0xA2
    .{ .targetable = true, .name = 1110, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0xA3
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xA4
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xA5
    .{ .targetable = true, .name = 1111, .class = .other, .side = .hostile, .unknown_2c = 1 },
    // 0xA6
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xA7
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xA8
    .{ .targetable = true, .name = 1112, .class = .other, .side = .hostile, .unknown_2c = 1 },
    // 0xA9
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xAA
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xAB
    .{ .targetable = false, .name = 0, .class = .other, .side = .neutral, .unknown_2c = 0 },
    // 0xAC
    .{ .targetable = false, .name = 0, .class = .other, .side = .neutral, .unknown_2c = 0 },
    // 0xAD
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xAE
    .{ .targetable = false, .name = 0, .class = .debris, .side = .neutral, .unknown_2c = 0 },
    // 0xAF
    .{ .targetable = true, .name = 1113, .class = .other, .side = .hostile, .unknown_2c = 1 },
    // 0xB0
    .{ .targetable = true, .name = 1107, .class = .other, .side = .hostile, .unknown_2c = 1 },
    // 0xB1
    .{ .targetable = false, .name = 0, .class = .other, .side = .hostile, .unknown_2c = 0 },
    // 0xB2
    .{ .targetable = false, .name = 0, .class = .other, .side = .hostile, .unknown_2c = 0 },
    // 0xB3
    .{ .targetable = false, .name = 0, .class = .other, .side = .hostile, .unknown_2c = 0 },
    // 0xB4
    .{ .targetable = false, .name = 0, .class = .other, .side = .hostile, .unknown_2c = 0 },
    // 0xB5
    .{ .targetable = false, .name = 0, .class = .other, .side = .hostile, .unknown_2c = 0 },
    // 0xB6
    .{ .targetable = false, .name = 0, .class = .other, .side = .hostile, .unknown_2c = 0 },
    // 0xB7
    .{ .targetable = false, .name = 0, .class = .other, .side = .hostile, .unknown_2c = 0 },
    // 0xB8
    .{ .targetable = false, .name = 0, .class = .other, .side = .hostile, .unknown_2c = 0 },
    // 0xB9
    .{ .targetable = true, .name = 1114, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0xBA
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xBB
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xBC
    .{ .targetable = false, .name = 0, .class = .other, .side = .friendly, .unknown_2c = 0 },
    // 0xBD
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xBE
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xBF
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xC0
    .{ .targetable = true, .name = 1115, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0xC1
    .{ .targetable = true, .name = 1116, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0xC2
    .{ .targetable = true, .name = 1070, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0xC3
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xC4
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xC5
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xC6
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xC7
    .{ .targetable = true, .name = 1117, .class = .capital, .side = .friendly, .unknown_2c = 1 },
    // 0xC8
    .{ .targetable = true, .name = 1118, .class = .capital, .side = .friendly, .unknown_2c = 1 },
    // 0xC9
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0xCA
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0xCB
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0xCC
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0xCD
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0xCE
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0xCF
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0xD0
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0xD1
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0xD2
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0xD3
    .{ .targetable = false, .name = 0, .class = .planet, .side = .neutral, .unknown_2c = 0 },
    // 0xD4
    .{ .targetable = false, .name = 0, .class = .other, .side = .neutral, .unknown_2c = 0 },
    // 0xD5
    .{ .targetable = false, .name = 0, .class = .other, .side = .neutral, .unknown_2c = 0 },
    // 0xD6
    .{ .targetable = false, .name = 0, .class = .other, .side = .neutral, .unknown_2c = 0 },
    // 0xD7
    .{ .targetable = true, .name = 1119, .class = .other, .side = .friendly, .unknown_2c = 0 },
    // 0xD8
    .{ .targetable = false, .name = 0, .class = .other, .side = .hostile, .unknown_2c = 0 },
    // 0xD9
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xDA
    .{ .targetable = true, .name = 1048, .class = .capital, .side = .friendly, .unknown_2c = 1 },
    // 0xDB
    .{ .targetable = true, .name = 1068, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0xDC
    .{ .targetable = true, .name = 1069, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0xDD
    .{ .targetable = true, .name = 1072, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0xDE
    .{ .targetable = true, .name = 1073, .class = .capital, .side = .hostile, .unknown_2c = 1 },
    // 0xDF
    .{ .targetable = true, .name = 1088, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0xE0
    .{ .targetable = true, .name = 1099, .class = .support, .side = .hostile, .unknown_2c = 1 },
    // 0xE1
    .{ .targetable = true, .name = 1100, .class = .other, .side = .hostile, .unknown_2c = 1 },
    // 0xE2
    .{ .targetable = true, .name = 1109, .class = .other, .side = .hostile, .unknown_2c = 1 },
    // 0xE3
    .{ .targetable = true, .name = 1121, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0xE4
    .{ .targetable = true, .name = 1122, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0xE5
    .{ .targetable = true, .name = 1123, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0xE6
    .{ .targetable = true, .name = 1124, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0xE7
    .{ .targetable = true, .name = 1125, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0xE8
    .{ .targetable = true, .name = 1126, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0xE9
    .{ .targetable = true, .name = 1127, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0xEA
    .{ .targetable = true, .name = 1128, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0xEB
    .{ .targetable = true, .name = 1129, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0xEC
    .{ .targetable = true, .name = 1130, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0xED
    .{ .targetable = true, .name = 1131, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0xEE
    .{ .targetable = true, .name = 1132, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0xEF
    .{ .targetable = true, .name = 1133, .class = .support, .side = .friendly, .unknown_2c = 1 },
    // 0xF0
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xF1
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xF2
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xF3
    .{ .targetable = false, .name = 0, .class = .capital, .side = .neutral, .unknown_2c = 1 },
    // 0xF4
    .{ .targetable = true, .name = 8, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0xF5
    .{ .targetable = true, .name = 3, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0xF6
    .{ .targetable = true, .name = 17, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0xF7
    .{ .targetable = true, .name = 16, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0xF8
    .{ .targetable = true, .name = 19, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0xF9
    .{ .targetable = true, .name = 15, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0xFA
    .{ .targetable = true, .name = 142, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0xFB
    .{ .targetable = true, .name = 141, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0xFC
    .{ .targetable = true, .name = 18, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0xFD
    .{ .targetable = true, .name = 21, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0xFE
    .{ .targetable = true, .name = 2, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
    // 0xFF
    .{ .targetable = true, .name = 1, .class = .fighter, .side = .friendly, .unknown_2c = 0 },
};
