//! The models the engine loads by number: one for each ship type, and those it mounts on
//! attachment points, by kind and id.
//!
//! Generated by `src/tools/tablegen` from the payload executable: the ship type table at
//! 0x004F7490, and the loader at 0x0045DE70 that fills the attachment table at 0x00538CA8. The
//! file names are the engine's own. Do not edit by hand; run `make model-tables`.

const Kind = @import("../../../formats/shp.zig").Attachment.Kind;

/// A ship type's model, and the sprite of it the comms screen shows. Types are numbered like
/// the records of `shipstats.bin`.
pub const ShipType = struct {
    model: ?[]const u8,
    schematic: ?[]const u8,
};

/// What the engine loads for attachment points of one kind and id.
pub const Attachment = struct {
    model: ?[]const u8 = null,
    /// A second model loaded with the first: the missile, for a missile pod.
    second_model: ?[]const u8 = null,
    /// **Unknown.** 1 unless the loader sets it.
    count: u32 = 1,
    sprite: ?[]const u8 = null,
};

pub const ids_per_kind = 20;

pub const ship_types = [_]ShipType{
    // 0x00
    .{ .model = "uslf_prd.shp", .schematic = "predscem.spr" },
    // 0x01
    .{ .model = "jlf_nagi.shp", .schematic = "nagiscem.spr" },
    // 0x02
    .{ .model = "german_grendal.shp", .schematic = "grenscem.spr" },
    // 0x03
    .{ .model = "british_crusader.shp", .schematic = "crusscem.spr" },
    // 0x04
    .{ .model = "usa_coyote.shp", .schematic = "coyoscem.spr" },
    // 0x05
    .{ .model = "french_mirage.shp", .schematic = "mirascem.spr" },
    // 0x06
    .{ .model = "british_tempest.shp", .schematic = "tempscem.spr" },
    // 0x07
    .{ .model = "usmf_pat.shp", .schematic = "patrscem.spr" },
    // 0x08
    .{ .model = "german_wolverine.shp", .schematic = "wolvscem.spr" },
    // 0x09
    .{ .model = "ushf_reaper.shp", .schematic = "reapscem.spr" },
    // 0x0A
    .{ .model = "jap_shroud.shp", .schematic = "shroscem.spr" },
    // 0x0B
    .{ .model = "uspf_phx.shp", .schematic = "phxscem.spr" },
    // 0x0C
    .{ .model = "reliant.shp", .schematic = "reliscem.spr" },
    // 0x0D
    .{ .model = "yamato.shp", .schematic = "yamascem.spr" },
    // 0x0E
    .{ .model = null, .schematic = null },
    // 0x0F
    .{ .model = "kestrel.shp", .schematic = "kestscem.spr" },
    // 0x10
    .{ .model = null, .schematic = null },
    // 0x11
    .{ .model = "victorious.shp", .schematic = "victscem.spr" },
    // 0x12
    .{ .model = "endeavour.shp", .schematic = "endescem.spr" },
    // 0x13
    .{ .model = "mitchell.shp", .schematic = "mitcscem.spr" },
    // 0x14
    .{ .model = "bremen.shp", .schematic = "bremscem.spr" },
    // 0x15
    .{ .model = null, .schematic = null },
    // 0x16
    .{ .model = "ulysses.shp", .schematic = "ulysscem.spr" },
    // 0x17
    .{ .model = "jap_sai.shp", .schematic = "saiscem.spr" },
    // 0x18
    .{ .model = "nanny.shp", .schematic = "nannscem.spr" },
    // 0x19
    .{ .model = "btb_glhd.shp", .schematic = "galascem.spr" },
    // 0x1A
    .{ .model = "ustb_hds.shp", .schematic = "hadescem.spr" },
    // 0x1B
    .{ .model = null, .schematic = null },
    // 0x1C
    .{ .model = "lonestar.shp", .schematic = "lonescem.spr" },
    // 0x1D
    .{ .model = "limpet_t_car.shp", .schematic = "boarscem.spr" },
    // 0x1E
    .{ .model = "us_prowler.shp", .schematic = "prowscem.spr" },
    // 0x1F
    .{ .model = "ripper_2.shp", .schematic = "ripscem.spr" },
    // 0x20
    .{ .model = "lueneburg.shp", .schematic = "luenscem.spr" },
    // 0x21
    .{ .model = "a_mammoth.shp", .schematic = "mammscem.spr" },
    // 0x22
    .{ .model = null, .schematic = null },
    // 0x23
    .{ .model = null, .schematic = null },
    // 0x24
    .{ .model = null, .schematic = null },
    // 0x25
    .{ .model = "stork.shp", .schematic = "storscem.spr" },
    // 0x26
    .{ .model = null, .schematic = null },
    // 0x27
    .{ .model = "chin_han.shp", .schematic = "haidscem.spr" },
    // 0x28
    .{ .model = "chin_zhuhai.shp", .schematic = "karascem.spr" },
    // 0x29
    .{ .model = "luda.shp", .schematic = "saliscem.spr" },
    // 0x2A
    .{ .model = "houjian.shp", .schematic = "azanscem.spr" },
    // 0x2B
    .{ .model = "rus_sabre.shp", .schematic = "sabrscem.spr" },
    // 0x2C
    .{ .model = "rus_lagg.shp", .schematic = "laggscem.spr" },
    // 0x2D
    .{ .model = "rus_kamov.shp", .schematic = "kamoscem.spr" },
    // 0x2E
    .{ .model = "mid_saracen.shp", .schematic = "sarascem.spr" },
    // 0x2F
    .{ .model = null, .schematic = null },
    // 0x30
    .{ .model = "scimitar.shp", .schematic = "scimscem.spr" },
    // 0x31
    .{ .model = "rus_basalisk.shp", .schematic = "basiscem.spr" },
    // 0x32
    .{ .model = "rus_kossac.shp", .schematic = "kossscem.spr" },
    // 0x33
    .{ .model = null, .schematic = null },
    // 0x34
    .{ .model = "ramases.shp", .schematic = "ramascem.spr" },
    // 0x35
    .{ .model = "krasnaya.shp", .schematic = "krasscem.spr" },
    // 0x36
    .{ .model = "kiev.shp", .schematic = "morzscem.spr" },
    // 0x37
    .{ .model = "cs_badanov.shp", .schematic = "badascem.spr" },
    // 0x38
    .{ .model = "pukov.shp", .schematic = "pukoscem.spr" },
    // 0x39
    .{ .model = null, .schematic = null },
    // 0x3A
    .{ .model = "song.shp", .schematic = "rizascem.spr" },
    // 0x3B
    .{ .model = "cyclops.shp", .schematic = "cyclscem.spr" },
    // 0x3C
    .{ .model = "rus_kurgan.shp", .schematic = "kurgscem.spr" },
    // 0x3D
    .{ .model = "sharov.shp", .schematic = "shavscem.spr" },
    // 0x3E
    .{ .model = "rmc_gurevich.shp", .schematic = "gurescem.spr" },
    // 0x3F
    .{ .model = "berijev.shp", .schematic = "beriscem.spr" },
    // 0x40
    .{ .model = "kiev.shp", .schematic = "kievscem.spr" },
    // 0x41
    .{ .model = "crp_loki.shp", .schematic = "lokiscem.spr" },
    // 0x42
    .{ .model = "cld_scarab.shp", .schematic = "kalascem.spr" },
    // 0x43
    .{ .model = "saladin.shp", .schematic = "salascem.spr" },
    // 0x44
    .{ .model = "darkreign.shp", .schematic = "dreiscem.spr" },
    // 0x45
    .{ .model = "stalag.shp", .schematic = "stalscem.spr" },
    // 0x46
    .{ .model = "antanov.shp", .schematic = "antascem.spr" },
    // 0x47
    .{ .model = "kronstadt.shp", .schematic = "kronscem.spr" },
    // 0x48
    .{ .model = "boridin.shp", .schematic = "boriscem.spr" },
    // 0x49
    .{ .model = "rus_troopcar.shp", .schematic = "scarscem.spr" },
    // 0x4A
    .{ .model = "torpedo.shp", .schematic = null },
    // 0x4B
    .{ .model = "ulysses2.shp", .schematic = null },
    // 0x4C
    .{ .model = "ulysses3.shp", .schematic = null },
    // 0x4D
    .{ .model = "uly_escape.shp", .schematic = "epodscem.spr" },
    // 0x4E
    .{ .model = "deb_1.shp", .schematic = null },
    // 0x4F
    .{ .model = "deb_2.shp", .schematic = null },
    // 0x50
    .{ .model = "deb_3.shp", .schematic = null },
    // 0x51
    .{ .model = "deb_4.shp", .schematic = null },
    // 0x52
    .{ .model = "deb_5.shp", .schematic = null },
    // 0x53
    .{ .model = "deb_6.shp", .schematic = null },
    // 0x54
    .{ .model = "deb_7.shp", .schematic = null },
    // 0x55
    .{ .model = "deb_8.shp", .schematic = null },
    // 0x56
    .{ .model = "deb_9.shp", .schematic = null },
    // 0x57
    .{ .model = "deb_10.shp", .schematic = null },
    // 0x58
    .{ .model = "rus_man1.shp", .schematic = null },
    // 0x59
    .{ .model = "rus_man2.shp", .schematic = null },
    // 0x5A
    .{ .model = "rus_man3.shp", .schematic = null },
    // 0x5B
    .{ .model = "rus_man4.shp", .schematic = null },
    // 0x5C
    .{ .model = "rus_torp.shp", .schematic = "russtorp.spr" },
    // 0x5D
    .{ .model = "A_mammoth2.shp", .schematic = "mammscem.spr" },
    // 0x5E
    .{ .model = "baxter.shp", .schematic = "baxtscem.spr" },
    // 0x5F
    .{ .model = "neptune_hi_1.shp", .schematic = null },
    // 0x60
    .{ .model = "triton_hi_1.shp", .schematic = null },
    // 0x61
    .{ .model = "uranus_hi_1.shp", .schematic = null },
    // 0x62
    .{ .model = "saturn_hi_ring_2.shp", .schematic = null },
    // 0x63
    .{ .model = "titan_hi_1.shp", .schematic = null },
    // 0x64
    .{ .model = "jupiter_hi_1.shp", .schematic = null },
    // 0x65
    .{ .model = "europa_hi_1.shp", .schematic = null },
    // 0x66
    .{ .model = "grany_hi_1.shp", .schematic = null },
    // 0x67
    .{ .model = "io_hi_1.shp", .schematic = null },
    // 0x68
    .{ .model = "calist_hi_1.shp", .schematic = null },
    // 0x69
    .{ .model = "venus1_hi_1.shp", .schematic = null },
    // 0x6A
    .{ .model = "earth.shp", .schematic = null },
    // 0x6B
    .{ .model = "kronstadt dest.shp", .schematic = null },
    // 0x6C
    .{ .model = "boridin dest.shp", .schematic = null },
    // 0x6D
    .{ .model = "coalprotogate.shp", .schematic = "protscem.spr" },
    // 0x6E
    .{ .model = "coaladvgate.shp", .schematic = "agatscem.spr" },
    // 0x6F
    .{ .model = "mine_prox.shp", .schematic = "proxscem.spr" },
    // 0x70
    .{ .model = "black_box.shp", .schematic = "bboxscem.spr" },
    // 0x71
    .{ .model = "stork_sat.shp", .schematic = "ssatscem.spr" },
    // 0x72
    .{ .model = "mamdest.shp", .schematic = "mammscem.spr" },
    // 0x73
    .{ .model = "mamdest2.shp", .schematic = "mammscem.spr" },
    // 0x74
    .{ .model = "coalprotogate_plates.shp", .schematic = "protscem.spr" },
    // 0x75
    .{ .model = "cs_baddead.shp", .schematic = "badascem.spr" },
    // 0x76
    .{ .model = "cs_baddead2.shp", .schematic = "badascem.spr" },
    // 0x77
    .{ .model = "rus_kurgan_dest.shp", .schematic = "kurgscem.spr" },
    // 0x78
    .{ .model = "krasnaya.shp", .schematic = "krasscem.spr" },
    // 0x79
    .{ .model = "ast_1.shp", .schematic = null },
    // 0x7A
    .{ .model = "ast_2.shp", .schematic = null },
    // 0x7B
    .{ .model = "ast_3.shp", .schematic = null },
    // 0x7C
    .{ .model = "ast_4.shp", .schematic = null },
    // 0x7D
    .{ .model = "ast_5.shp", .schematic = null },
    // 0x7E
    .{ .model = "ast_6.shp", .schematic = null },
    // 0x7F
    .{ .model = "ast_7.shp", .schematic = null },
    // 0x80
    .{ .model = "coalresstat.shp", .schematic = "resbscem.spr" },
    // 0x81
    .{ .model = "latov.shp", .schematic = "latoscem.spr" },
    // 0x82
    .{ .model = "RMC_gurevich_dest.shp", .schematic = null },
    // 0x83
    .{ .model = "training_hoop.shp", .schematic = "trinscem.spr" },
    // 0x84
    .{ .model = "czar_docked.shp", .schematic = "czadscem.spr" },
    // 0x85
    .{ .model = "turast_1.shp", .schematic = null },
    // 0x86
    .{ .model = "turast_2.shp", .schematic = null },
    // 0x87
    .{ .model = "turast_3.shp", .schematic = null },
    // 0x88
    .{ .model = "turast_4.shp", .schematic = null },
    // 0x89
    .{ .model = "turast_5.shp", .schematic = null },
    // 0x8A
    .{ .model = "turast_6.shp", .schematic = null },
    // 0x8B
    .{ .model = "turast_7.shp", .schematic = null },
    // 0x8C
    .{ .model = "DMPowerup.shp", .schematic = null },
    // 0x8D
    .{ .model = "beacongate.shp", .schematic = "nukescem.spr" },
    // 0x8E
    .{ .model = "DMBeacon.shp", .schematic = "beacscem.spr" },
    // 0x8F
    .{ .model = "pukov_dest1.shp", .schematic = null },
    // 0x90
    .{ .model = "ber_escape.shp", .schematic = "escascem.spr" },
    // 0x91
    .{ .model = "us_cargo.shp", .schematic = "cargscem.spr" },
    // 0x92
    .{ .model = "ussr_cargo.shp", .schematic = "car2scem.spr" },
    // 0x93
    .{ .model = "grazer.shp", .schematic = "grazscem.spr" },
    // 0x94
    .{ .model = "archer.shp", .schematic = "archscem.spr" },
    // 0x95
    .{ .model = "kafelnikof.shp", .schematic = "kafescem.spr" },
    // 0x96
    .{ .model = "reliant_destback.shp", .schematic = null },
    // 0x97
    .{ .model = "stalag_doors.shp", .schematic = null },
    // 0x98
    .{ .model = "stalag_ductcover.shp", .schematic = null },
    // 0x99
    .{ .model = "russ_shuttle.shp", .schematic = "yakoscem.spr" },
    // 0x9A
    .{ .model = "krasny.shp", .schematic = "badascem.spr" },
    // 0x9B
    .{ .model = "varyag.shp", .schematic = "varyscem.spr" },
    // 0x9C
    .{ .model = "ramases.shp", .schematic = "ramascem.spr" },
    // 0x9D
    .{ .model = "carter.shp", .schematic = "baxtscem.spr" },
    // 0x9E
    .{ .model = "bremen.shp", .schematic = "bremscem.spr" },
    // 0x9F
    .{ .model = "washington.shp", .schematic = "victscem.spr" },
    // 0xA0
    .{ .model = "mitchell.shp", .schematic = "mitcscem.spr" },
    // 0xA1
    .{ .model = "zakov.shp", .schematic = "zakoscem.spr" },
    // 0xA2
    .{ .model = "zakov.shp", .schematic = "zakoscem.spr" },
    // 0xA3
    .{ .model = "Krasnaya LeftArm.SHP", .schematic = null },
    // 0xA4
    .{ .model = "Krasnaya RightArm.SHP", .schematic = null },
    // 0xA5
    .{ .model = "rogue_base.shp", .schematic = "rbasscem.spr" },
    // 0xA6
    .{ .model = "kronstadt arm.shp", .schematic = null },
    // 0xA7
    .{ .model = "boridin dome.shp", .schematic = null },
    // 0xA8
    .{ .model = "boridin breakaway.shp", .schematic = "borbscem.spr" },
    // 0xA9
    .{ .model = "Darkreign_DestHat.shp", .schematic = null },
    // 0xAA
    .{ .model = "Yamato DestBack.shp", .schematic = null },
    // 0xAB
    .{ .model = "service_droid.shp", .schematic = "sdroscem.spr" },
    // 0xAC
    .{ .model = "service_astronaut.shp", .schematic = null },
    // 0xAD
    .{ .model = "Rogue_base top dest.SHP", .schematic = null },
    // 0xAE
    .{ .model = "rus_tank.shp", .schematic = null },
    // 0xAF
    .{ .model = "shoot_me.shp", .schematic = "ttarscem.spr" },
    // 0xB0
    .{ .model = "zakov.shp", .schematic = "zakoscem.spr" },
    // 0xB1
    .{ .model = "shell.shp", .schematic = null },
    // 0xB2
    .{ .model = "rockchunk00.SHP", .schematic = null },
    // 0xB3
    .{ .model = "rockchunk01.SHP", .schematic = null },
    // 0xB4
    .{ .model = "rockchunk02.SHP", .schematic = null },
    // 0xB5
    .{ .model = "rockchunk03.SHP", .schematic = null },
    // 0xB6
    .{ .model = "rockchunk04.SHP", .schematic = null },
    // 0xB7
    .{ .model = "latov_chunk1.shp", .schematic = null },
    // 0xB8
    .{ .model = "latov_chunk2.shp", .schematic = null },
    // 0xB9
    .{ .model = "czar.shp", .schematic = "czarscem.spr" },
    // 0xBA
    .{ .model = "zakov_FrntDest.SHP", .schematic = null },
    // 0xBB
    .{ .model = "sharov backdest.shp", .schematic = null },
    // 0xBC
    .{ .model = "limpet_pod.shp", .schematic = null },
    // 0xBD
    .{ .model = "stalag dest01.shp", .schematic = null },
    // 0xBE
    .{ .model = "stalag dest02.shp", .schematic = null },
    // 0xBF
    .{ .model = "saladin dest.shp", .schematic = null },
    // 0xC0
    .{ .model = null, .schematic = null },
    // 0xC1
    .{ .model = null, .schematic = null },
    // 0xC2
    .{ .model = "kiev.shp", .schematic = "kievscem.spr" },
    // 0xC3
    .{ .model = "kiev backdest.shp", .schematic = null },
    // 0xC4
    .{ .model = "baxter topdest.shp", .schematic = null },
    // 0xC5
    .{ .model = "victorious frontdest.shp", .schematic = null },
    // 0xC6
    .{ .model = "mitchell_dest.shp", .schematic = null },
    // 0xC7
    .{ .model = "fort bear.shp", .schematic = "bearscem.spr" },
    // 0xC8
    .{ .model = "fort_sherman.shp", .schematic = "sherscem.spr" },
    // 0xC9
    .{ .model = "neptune_lo_1.shp", .schematic = null },
    // 0xCA
    .{ .model = "triton_lo_1.shp", .schematic = null },
    // 0xCB
    .{ .model = "uranus_lo_1.shp", .schematic = null },
    // 0xCC
    .{ .model = "saturn_lo_ring_1.shp", .schematic = null },
    // 0xCD
    .{ .model = "titan_lo_1.shp", .schematic = null },
    // 0xCE
    .{ .model = "jupiter_lo_1.shp", .schematic = null },
    // 0xCF
    .{ .model = "europa_lo_1.shp", .schematic = null },
    // 0xD0
    .{ .model = "grany_lo_1.shp", .schematic = null },
    // 0xD1
    .{ .model = "io_lo_1.shp", .schematic = null },
    // 0xD2
    .{ .model = "calist_lo_1.shp", .schematic = null },
    // 0xD3
    .{ .model = "venus1_lo_1.shp", .schematic = null },
    // 0xD4
    .{ .model = "yam_tube.shp", .schematic = null },
    // 0xD5
    .{ .model = "yamhanger.shp", .schematic = null },
    // 0xD6
    .{ .model = "reliant_hang.shp", .schematic = null },
    // 0xD7
    .{ .model = "comms relay.shp", .schematic = "comsscem.spr" },
    // 0xD8
    .{ .model = "saladin_link.shp", .schematic = null },
    // 0xD9
    .{ .model = "varyag frontdest.shp", .schematic = null },
    // 0xDA
    .{ .model = "kestrel.shp", .schematic = "kestscem.spr" },
    // 0xDB
    .{ .model = "krasnaya.shp", .schematic = "krasscem.spr" },
    // 0xDC
    .{ .model = "krasnaya.shp", .schematic = "krasscem.spr" },
    // 0xDD
    .{ .model = "kiev.shp", .schematic = "kievscem.spr" },
    // 0xDE
    .{ .model = "kiev.shp", .schematic = "kievscem.spr" },
    // 0xDF
    .{ .model = "uly_escape.shp", .schematic = null },
    // 0xE0
    .{ .model = "ber_escape.shp", .schematic = "escascem.spr" },
    // 0xE1
    .{ .model = "fuel_pod1.shp", .schematic = "car2scem.spr" },
    // 0xE2
    .{ .model = "zakov.shp", .schematic = "zakoscem.spr" },
    // 0xE3
    .{ .model = "a_mammoth.shp", .schematic = "mammscem.spr" },
    // 0xE4
    .{ .model = "a_mammoth.shp", .schematic = "mammscem.spr" },
    // 0xE5
    .{ .model = "a_mammoth.shp", .schematic = "mammscem.spr" },
    // 0xE6
    .{ .model = "a_mammoth.shp", .schematic = "mammscem.spr" },
    // 0xE7
    .{ .model = "a_mammoth.shp", .schematic = "mammscem.spr" },
    // 0xE8
    .{ .model = "a_mammoth.shp", .schematic = "mammscem.spr" },
    // 0xE9
    .{ .model = "a_mammoth.shp", .schematic = "mammscem.spr" },
    // 0xEA
    .{ .model = "a_mammoth.shp", .schematic = "mammscem.spr" },
    // 0xEB
    .{ .model = "a_mammoth.shp", .schematic = "mammscem.spr" },
    // 0xEC
    .{ .model = "a_mammoth.shp", .schematic = "mammscem.spr" },
    // 0xED
    .{ .model = "a_mammoth.shp", .schematic = "mammscem.spr" },
    // 0xEE
    .{ .model = "a_mammoth.shp", .schematic = "mammscem.spr" },
    // 0xEF
    .{ .model = "a_mammoth.shp", .schematic = "mammscem.spr" },
    // 0xF0
    .{ .model = "ast_hole1.shp", .schematic = null },
    // 0xF1
    .{ .model = "ast_hole2.shp", .schematic = null },
    // 0xF2
    .{ .model = "ast_hole3.shp", .schematic = null },
    // 0xF3
    .{ .model = "ast_hole4.shp", .schematic = null },
    // 0xF4
    .{ .model = "t_uslf_prd.shp", .schematic = "predscem.spr" },
    // 0xF5
    .{ .model = "t_jlf_nagi.shp", .schematic = "nagiscem.spr" },
    // 0xF6
    .{ .model = "t_german_grendal.shp", .schematic = "grenscem.spr" },
    // 0xF7
    .{ .model = "t_british_crusader.shp", .schematic = "crusscem.spr" },
    // 0xF8
    .{ .model = "t_usa_coyote.shp", .schematic = "coyoscem.spr" },
    // 0xF9
    .{ .model = "t_french_mirage.shp", .schematic = "mirascem.spr" },
    // 0xFA
    .{ .model = "t_british_tempest.shp", .schematic = "tempscem.spr" },
    // 0xFB
    .{ .model = "t_usmf_pat.shp", .schematic = "patrscem.spr" },
    // 0xFC
    .{ .model = "t_german_wolverine.shp", .schematic = "wolvscem.spr" },
    // 0xFD
    .{ .model = "t_ushf_reaper.shp", .schematic = "reapscem.spr" },
    // 0xFE
    .{ .model = "t_jap_shroud.shp", .schematic = "shroscem.spr" },
    // 0xFF
    .{ .model = "t_uspf_phx.shp", .schematic = "phxscem.spr" },
};

/// Indexed by kind, then id.
pub const attachments = [9][ids_per_kind]Attachment{
    // Kind 0: missile
    .{
        .{ .model = "01_screamer_pod.shp", .second_model = "01_screamer.shp", .count = 20 },
        .{ .model = "02_raptor_pod.shp", .second_model = "02_raptor.shp", .count = 3 },
        .{ .model = "03_havoc.shp" },
        .{ .model = "04_jackhammer.shp" },
        .{ .model = "05_bandit.shp" },
        .{ .model = "06_vagabond.shp" },
        .{ .model = "07_solomon_pod.shp", .second_model = "07_solomon.shp", .count = 4 },
        .{ .model = "08_imp.shp" },
        .{ .model = "09_hawk_pod.shp", .second_model = "09_hawk.shp", .count = 4 },
        .{},
        .{ .model = "fuel_pod.shp" },
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
    },
    // Kind 1: gun
    .{
        .{ .model = "01_lasr_can.shp" },
        .{ .model = "02_gat_laser.shp" },
        .{ .model = "03_proton.shp" },
        .{ .model = "04_pulse_las.shp" },
        .{ .model = "05_tachyon_gun.shp" },
        .{ .model = "06_neutron_gun.shp" },
        .{ .model = "07_mass_ion.shp" },
        .{ .model = "08_gat_plasma.shp" },
        .{ .model = "09_rus_btur.shp" },
        .{ .model = "10_rus_stur.shp" },
        .{ .model = "11_al_mtur.shp" },
        .{ .model = "12_light_gun.shp" },
        .{ .model = "13_al_stur.shp" },
        .{ .model = "14_al_stur.shp" },
        .{ .model = "al_mis_tur.shp" },
        .{ .model = "coal_mis_tur.shp" },
        .{ .model = "allied_cap_gun.shp" },
        .{ .model = "col_cap_gun.shp" },
        .{ .model = "gun_base.shp" },
        .{ .model = "small gun_base.shp" },
    },
    // Kind 2: engine_glow
    .{
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
    },
    // Kind 3: gun_muzzle
    .{
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
    },
    // Kind 4: light
    .{
        .{ .sprite = "newflare" },
        .{ .sprite = "newlight" },
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
    },
    // Kind 5: pod
    .{
        .{ .model = "01_cargo_pod.shp" },
        .{ .model = "02_rus_pod.shp" },
        .{},
        .{},
        .{},
        .{ .model = "fuel_pod1.shp" },
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
    },
    // Kind 6: eject_point
    .{
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
    },
    // Kind 7: case_ejector
    .{
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
    },
    // Kind 8: unknown
    .{
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
        .{},
    },
};

/// The ship type numbered `index`, or null past the table.
pub fn shipType(index: usize) ?ShipType {
    return if (index < ship_types.len) ship_types[index] else null;
}

/// What the engine loads for an attachment point, or null when it loads nothing for it.
pub fn attachment(kind: Kind, id: u32) ?Attachment {
    const index = @intFromEnum(kind);
    if (index >= attachments.len or id >= ids_per_kind) return null;
    const entry = attachments[index][id];
    if (entry.model == null and entry.sprite == null) return null;
    return entry;
}

test attachment {
    const std = @import("std");
    try std.testing.expect(attachment(.gun, 0) != null);
    try std.testing.expect(attachment(.gun, ids_per_kind) == null);
    try std.testing.expect(shipType(0).?.model != null);
}
