//! The combat maneuvers the Fight order runs: each one's name, the inputs it may mirror, how long
//! it runs and its script; the routines each opcode of the script language runs; and the lists
//! Fight picks a maneuver from. `docs/engine/maneuvers.md` describes them.
//!
//! Generated by `src/tools/tablegen` from the payload executable's maneuver table at
//! 0x004E1070, 10 maneuvers, its handler table at 0x004E0CC0 and its choice lists at
//! 0x004E1918. Names and scripts are the developers' own. Do not edit by hand; run
//! `make maneuver-tables`.

const std = @import("std");

const script = @import("script.zig");
pub const Opcode = script.Opcode;
pub const Mirror = @import("../aidefend.zig").Mirror;

/// Where the tables are in the payload executable.
pub const addresses = struct {
    pub const table: u32 = 0x004E1070;
    pub const handlers: u32 = 0x004E0CC0;
    pub const choices: u32 = 0x004E1918;
};

/// Every maneuver, numbered as the game numbers them.
pub const Maneuver = enum(u16) {
    defend_dodge1 = 0,
    defend_dodge2 = 1,
    defend_dodge3 = 2,
    out_of_action_sphere = 3,
    defend_runaway = 4,
    attack_pursue = 5,
    attack_massive_object = 6,
    attack_medium_fighter = 7,
    loop_the_loop = 8,
    run_to_ship = 9,
    _,
};

pub const Info = struct {
    maneuver: Maneuver,
    /// The developers' name.
    name: []const u8,
    /// The inputs it may mirror, a random choice of them each time it starts.
    mirror: Mirror,
    /// How long it runs, in ticks, unless Fight says otherwise.
    min_ticks: u16,
    max_ticks: u16,
    /// Where its script is in the payload executable.
    script_address: u32,
    script: []const []const u8,
};

/// Every maneuver, by number.
pub const table = [_]Info{
    .{
        .maneuver = .defend_dodge1,
        .name = "defend dodge1",
        .mirror = @bitCast(@as(u8, 0x05)),
        .min_ticks = 400,
        .max_ticks = 1000,
        .script_address = 0x004E0D70,
        .script = &.{
            "Cloak(on)",
            "SetAfterburner(off)",
            "loop:",
            "\tSetMirror",
            "\tSetAfterburner(on)",
            "\tRunAway(50, 100)",
            "\tSetPitch(1)",
            "\tSetRoll(1)",
            "\tSetYaw(0)",
            "\tSetSpeed(1)",
            "\tSetAfterburner(on)",
            "\tWait(40, 80)",
            "\tSetRoll(-1)",
            "\tSetPitch(0)",
            "\tSetAfterburner(on)",
            "\tWait(100, 200)",
            "\tGoto loop",
        },
    },
    .{
        .maneuver = .defend_dodge2,
        .name = "defend dodge2",
        .mirror = @bitCast(@as(u8, 0x05)),
        .min_ticks = 400,
        .max_ticks = 1000,
        .script_address = 0x004E0E00,
        .script = &.{
            "Cloak(on)",
            "SetAfterburner(off)",
            "SetYaw(0)",
            "SetSpeed(1)",
            "loop:",
            "\tSetMirror",
            "\tSetPitch(0.5, 1)",
            "\tSetRoll(0)",
            "\tSetAfterburner(on)",
            "\tWait(200, 400)",
            "\tSetPitch(0)",
            "\tSetRoll(1)",
            "\tSetAfterburner(on)",
            "\tWait(50, 100)",
            "\tGoto loop",
        },
    },
    .{
        .maneuver = .defend_dodge3,
        .name = "defend dodge3",
        .mirror = @bitCast(@as(u8, 0x05)),
        .min_ticks = 400,
        .max_ticks = 1000,
        .script_address = 0x004E0E80,
        .script = &.{
            "Cloak(on)",
            "SetAfterburner(off)",
            "SetYaw(0)",
            "SetSpeed(1)",
            "loop:",
            "\tSetMirror",
            "\tSetRoll(1)",
            "\tSetPitch(0.5, 1)",
            "\tSetAfterburner(on)",
            "\tWait(200, 400)",
            "\tGoto loop",
        },
    },
    .{
        .maneuver = .out_of_action_sphere,
        .name = "out of action sphere",
        .mirror = @bitCast(@as(u8, 0x00)),
        .min_ticks = 1000,
        .max_ticks = 1500,
        .script_address = 0x004E0EE0,
        .script = &.{
            "SetAfterburner(off)",
            "loop:",
            "\tOutofactionsphere(1000)",
            "\tGoto loop",
        },
    },
    .{
        .maneuver = .defend_runaway,
        .name = "defend runaway",
        .mirror = @bitCast(@as(u8, 0x00)),
        .min_ticks = 200,
        .max_ticks = 300,
        .script_address = 0x004E0F08,
        .script = &.{
            "SetAfterburner(off)",
            "Cloak(on)",
            "loop:",
            "\tSetAfterburner(on)",
            "\tRunaway(100)",
            "\tGoto loop",
        },
    },
    .{
        .maneuver = .attack_pursue,
        .name = "attack pursue",
        .mirror = @bitCast(@as(u8, 0x00)),
        .min_ticks = 200,
        .max_ticks = 300,
        .script_address = 0x004E0F40,
        .script = &.{
            "Cloak(off)",
            "SetAfterburner(off)",
            "loop:",
            "\tIf Goingtocrash",
            "\t\tAvoid(300)",
            "\tEndif",
            "\tAttack(25)",
            "\tGoto loop",
        },
    },
    .{
        .maneuver = .attack_massive_object,
        .name = "attack massive object",
        .mirror = @bitCast(@as(u8, 0x00)),
        .min_ticks = 20000,
        .max_ticks = 25000,
        .script_address = 0x004E0F88,
        .script = &.{
            "Cloak(on)",
            "SetAfterburner(off)",
            "NewAttackRun(true)",
            "loop:",
            "\tCloak(off)",
            "\tAttackmassive()",
            "\tCloak(on)",
            "\tNewAttackRun(false)",
            "\tGoto loop",
        },
    },
    .{
        .maneuver = .attack_medium_fighter,
        .name = "attack medium fighter",
        .mirror = @bitCast(@as(u8, 0x00)),
        .min_ticks = 10000,
        .max_ticks = 15000,
        .script_address = 0x004E0FD8,
        .script = &.{
            "SetAfterburner(off)",
            "loop:",
            "\tAttackMediumFighter(100)",
            "\tGoto loop",
        },
    },
    .{
        .maneuver = .loop_the_loop,
        .name = "loop the loop",
        .mirror = @bitCast(@as(u8, 0x00)),
        .min_ticks = 200,
        .max_ticks = 1000,
        .script_address = 0x004E1000,
        .script = &.{
            "Cloak(on)",
            "SetAfterburner(off)",
            "SetPitch(1)",
            "SetYaw(0)",
            "SetRoll(0)",
            "SetSpeed(0.5)",
            "loop:",
            "\tWait(1000)",
            "\tGoto loop",
        },
    },
    .{
        .maneuver = .run_to_ship,
        .name = "run to ship",
        .mirror = @bitCast(@as(u8, 0x00)),
        .min_ticks = 10000,
        .max_ticks = 15000,
        .script_address = 0x004E1050,
        .script = &.{
            "SetAfterburner(off)",
            "RunToShip()",
            "EndScript()",
        },
    },
};

pub const Handlers = struct {
    /// Runs as an instruction starts; true makes it wait.
    start: ?u32,
    /// Runs each update while the instruction waits; true keeps it waiting.
    run: ?u32,
};

/// What each opcode runs, by address in the payload executable.
pub const handlers: std.EnumArray(Opcode, Handlers) = .init(.{
    .set_yaw = .{ .start = 0x00405960, .run = null },
    .set_pitch = .{ .start = 0x004059E0, .run = null },
    .set_roll = .{ .start = 0x00405A60, .run = null },
    .set_speed = .{ .start = 0x00405AE0, .run = null },
    .wait = .{ .start = 0x00405B20, .run = 0x00405C30 },
    .goto = .{ .start = 0x00405B70, .run = null },
    .label = .{ .start = null, .run = null },
    .set_afterburner = .{ .start = 0x00405B80, .run = null },
    .runaway = .{ .start = 0x00405DA0, .run = 0x00405E60 },
    .attack = .{ .start = 0x00405B20, .run = 0x00405E80 },
    .attack_massive = .{ .start = 0x00405B20, .run = 0x00406030 },
    .out_of_action_sphere = .{ .start = 0x00406110, .run = 0x00405E60 },
    .set_mirror = .{ .start = 0x00406150, .run = null },
    .@"if" = .{ .start = 0x00406170, .run = null },
    .@"else" = .{ .start = 0x00405B70, .run = null },
    .endif = .{ .start = null, .run = null },
    .avoid = .{ .start = 0x00405B20, .run = 0x004062D0 },
    .cloak = .{ .start = 0x004063E0, .run = null },
    .attack_medium_fighter = .{ .start = 0x00405B20, .run = 0x00406400 },
    .new_attack_run = .{ .start = 0x004065D0, .run = 0x00406680 },
    .run_to_ship = .{ .start = 0x00406800, .run = 0x00406840 },
    .end_script = .{ .start = 0x00406990, .run = 0x004069A0 },
});

/// Where one ship is from the other's nose: within 60 degrees of it, abeam, or behind.
pub const Bearing = enum { ahead, abeam, behind };

/// The maneuvers Fight picks from at random, by where its target is from the ship's nose, then
/// where the ship is from the target's.
pub const choices = [3][3][]const Maneuver{
    .{
        &.{ .defend_runaway, .defend_dodge1, .defend_dodge2, .defend_dodge3, .loop_the_loop },
        &.{.attack_pursue},
        &.{.attack_pursue},
    },
    .{
        &.{ .defend_runaway, .defend_dodge1, .defend_dodge2, .defend_dodge3, .loop_the_loop },
        &.{ .defend_runaway, .defend_dodge1, .defend_dodge2, .defend_dodge3, .loop_the_loop },
        &.{.attack_pursue},
    },
    .{
        &.{ .defend_runaway, .defend_dodge1, .defend_dodge2, .defend_dodge3, .loop_the_loop },
        &.{ .defend_runaway, .defend_dodge1, .defend_dodge2, .defend_dodge3, .loop_the_loop },
        &.{.attack_pursue},
    },
};

/// The maneuver numbered `maneuver`, or null past the table.
pub fn info(maneuver: Maneuver) ?Info {
    const index = @intFromEnum(maneuver);
    return if (index < table.len) table[index] else null;
}

/// Each maneuver's script, compiled: a line that does not compile fails the build.
pub const compiled = blk: {
    var out: [table.len][]const script.Instruction = undefined;
    for (table, &out) |entry, *instructions| {
        const lines = script.compile(entry.script);
        instructions.* = &lines;
    }
    break :blk out;
};

comptime {
    if (table.len != std.enums.values(Maneuver).len) @compileError("one entry per maneuver");
    for (table, 0..) |entry, index| {
        if (@intFromEnum(entry.maneuver) != index) @compileError("maneuvers out of place");
    }
}

test info {
    for (table) |entry| try std.testing.expectEqual(entry.maneuver, info(entry.maneuver).?.maneuver);
    try std.testing.expectEqual(null, info(@enumFromInt(table.len)));
    for (compiled, table) |instructions, entry| try std.testing.expectEqual(entry.script.len, instructions.len);
}
