//! Reads the Executor command catalogue, which `0x21 command` indexes, out of the payload.
//!
//! The catalogue is self-describing: each entry carries its implementation, its name, a label and
//! a type for each parameter, and a one-line description, all written by the developers. The
//! engine counts entries until one has no implementation (`FUN_00452A80`), and this reader applies
//! the same rule.

const std = @import("std");
const Io = std.Io;

const starlancer = @import("starlancer");
const pe = starlancer.pe;

/// Virtual address of the catalogue, which `FUN_0045CE30` installs as the command table.
pub const catalogue: u32 = 0x004F0F50;

pub const entry_size = 0x74;
pub const max_params = 8;

/// Offsets within an entry.
const layout = struct {
    const implementation = 0x00;
    const params = 0x04;
    const name = 0x08;
    /// Each parameter is a type, an unidentified word, and a label pointer.
    const first_param = 0x0C;
    const param_size = 12;
    const description = 0x6C;
    const flag = 0x70;
};

pub const Param = struct {
    kinds: u32,
    extra: u32,
    label: []const u8,
};

pub const Command = struct {
    implementation: u32,
    name: []const u8,
    params: []const Param,
    description: []const u8,
    flag: u32,
};

pub const Error = error{ OutOfImage, BadString, TooManyParams };

/// Reads virtual addresses out of a PE image.
const Reader = struct {
    image: pe.Image,
    bytes: []const u8,
    base: u32,

    fn slice(reader: Reader, va: u32, len: usize) Error![]const u8 {
        if (va < reader.base) return error.OutOfImage;
        const offset = reader.image.fileOffset(va - reader.base) orelse return error.OutOfImage;
        if (offset + len > reader.bytes.len) return error.OutOfImage;
        return reader.bytes[offset..][0..len];
    }

    fn word(reader: Reader, va: u32) Error!u32 {
        return std.mem.readInt(u32, (try reader.slice(va, 4))[0..4], .little);
    }

    /// A NUL-terminated string at `va`, or empty for a null pointer.
    fn string(reader: Reader, va: u32) Error![]const u8 {
        if (va == 0) return "";
        if (va < reader.base) return error.BadString;
        const offset = reader.image.fileOffset(va - reader.base) orelse return error.BadString;
        const rest = reader.bytes[offset..];
        const end = std.mem.indexOfScalar(u8, rest, 0) orelse return error.BadString;
        for (rest[0..end]) |c| if (c < 0x20 or c > 0x7E) return error.BadString;
        return rest[0..end];
    }
};

pub fn read(arena: std.mem.Allocator, image: pe.Image, bytes: []const u8) (Error || std.mem.Allocator.Error)![]const Command {
    const reader: Reader = .{ .image = image, .bytes = bytes, .base = image.optional_header.image_base };
    var commands: std.ArrayList(Command) = .empty;

    var at = catalogue;
    while (true) : (at += entry_size) {
        const implementation = try reader.word(at + layout.implementation);
        if (implementation == 0) break;

        const count = try reader.word(at + layout.params);
        if (count > max_params) return error.TooManyParams;
        const params = try arena.alloc(Param, count);
        for (params, 0..) |*param, i| {
            const field = at + layout.first_param + @as(u32, @intCast(i)) * layout.param_size;
            param.* = .{
                .kinds = try reader.word(field),
                .extra = try reader.word(field + 4),
                .label = try reader.string(try reader.word(field + 8)),
            };
        }
        try commands.append(arena, .{
            .implementation = implementation,
            .name = try reader.string(try reader.word(at + layout.name)),
            .params = params,
            .description = try reader.string(try reader.word(at + layout.description)),
            .flag = try reader.word(at + layout.flag),
        });
    }
    return commands.toOwnedSlice(arena);
}

pub fn emit(w: *Io.Writer, commands: []const Command) !void {
    try w.print(
        \\//! The Executor commands that `0x21 command` calls.
        \\//!
        \\//! Generated by `src/tools/vmgen` from the payload executable's command catalogue at
        \\//! 0x{X:0>8}, {d} entries. Names, labels and descriptions are the developers' own. Do not
        \\//! edit by hand; run `make vm-commands`.
        \\
        \\
        \\/// What a parameter accepts: a mask of the kinds of value it takes. The bit names are read off
        \\/// the labels of the parameters that set them.
        \\pub const Kinds = packed struct(u32) {{
        \\    _unknown_0: u7,
        \\    /// `0x80`: a count, an ID, a number of seconds.
        \\    number: bool,
        \\    /// `0x100`: the name of a speech or movie file.
        \\    file_name: bool,
        \\    /// `0x200`: text, or an animation name.
        \\    text: bool,
        \\    /// `0x400`: a ship.
        \\    ship: bool,
        \\    /// `0x800`: a flight group, or a patrol route.
        \\    flight_group: bool,
        \\    _unknown_12: u2,
        \\    /// `0x4000`: a function, meaning a part.
        \\    part: bool,
        \\    _unknown_15: u4,
        \\    /// `0x80000`: a named constant: a pilot, an AI mode, a text ID.
        \\    constant: bool,
        \\    _unknown_20: bool,
        \\    /// `0x200000`: a trigger condition.
        \\    condition: bool,
        \\    /// `0x400000`: a camera or flight curve.
        \\    curve: bool,
        \\    _unknown_23: u9,
        \\}};
        \\
        \\pub const Param = struct {{
        \\    kinds: Kinds,
        \\    /// **Unknown.** Zero for most parameters.
        \\    extra: u32,
        \\    label: []const u8,
        \\}};
        \\
        \\pub const Command = struct {{
        \\    name: []const u8,
        \\    params: []const Param,
        \\    description: []const u8,
        \\    /// **Unknown.** Set on seven commands.
        \\    flag: u32,
        \\    /// Address of the implementation in the payload executable.
        \\    implementation: u32,
        \\}};
        \\
        \\/// Every command, indexed by the operand of `0x21 command`.
        \\pub const table = [_]Command{{
        \\
    , .{ catalogue, commands.len });

    for (commands, 0..) |command, index| {
        try w.print("    // 0x{X:0>2}\n    .{{\n", .{index});
        try w.print("        .name = \"{f}\",\n", .{std.zig.fmtString(command.name)});
        if (command.params.len == 0) {
            try w.writeAll("        .params = &.{},\n");
        } else {
            try w.writeAll("        .params = &.{\n");
            for (command.params) |param| {
                try w.print(
                    "            .{{ .kinds = @bitCast(@as(u32, 0x{X:0>8})), .extra = 0x{X:0>8}, .label = \"{f}\" }},\n",
                    .{ param.kinds, param.extra, std.zig.fmtString(param.label) },
                );
            }
            try w.writeAll("        },\n");
        }
        try w.print("        .description = \"{f}\",\n", .{std.zig.fmtString(command.description)});
        try w.print("        .flag = {d},\n", .{command.flag});
        try w.print("        .implementation = 0x{X:0>8},\n    }},\n", .{command.implementation});
    }

    try w.writeAll(
        \\};
        \\
        \\/// Looks up the command `0x21 command` calls with `index`.
        \\pub fn find(index: u8) ?Command {
        \\    return if (index < table.len) table[index] else null;
        \\}
        \\
        \\test find {
        \\    const std = @import("std");
        \\    try std.testing.expect(find(0) != null);
        \\    try std.testing.expect(find(table.len) == null);
        \\    for (table) |command| try std.testing.expect(command.name.len != 0);
        \\}
        \\
    );
}
