//! vmgen: derives the mission script VM's tables from the game binary.
//!
//!     vmgen opcodes <LANCER.EXE> <disassembly.asm> <output.zig>
//!     vmgen commands <LANCER.EXE> <output.zig>
//!     vmgen names <output.tsv>
//!
//! `opcodes`: the VM dispatches on a byte through a table of handler addresses. Reading that table
//! gives the opcode set, and following each handler gives the size and shape of the instruction it
//! decodes. `disassembly.asm` is what `make ghidra-export` writes for the payload executable.
//!
//! `commands`: the Executor catalogue that `0x21 command` indexes, which needs only the binary.
//!
//! `names`: a table naming each opcode handler after its opcode, from the committed opcode table
//! and `dte.Opcode`, for `ghidra/scripts/ApplyNames.java`.
//!
//! Both come straight out of the binary, so the tables written are transcripts of the engine
//! rather than readings of the mission files.

const std = @import("std");
const Io = std.Io;

const starlancer = @import("starlancer");
const pe = starlancer.pe;

const commands = @import("commands.zig");
const eval = @import("eval.zig");
const x86 = @import("x86.zig");

/// Virtual address of the dispatch table, found from the `CALL dword ptr [...]` that the
/// interpreter's inner loop makes.
const dispatch_table: u32 = 0x004F6350;

/// Entries the table could hold. The real one is shorter; where it ends is worked out below.
const max_opcodes = 256;

const Handler = struct {
    opcode: u8,
    address: u32,
    shape: eval.Shape,
};

const usage =
    \\usage: vmgen opcodes <LANCER.EXE> <disassembly.asm> <output.zig>
    \\       vmgen commands <LANCER.EXE> <output.zig>
    \\       vmgen names <output.tsv>
    \\
;

const Mode = union(enum) {
    opcodes: struct { binary: []const u8, listing: []const u8, output: []const u8 },
    commands: struct { binary: []const u8, output: []const u8 },
    names: struct { output: []const u8 },

    fn parse(args: []const [:0]const u8) ?Mode {
        if (args.len == 0) return null;
        const tag = std.meta.stringToEnum(std.meta.Tag(Mode), args[0]) orelse return null;
        const rest = args[1..];
        return switch (tag) {
            .opcodes => if (rest.len == 3) .{ .opcodes = .{ .binary = rest[0], .listing = rest[1], .output = rest[2] } } else null,
            .commands => if (rest.len == 2) .{ .commands = .{ .binary = rest[0], .output = rest[1] } } else null,
            .names => if (rest.len == 1) .{ .names = .{ .output = rest[0] } } else null,
        };
    }
};

pub fn main(init: std.process.Init) !u8 {
    const arena = init.arena.allocator();
    const args = try init.minimal.args.toSlice(arena);
    const mode = Mode.parse(args[1..]) orelse {
        std.debug.print("{s}", .{usage});
        return 2;
    };
    return switch (mode) {
        .opcodes => |paths| opcodes(init, arena, paths.binary, paths.listing, paths.output),
        .commands => |paths| catalogue(init, arena, paths.binary, paths.output),
        .names => |paths| handlerNames(init, paths.output),
    };
}

/// Writes one row per opcode handler, named `vm_` and its opcode's name. An opcode sharing its
/// handler with another is a `_alt` alias, so the handler takes the other's name.
fn handlerNames(init: std.process.Init, output: []const u8) !u8 {
    const dte = starlancer.dte;
    const cwd: Io.Dir = .cwd();
    var buffer: [16 << 10]u8 = undefined;
    var out: Io.File.Writer = .init(try cwd.createFile(init.io, output, .{}), init.io, &buffer);
    defer out.file.close(init.io);
    const w = &out.interface;

    try w.writeAll("# Generated by vmgen names from src/formats/vm_opcodes.zig and dte.Opcode.\n");
    var written: usize = 0;
    for (dte.vm_opcodes.table, 0..) |info, index| {
        // Each handler once, under the first opcode that is not an alias.
        const name = dte.opcodeName(info.opcode) orelse continue;
        if (std.mem.endsWith(u8, name, "_alt")) continue;
        var first = true;
        for (dte.vm_opcodes.table[0..index]) |earlier| {
            if (earlier.handler != info.handler) continue;
            const earlier_name = dte.opcodeName(earlier.opcode) orelse continue;
            if (!std.mem.endsWith(u8, earlier_name, "_alt")) first = false;
        }
        if (!first) continue;

        try w.print("{x:0>8}\tfunction\tvm_{s}\topcode 0x{X:0>2}", .{ info.handler, name, info.opcode });
        for (dte.vm_opcodes.table) |other| {
            if (other.handler == info.handler and other.opcode != info.opcode) {
                try w.print(", also 0x{X:0>2}", .{other.opcode});
            }
        }
        try w.writeByte('\n');
        written += 1;
    }
    try w.flush();
    std.debug.print("{d} handler names -> {s}\n", .{ written, output });
    return 0;
}

fn catalogue(init: std.process.Init, arena: std.mem.Allocator, binary_path: []const u8, output: []const u8) !u8 {
    const cwd: Io.Dir = .cwd();
    const binary = try cwd.readFileAlloc(init.io, binary_path, arena, .limited(64 << 20));
    const image: pe.Image = try .parse(binary);
    const all = try commands.read(arena, image, binary);

    var buffer: [16 << 10]u8 = undefined;
    var out: Io.File.Writer = .init(try cwd.createFile(init.io, output, .{}), init.io, &buffer);
    defer out.file.close(init.io);
    try commands.emit(&out.interface, all);
    try out.interface.flush();

    std.debug.print("{d} commands -> {s}\n", .{ all.len, output });
    return 0;
}

fn opcodes(
    init: std.process.Init,
    arena: std.mem.Allocator,
    binary_path: []const u8,
    listing_path: []const u8,
    output: []const u8,
) !u8 {
    const cwd: Io.Dir = .cwd();
    const binary = try cwd.readFileAlloc(init.io, binary_path, arena, .limited(64 << 20));
    const listing = try cwd.readFileAlloc(init.io, listing_path, arena, .limited(256 << 20));

    const image: pe.Image = try .parse(binary);
    const base = image.optional_header.image_base;
    const text = image.sectionByName(".text") orelse {
        std.debug.print("{s}: no .text section\n", .{binary_path});
        return 1;
    };
    const text_start = base + text.virtual_address;
    const text_end = text_start + text.virtual_size;

    const table_offset = image.fileOffset(dispatch_table - base) orelse {
        std.debug.print("dispatch table at {x} is not in the image\n", .{dispatch_table});
        return 1;
    };

    const functions = try x86.parse(arena, listing);
    var by_address: std.AutoHashMapUnmanaged(u32, x86.Function) = .empty;
    for (functions) |function| try by_address.put(arena, function.address, function);

    // The table runs from its start to the first entry that is neither empty nor a code address.
    // Past that point the data is some other structure, which holds values that happen to look
    // like addresses.
    var handlers: std.ArrayList(Handler) = .empty;
    var length: usize = 0;
    for (0..max_opcodes) |opcode| {
        const entry = std.mem.readInt(u32, binary[table_offset + opcode * 4 ..][0..4], .little);
        if (entry == 0) continue;
        if (entry < text_start or entry >= text_end) break;
        length = opcode + 1;

        const handler = by_address.get(entry) orelse {
            std.debug.print("opcode {x:0>2}: no function at {x:0>8} in the listing\n", .{ opcode, entry });
            return 1;
        };
        const shape = eval.analyze(arena, handler) catch |err| {
            std.debug.print("opcode {x:0>2} ({s}): {t}\n", .{ opcode, handler.name, err });
            return 1;
        };
        try handlers.append(arena, .{ .opcode = @intCast(opcode), .address = entry, .shape = shape });
    }

    var buffer: [16 << 10]u8 = undefined;
    var out: Io.File.Writer = .init(try cwd.createFile(init.io, output, .{}), init.io, &buffer);
    defer out.file.close(init.io);
    try emit(&out.interface, handlers.items, length);
    try out.interface.flush();

    std.debug.print("{d} opcodes over a table of {d} entries -> {s}\n", .{
        handlers.items.len, length, output,
    });
    return 0;
}

fn emit(w: *Io.Writer, handlers: []const Handler, length: usize) !void {
    try w.print(
        \\//! The mission script VM's instruction set.
        \\//!
        \\//! Generated by `src/tools/vmgen` from the payload executable's dispatch table at
        \\//! 0x{[table]X:0>8}, which holds {[length]d} entries. Do not edit by hand; run `make vm-opcodes`.
        \\
        \\
        \\/// What an instruction does to the instruction pointer.
        \\pub const Form = enum {{
        \\    /// Execution continues at the instruction after the operands.
        \\    sequential,
        \\    /// The operand bytes hold a displacement, relative to their own position, to where
        \\    /// execution resumes. The instruction itself still ends after them.
        \\    branch,
        \\    /// The one operand byte is a total length, covering itself: `length - 1` bytes of
        \\    /// inline data follow it, and execution resumes after them.
        \\    inline_data,
        \\    /// Control passes somewhere a linear decoder cannot follow.
        \\    transfer,
        \\}};
        \\
        \\pub const Info = struct {{
        \\    opcode: u8,
        \\    /// Operand bytes between the opcode and the next instruction. For `inline_data` this
        \\    /// counts only the length byte.
        \\    operands: u8,
        \\    form: Form,
        \\    /// Whether execution can continue at the instruction after the operands. Where it
        \\    /// cannot, the bytes that follow are reached only by a branch, so a linear sweep
        \\    /// would decode whatever happens to sit there.
        \\    falls_through: bool,
        \\    /// Address of the handler in the payload executable.
        \\    handler: u32,
        \\}};
        \\
        \\/// Every opcode the VM implements, in order.
        \\pub const table = [_]Info{{
        \\
    , .{ .table = dispatch_table, .length = length });

    for (handlers) |handler| {
        try w.print(
            "    .{{ .opcode = 0x{X:0>2}, .operands = {d}, .form = .{t}, .falls_through = {}, .handler = 0x{X:0>8} }},\n",
            .{
                handler.opcode,              handler.shape.operands, handler.shape.form,
                handler.shape.falls_through, handler.address,
            },
        );
    }

    try w.writeAll(
        \\};
        \\
        \\/// Looks up `opcode`, or null when the VM has no handler for it.
        \\pub fn find(opcode: u8) ?Info {
        \\    // The table is sorted, and short enough that a scan beats anything cleverer.
        \\    for (table) |info| {
        \\        if (info.opcode == opcode) return info;
        \\        if (info.opcode > opcode) break;
        \\    }
        \\    return null;
        \\}
        \\
        \\test find {
        \\    const std = @import("std");
        \\    try std.testing.expect(find(table[0].opcode) != null);
        \\    try std.testing.expect(find(0x00) == null);
        \\    for (table[1..], table[0 .. table.len - 1]) |next, previous| {
        \\        try std.testing.expect(next.opcode > previous.opcode);
        \\    }
        \\}
        \\
    );
}

test Mode {
    const both = Mode.parse(&.{ "commands", "LANCER.EXE", "out.zig" }).?;
    try std.testing.expectEqualStrings("out.zig", both.commands.output);
    try std.testing.expectEqual(@as(?Mode, null), Mode.parse(&.{ "opcodes", "LANCER.EXE" }));
    try std.testing.expectEqual(@as(?Mode, null), Mode.parse(&.{"bogus"}));
}

test {
    std.testing.refAllDecls(@This());
    _ = commands;
    _ = eval;
    _ = x86;
}
