//! vmgen: derives the mission script VM's opcode table from the game binary.
//!
//! The VM dispatches on a byte through a table of handler addresses. Reading that table gives the
//! opcode set, and following each handler gives the size and shape of the instruction it decodes.
//! Both come straight out of the binary, so the table this writes is a transcript of the engine
//! rather than a reading of the mission files.
//!
//!     vmgen <LANCER.EXE> <disassembly.asm> <output.zig>
//!
//! `disassembly.asm` is what `make ghidra-export` writes for the payload executable.

const std = @import("std");
const Io = std.Io;

const starlancer = @import("starlancer");
const pe = starlancer.pe;

const eval = @import("eval.zig");
const x86 = @import("x86.zig");

/// Virtual address of the dispatch table, found from the `CALL dword ptr [...]` that the
/// interpreter's inner loop makes.
const dispatch_table: u32 = 0x004F6350;

/// Entries the table could hold. The real one is shorter; where it ends is worked out below.
const max_opcodes = 256;

const Handler = struct {
    opcode: u8,
    address: u32,
    shape: eval.Shape,
};

pub fn main(init: std.process.Init) !u8 {
    const arena = init.arena.allocator();
    const args = try init.minimal.args.toSlice(arena);
    if (args.len != 4) {
        std.debug.print("usage: vmgen <LANCER.EXE> <disassembly.asm> <output.zig>\n", .{});
        return 2;
    }

    const cwd: Io.Dir = .cwd();
    const binary = try cwd.readFileAlloc(init.io, args[1], arena, .limited(64 << 20));
    const listing = try cwd.readFileAlloc(init.io, args[2], arena, .limited(256 << 20));

    const image: pe.Image = try .parse(binary);
    const base = image.optional_header.image_base;
    const text = image.sectionByName(".text") orelse {
        std.debug.print("{s}: no .text section\n", .{args[1]});
        return 1;
    };
    const text_start = base + text.virtual_address;
    const text_end = text_start + text.virtual_size;

    const table_offset = image.fileOffset(dispatch_table - base) orelse {
        std.debug.print("dispatch table at {x} is not in the image\n", .{dispatch_table});
        return 1;
    };

    const functions = try x86.parse(arena, listing);
    var by_address: std.AutoHashMapUnmanaged(u32, x86.Function) = .empty;
    for (functions) |function| try by_address.put(arena, function.address, function);

    // The table runs from its start to the first entry that is neither empty nor a code address.
    // Past that point the data is some other structure, which holds values that happen to look
    // like addresses.
    var handlers: std.ArrayList(Handler) = .empty;
    var length: usize = 0;
    for (0..max_opcodes) |opcode| {
        const entry = std.mem.readInt(u32, binary[table_offset + opcode * 4 ..][0..4], .little);
        if (entry == 0) continue;
        if (entry < text_start or entry >= text_end) break;
        length = opcode + 1;

        const handler = by_address.get(entry) orelse {
            std.debug.print("opcode {x:0>2}: no function at {x:0>8} in the listing\n", .{ opcode, entry });
            return 1;
        };
        const shape = eval.analyze(arena, handler) catch |err| {
            std.debug.print("opcode {x:0>2} ({s}): {t}\n", .{ opcode, handler.name, err });
            return 1;
        };
        try handlers.append(arena, .{ .opcode = @intCast(opcode), .address = entry, .shape = shape });
    }

    var buffer: [16 << 10]u8 = undefined;
    var out: Io.File.Writer = .init(try cwd.createFile(init.io, args[3], .{}), init.io, &buffer);
    defer out.file.close(init.io);
    try emit(&out.interface, handlers.items, length);
    try out.interface.flush();

    std.debug.print("{d} opcodes over a table of {d} entries -> {s}\n", .{
        handlers.items.len, length, args[3],
    });
    return 0;
}

fn emit(w: *Io.Writer, handlers: []const Handler, length: usize) !void {
    try w.print(
        \\//! The mission script VM's instruction set.
        \\//!
        \\//! Generated by `src/tools/vmgen` from the payload executable's dispatch table at
        \\//! 0x{[table]X:0>8}, which holds {[length]d} entries. Do not edit by hand; run `make vm-opcodes`.
        \\
        \\
        \\/// What an instruction does to the instruction pointer.
        \\pub const Form = enum {{
        \\    /// Execution continues at the instruction after the operands.
        \\    sequential,
        \\    /// The operand bytes hold a displacement, relative to their own position, to where
        \\    /// execution resumes. The instruction itself still ends after them.
        \\    branch,
        \\    /// The one operand byte is a total length, covering itself: `length - 1` bytes of
        \\    /// inline data follow it, and execution resumes after them.
        \\    inline_data,
        \\    /// Control passes somewhere a linear decoder cannot follow.
        \\    transfer,
        \\}};
        \\
        \\pub const Info = struct {{
        \\    opcode: u8,
        \\    /// Operand bytes between the opcode and the next instruction. For `inline_data` this
        \\    /// counts only the length byte.
        \\    operands: u8,
        \\    form: Form,
        \\    /// Whether execution can continue at the instruction after the operands. Where it
        \\    /// cannot, the bytes that follow are reached only by a branch, so a linear sweep
        \\    /// would decode whatever happens to sit there.
        \\    falls_through: bool,
        \\    /// Address of the handler in the payload executable.
        \\    handler: u32,
        \\}};
        \\
        \\/// Every opcode the VM implements, in order.
        \\pub const table = [_]Info{{
        \\
    , .{ .table = dispatch_table, .length = length });

    for (handlers) |handler| {
        try w.print(
            "    .{{ .opcode = 0x{X:0>2}, .operands = {d}, .form = .{t}, .falls_through = {}, .handler = 0x{X:0>8} }},\n",
            .{
                handler.opcode,              handler.shape.operands, handler.shape.form,
                handler.shape.falls_through, handler.address,
            },
        );
    }

    try w.writeAll(
        \\};
        \\
        \\/// Looks up `opcode`, or null when the VM has no handler for it.
        \\pub fn find(opcode: u8) ?Info {
        \\    // The table is sorted, and short enough that a scan beats anything cleverer.
        \\    for (table) |info| {
        \\        if (info.opcode == opcode) return info;
        \\        if (info.opcode > opcode) break;
        \\    }
        \\    return null;
        \\}
        \\
        \\test find {
        \\    const std = @import("std");
        \\    try std.testing.expect(find(table[0].opcode) != null);
        \\    try std.testing.expect(find(0x00) == null);
        \\    for (table[1..], table[0 .. table.len - 1]) |next, previous| {
        \\        try std.testing.expect(next.opcode > previous.opcode);
        \\    }
        \\}
        \\
    );
}

test {
    std.testing.refAllDecls(@This());
    _ = eval;
    _ = x86;
}
