//! The player's actions, and the keys and joystick buttons the game binds them to at first.
//!
//! Generated by `src/tools/tablegen` from the payload executable's control bindings at
//! 0x004E2380, 74 actions. The names are the game's own. Do not edit by hand; run
//! `make control-tables`.

const std = @import("std");

/// The modifier held with a key; `docs/engine/controls.md` describes how each counts.
pub const Modifier = @import("../input.zig").ControlBinding.Modifier;

/// Every action, numbered as the game numbers them.
pub const Action = enum(u32) {
    cockpit_camera = 0,
    left_view_camera = 1,
    right_view_camera = 2,
    rear_view_camera = 3,
    flyby_camera = 4,
    target_camera = 5,
    external_camera = 6,
    missile_camera = 7,
    next_enemy_target = 8,
    previous_enemy_target = 9,
    next_friendly_target = 10,
    previous_friendly_target = 11,
    next_subtarget = 12,
    previous_subtarget = 13,
    target_under_reticule = 14,
    target_nearest_enemy = 15,
    target_nearest_friendly = 16,
    target_torpedo = 17,
    smart_target = 18,
    primary_target = 19,
    afterburners = 20,
    afterburner_toggle = 21,
    reverse_thrust = 22,
    jump_drive = 23,
    match_speed = 24,
    accelerate = 25,
    decelerate = 26,
    zero_throttle = 27,
    full_throttle = 28,
    roll_ship_clockwise = 29,
    roll_ship_anti_clockwise = 30,
    nose_up = 31,
    nose_down = 32,
    rotate_clockwise = 33,
    rotate_anti_clockwise = 34,
    strafe_left = 35,
    strafe_right = 36,
    joystick_roll = 37,
    fire_lasers = 38,
    full_guns = 39,
    gunnery_window = 40,
    gunnery_window_locked = 41,
    synchronise_guns = 42,
    toggle_blindfire = 43,
    launch_missile = 44,
    missile_window = 45,
    rotate_missiles_clockwise = 46,
    rotate_missiles_anticlockwise = 47,
    comms_window = 48,
    powerball_window = 49,
    powerball_window_locked = 50,
    full_power_to_gunnery = 51,
    full_power_to_engines = 52,
    full_power_to_shields = 53,
    equalize_power = 54,
    objectives_window = 55,
    wing_status_window = 56,
    wing_status_window_locked = 57,
    damage_window = 58,
    damage_window_locked = 59,
    radar_ranges = 60,
    shield_balancing = 61,
    countermeasures = 62,
    eject = 63,
    cloak_ship = 64,
    ecm = 65,
    spectral_shields = 66,
    attack_my_target = 67,
    back_off = 68,
    help_me = 69,
    permission_to_land = 70,
    display_kills = 71,
    send_comms_message = 72,
    key_config = 73,
};

pub const Binding = struct {
    /// The name the game shows.
    name: []const u8,
    /// A DirectInput scan code (`DIK_*`).
    key: u16,
    modifier: Modifier,
    /// A joystick button, or null for none.
    button: ?u8,
};

/// The bindings the game starts with, indexed by `Action`.
pub const defaults = [_]Binding{
    .{ .name = "COCKPIT CAMERA", .key = 0x02, .modifier = .none, .button = null },
    .{ .name = "LEFT VIEW CAMERA", .key = 0x03, .modifier = .none, .button = null },
    .{ .name = "RIGHT VIEW CAMERA", .key = 0x04, .modifier = .none, .button = null },
    .{ .name = "REAR VIEW CAMERA", .key = 0x05, .modifier = .none, .button = null },
    .{ .name = "FLYBY CAMERA", .key = 0x06, .modifier = .none, .button = null },
    .{ .name = "TARGET CAMERA", .key = 0x07, .modifier = .none, .button = null },
    .{ .name = "EXTERNAL CAMERA", .key = 0x08, .modifier = .none, .button = null },
    .{ .name = "MISSILE CAMERA", .key = 0x09, .modifier = .none, .button = null },
    .{ .name = "NEXT ENEMY TARGET", .key = 0x12, .modifier = .none, .button = null },
    .{ .name = "PREVIOUS ENEMY TARGET", .key = 0x12, .modifier = .shift, .button = null },
    .{ .name = "NEXT FRIENDLY TARGET", .key = 0x10, .modifier = .none, .button = 5 },
    .{ .name = "PREVIOUS FRIENDLY TARGET", .key = 0x10, .modifier = .shift, .button = null },
    .{ .name = "NEXT SUBTARGET", .key = 0x1F, .modifier = .none, .button = null },
    .{ .name = "PREVIOUS SUBTARGET", .key = 0x1F, .modifier = .shift, .button = null },
    .{ .name = "TARGET UNDER RETICULE", .key = 0x15, .modifier = .none, .button = null },
    .{ .name = "TARGET NEAREST ENEMY", .key = 0x13, .modifier = .none, .button = 3 },
    .{ .name = "TARGET NEAREST FRIENDLY", .key = 0x11, .modifier = .none, .button = null },
    .{ .name = "TARGET TORPEDO", .key = 0x14, .modifier = .none, .button = null },
    .{ .name = "SMART TARGET", .key = 0x12, .modifier = .control, .button = null },
    .{ .name = "PRIMARY TARGET", .key = 0x1E, .modifier = .none, .button = null },
    .{ .name = "AFTERBURNERS", .key = 0x0F, .modifier = .none, .button = 2 },
    .{ .name = "AFTERBURNER TOGGLE", .key = 0x29, .modifier = .none, .button = null },
    .{ .name = "REVERSE THRUST", .key = 0x0F, .modifier = .shift, .button = null },
    .{ .name = "JUMP DRIVE", .key = 0x24, .modifier = .none, .button = null },
    .{ .name = "MATCH SPEED", .key = 0x2C, .modifier = .none, .button = null },
    .{ .name = "ACCELERATE", .key = 0x0D, .modifier = .none, .button = null },
    .{ .name = "DECELERATE", .key = 0x0C, .modifier = .none, .button = null },
    .{ .name = "ZERO THROTTLE", .key = 0x0E, .modifier = .none, .button = null },
    .{ .name = "FULL THROTTLE", .key = 0x2B, .modifier = .none, .button = null },
    .{ .name = "ROLL SHIP CLOCKWISE", .key = 0xC9, .modifier = .none, .button = null },
    .{ .name = "ROLL SHIP ANTI-CLOCKWISE", .key = 0xC7, .modifier = .none, .button = null },
    .{ .name = "NOSE UP", .key = 0xD0, .modifier = .none, .button = null },
    .{ .name = "NOSE DOWN", .key = 0xC8, .modifier = .none, .button = null },
    .{ .name = "ROTATE CLOCKWISE", .key = 0xCB, .modifier = .none, .button = null },
    .{ .name = "ROTATE ANTI-CLOCKWISE", .key = 0xCD, .modifier = .none, .button = null },
    .{ .name = "STRAFE LEFT", .key = 0xCF, .modifier = .none, .button = 7 },
    .{ .name = "STRAFE RIGHT", .key = 0xD1, .modifier = .none, .button = 4 },
    .{ .name = "JOYSTICK ROLL", .key = 0xD2, .modifier = .none, .button = null },
    .{ .name = "FIRE LASERS", .key = 0x39, .modifier = .none, .button = 0 },
    .{ .name = "FULL GUNS", .key = 0x21, .modifier = .none, .button = null },
    .{ .name = "GUNNERY WINDOW", .key = 0x22, .modifier = .none, .button = null },
    .{ .name = "GUNNERY WINDOW LOCKED", .key = 0x22, .modifier = .shift, .button = null },
    .{ .name = "SYNCHRONISE GUNS", .key = 0x22, .modifier = .control, .button = null },
    .{ .name = "TOGGLE BLINDFIRE", .key = 0x21, .modifier = .shift, .button = null },
    .{ .name = "LAUNCH MISSILE", .key = 0x1C, .modifier = .none, .button = 1 },
    .{ .name = "MISSILE WINDOW", .key = 0x32, .modifier = .none, .button = null },
    .{ .name = "ROTATE MISSILES CLOCKWISE", .key = 0x34, .modifier = .none, .button = null },
    .{ .name = "ROTATE MISSILES ANTICLOCKWISE", .key = 0x33, .modifier = .none, .button = null },
    .{ .name = "COMMS WINDOW", .key = 0x2E, .modifier = .none, .button = null },
    .{ .name = "POWERBALL WINDOW", .key = 0x19, .modifier = .none, .button = null },
    .{ .name = "POWERBALL WINDOW LOCKED", .key = 0x19, .modifier = .shift, .button = null },
    .{ .name = "FULL POWER TO GUNNERY", .key = 0x16, .modifier = .none, .button = null },
    .{ .name = "FULL POWER TO ENGINES", .key = 0x17, .modifier = .none, .button = null },
    .{ .name = "FULL POWER TO SHIELDS", .key = 0x18, .modifier = .none, .button = null },
    .{ .name = "EQUALIZE POWER", .key = 0x1A, .modifier = .none, .button = null },
    .{ .name = "OBJECTIVES WINDOW", .key = 0x30, .modifier = .none, .button = null },
    .{ .name = "WING STATUS WINDOW", .key = 0x2D, .modifier = .none, .button = null },
    .{ .name = "WING STATUS WINDOW LOCKED", .key = 0x2D, .modifier = .shift, .button = null },
    .{ .name = "DAMAGE WINDOW", .key = 0x20, .modifier = .none, .button = null },
    .{ .name = "DAMAGE WINDOW LOCKED", .key = 0x20, .modifier = .shift, .button = null },
    .{ .name = "RADAR RANGES", .key = 0x2F, .modifier = .none, .button = null },
    .{ .name = "SHIELD BALANCING", .key = 0x31, .modifier = .none, .button = null },
    .{ .name = "COUNTERMEASURES", .key = 0x23, .modifier = .none, .button = null },
    .{ .name = "EJECT", .key = 0x58, .modifier = .none, .button = null },
    .{ .name = "CLOAK SHIP", .key = 0x25, .modifier = .none, .button = null },
    .{ .name = "ECM", .key = 0x26, .modifier = .none, .button = null },
    .{ .name = "SPECTRAL SHIELDS", .key = 0x27, .modifier = .none, .button = null },
    .{ .name = "ATTACK MY TARGET", .key = 0x3F, .modifier = .none, .button = null },
    .{ .name = "BACK OFF", .key = 0x40, .modifier = .none, .button = null },
    .{ .name = "HELP ME", .key = 0x41, .modifier = .none, .button = null },
    .{ .name = "PERMISSION TO LAND", .key = 0x42, .modifier = .none, .button = null },
    .{ .name = "DISPLAY KILLS", .key = 0x44, .modifier = .none, .button = null },
    .{ .name = "SEND COMMS MESSAGE", .key = 0x28, .modifier = .none, .button = null },
    .{ .name = "KEY CONFIG", .key = 0x3B, .modifier = .none, .button = null },
};

pub fn binding(action: Action) Binding {
    return defaults[@intFromEnum(action)];
}

comptime {
    if (defaults.len != std.enums.values(Action).len) @compileError("one binding per action");
}

test binding {
    for (std.enums.values(Action)) |action| {
        const name = binding(action).name;
        const tag = @tagName(action);
        try std.testing.expectEqual(name.len, tag.len);
        for (name, tag) |c, t| {
            try std.testing.expectEqual(if (c == ' ' or c == '-') '_' else std.ascii.toLower(c), t);
        }
    }
}
