//! The Executor commands that `0x21 command` calls.
//!
//! Generated by `src/tools/vmgen` from the payload executable's command catalogue at
//! 0x004F0F50, 95 entries. Names, labels and descriptions are the developers' own. Do not
//! edit by hand; run `make vm-commands`.

/// What a parameter accepts: a mask of the kinds of value it takes. The bit names are read off
/// the labels of the parameters that set them.
pub const Kinds = packed struct(u32) {
    _unknown_0: u7,
    /// `0x80`: a count, an ID, a number of seconds.
    number: bool,
    /// `0x100`: the name of a speech or movie file.
    file_name: bool,
    /// `0x200`: text, or an animation name.
    text: bool,
    /// `0x400`: a ship.
    ship: bool,
    /// `0x800`: a flight group, or a patrol route.
    flight_group: bool,
    _unknown_12: u2,
    /// `0x4000`: a function, meaning a part.
    part: bool,
    _unknown_15: u4,
    /// `0x80000`: a named constant: a pilot, an AI mode, a text ID.
    constant: bool,
    _unknown_20: bool,
    /// `0x200000`: a trigger condition.
    condition: bool,
    /// `0x400000`: a camera or flight curve.
    curve: bool,
    _unknown_23: u9,
};

pub const Param = struct {
    kinds: Kinds,
    /// **Unknown.** Zero for most parameters.
    extra: u32,
    label: []const u8,
};

pub const Command = struct {
    name: []const u8,
    params: []const Param,
    description: []const u8,
    /// **Unknown.** Set on seven commands.
    flag: u32,
    /// Address of the implementation in the payload executable.
    implementation: u32,
    /// The callback the implementation hands `for_each_ship` (`0x0045D460`), which runs it for
    /// each ship of the ship, flight group or squad the first argument names. Null for a
    /// command that does not.
    per_ship: ?u32,
};

/// Every command, indexed by the operand of `0x21 command`.
pub const table = [_]Command{
    // 0x00
    .{
        .name = "PrintShipName",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000D00)), .extra = 0x00000002, .label = "Test Param 1" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Test Param 2" },
        },
        .description = "Test Function",
        .flag = 0,
        .implementation = 0x00458AB0,
        .per_ship = null,
    },
    // 0x01
    .{
        .name = "CreateTimer",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Unique ID to identify timer" },
            .{ .kinds = @bitCast(@as(u32, 0x00004000)), .extra = 0x00000000, .label = "Function to execute when timer activates" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Number of seconds before timer activates" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Number of activations (0 == continuous)" },
        },
        .description = "Creates a timer to invoke a function",
        .flag = 0,
        .implementation = 0x0045D210,
        .per_ship = null,
    },
    // 0x02
    .{
        .name = "DestroyTimer",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Unique ID of timer to be destroyed" },
        },
        .description = "Destroys all timers associated with a function",
        .flag = 0,
        .implementation = 0x0045D290,
        .per_ship = null,
    },
    // 0x03
    .{
        .name = "CreateFlightGroup",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000800)), .extra = 0x00000000, .label = "Flight Group name to initialize" },
        },
        .description = "Initializes a flight group",
        .flag = 0,
        .implementation = 0x00457C40,
        .per_ship = null,
    },
    // 0x04
    .{
        .name = "DestroyFlightGroup",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000800)), .extra = 0x00000000, .label = "Flight Group name to destroy" },
        },
        .description = "Destroys a flight group",
        .flag = 0,
        .implementation = 0x00457FD0,
        .per_ship = null,
    },
    // 0x05
    .{
        .name = "Wait",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Number of Seconds to wait" },
        },
        .description = "Stop Executing for N Seconds",
        .flag = 1,
        .implementation = 0x0045D2E0,
        .per_ship = null,
    },
    // 0x06
    .{
        .name = "PlaySpeech",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000100)), .extra = 0x00000002, .label = "Name of speech file" },
        },
        .description = "Play a speech file",
        .flag = 0,
        .implementation = 0x00458090,
        .per_ship = null,
    },
    // 0x07
    .{
        .name = "WaitForSpeech",
        .params = &.{},
        .description = "Pause script until speech is complete",
        .flag = 1,
        .implementation = 0x00458100,
        .per_ship = null,
    },
    // 0x08
    .{
        .name = "PlayCommsMovie",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000100)), .extra = 0x00000004, .label = "Name of movie file" },
            .{ .kinds = @bitCast(@as(u32, 0x00000100)), .extra = 0x00000002, .label = "Name of speech file" },
            .{ .kinds = @bitCast(@as(u32, 0x00080000)), .extra = 0x00000002, .label = "GText thingy hangover err...." },
        },
        .description = "Play a movie in the comms window",
        .flag = 0,
        .implementation = 0x00458120,
        .per_ship = null,
    },
    // 0x09
    .{
        .name = "WaitForMovie",
        .params = &.{},
        .description = "Pause script until comms movie is complete",
        .flag = 1,
        .implementation = 0x00458180,
        .per_ship = null,
    },
    // 0x0A
    .{
        .name = "PrintDebugMessage",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000200)), .extra = 0x00000000, .label = "Text to print" },
        },
        .description = "Prints a debugging message on screen",
        .flag = 0,
        .implementation = 0x004581A0,
        .per_ship = null,
    },
    // 0x0B
    .{
        .name = "SetAI",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity to be controlled" },
            .{ .kinds = @bitCast(@as(u32, 0x00080000)), .extra = 0x00000000, .label = "AI Mode" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Initialize Immediately (T/F)" },
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x01000000, .label = "Entity to target (can be NULL)" },
        },
        .description = "Sets a Ship or Flight Group's AI pattern",
        .flag = 0,
        .implementation = 0x004581F0,
        .per_ship = 0x00458220,
    },
    // 0x0C
    .{
        .name = "ClearAI",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x02000000, .label = "Entity to be cleared" },
        },
        .description = "Resets all AI intructions for an entity",
        .flag = 0,
        .implementation = 0x004588C0,
        .per_ship = 0x004588E0,
    },
    // 0x0D
    .{
        .name = "SetPatrolRoute",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000C00)), .extra = 0x02000000, .label = "Entity to send to patrol route" },
            .{ .kinds = @bitCast(@as(u32, 0x00000800)), .extra = 0x02000000, .label = "Patrol route to follow" },
        },
        .description = "Sends a Ship to follow a patrol route",
        .flag = 0,
        .implementation = 0x00458860,
        .per_ship = 0x00458880,
    },
    // 0x0E
    .{
        .name = "SetPilot",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship to host pilot" },
            .{ .kinds = @bitCast(@as(u32, 0x00080000)), .extra = 0x00000003, .label = "Pilot to fly ship" },
        },
        .description = "Assigns a pilot to fly a ship",
        .flag = 0,
        .implementation = 0x00458830,
        .per_ship = null,
    },
    // 0x0F
    .{
        .name = "SetTriggerState",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x02000000, .label = "Entity owning trigger" },
            .{ .kinds = @bitCast(@as(u32, 0x00200000)), .extra = 0x00000000, .label = "Trigger type to enable/disable" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "TRUE for enable; FALSE for disable" },
        },
        .description = "Enables or disables the state of a trigger",
        .flag = 0,
        .implementation = 0x0045D300,
        .per_ship = null,
    },
    // 0x10
    .{
        .name = "StartDirectorCam",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00400400)), .extra = 0x00000000, .label = "Curve for camera to follow (or Ship for static cam)" },
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x01000000, .label = "Ship for camera to track (can be NULL)" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Duration of camera (seconds)" },
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x01000000, .label = "Tracks curve to this ship's speed (can be NULL)" },
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x01000000, .label = "Ships to disable for duration" },
        },
        .description = "Sets the camera to start following a predefined path",
        .flag = 0,
        .implementation = 0x004582E0,
        .per_ship = null,
    },
    // 0x11
    .{
        .name = "StartShipAnimation",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship to animate" },
            .{ .kinds = @bitCast(@as(u32, 0x00000200)), .extra = 0x00000000, .label = "Animation Name" },
        },
        .description = "Starts a specific animation for a ship",
        .flag = 0,
        .implementation = 0x00458720,
        .per_ship = null,
    },
    // 0x12
    .{
        .name = "ShipFollowCurve",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000C00)), .extra = 0x00000000, .label = "Entity to follow curve" },
            .{ .kinds = @bitCast(@as(u32, 0x00400000)), .extra = 0x00000000, .label = "The curve for the entity to follow" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Duration of movement (seconds)" },
        },
        .description = "Sets an ship/flight group to follow a predefined path",
        .flag = 0,
        .implementation = 0x004585D0,
        .per_ship = 0x004585F0,
    },
    // 0x13
    .{
        .name = "SetupLaunch",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity to be launched" },
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Ship to launch from" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Launch position" },
        },
        .description = "Sets up a ship ready to launch",
        .flag = 0,
        .implementation = 0x00458970,
        .per_ship = 0x004589A0,
    },
    // 0x14
    .{
        .name = "StartLaunch",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity to be launched" },
        },
        .description = "Launches a ship",
        .flag = 0,
        .implementation = 0x00458A40,
        .per_ship = 0x00458A60,
    },
    // 0x15
    .{
        .name = "DisplaySubTitle",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00080000)), .extra = 0x00000002, .label = "GText pilot define" },
        },
        .description = "Prints a subtitle so we can understand those foreign bods",
        .flag = 0,
        .implementation = 0x00458A80,
        .per_ship = null,
    },
    // 0x16
    .{
        .name = "ResetCodePriority",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity to have priorities reset" },
        },
        .description = "Clears/removes any priortiy order of the entity",
        .flag = 0,
        .implementation = 0x00458A90,
        .per_ship = 0x00458AB0,
    },
    // 0x17
    .{
        .name = "InterruptTriggerCode",
        .params = &.{},
        .description = "Stops script execution, will resume when trigger re-enabled",
        .flag = 0,
        .implementation = 0x0045D450,
        .per_ship = null,
    },
    // 0x18
    .{
        .name = "CommsFromShip",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship sending comm" },
            .{ .kinds = @bitCast(@as(u32, 0x00080000)), .extra = 0x00000004, .label = "Head movement" },
            .{ .kinds = @bitCast(@as(u32, 0x00000100)), .extra = 0x00000002, .label = "Name of speech file" },
        },
        .description = "Play a movie in the comms window",
        .flag = 0,
        .implementation = 0x00458AC0,
        .per_ship = null,
    },
    // 0x19
    .{
        .name = "CommsFromPilot",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00080000)), .extra = 0x00000003, .label = "Ship sending comm" },
            .{ .kinds = @bitCast(@as(u32, 0x00080000)), .extra = 0x00000004, .label = "Head movement" },
            .{ .kinds = @bitCast(@as(u32, 0x00000100)), .extra = 0x00000002, .label = "Name of speech file" },
        },
        .description = "Play a movie in the comms window",
        .flag = 0,
        .implementation = 0x00458B10,
        .per_ship = null,
    },
    // 0x1A
    .{
        .name = "SetInvulnerability",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Ship concerned" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Invulnerability (0 - non, 1 - player can hit, 2 - fully invulnerable, 3 - Eject before exploding)" },
        },
        .description = "Makes or stops a ship being invulnerable",
        .flag = 0,
        .implementation = 0x00458BC0,
        .per_ship = 0x00458BE0,
    },
    // 0x1B
    .{
        .name = "MovingShipFollowCurve",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000C00)), .extra = 0x02000000, .label = "Entity to follow curve" },
            .{ .kinds = @bitCast(@as(u32, 0x00400000)), .extra = 0x00000000, .label = "The curve for the entity to follow" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Duration of movement (seconds)" },
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Entity for curve to use as its start offset" },
        },
        .description = "Sets an ship/flight group to follow a predefined path",
        .flag = 0,
        .implementation = 0x004585A0,
        .per_ship = 0x004585C0,
    },
    // 0x1C
    .{
        .name = "DisableObject",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity concerned" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "True/False" },
        },
        .description = "Stops entities from being processed",
        .flag = 0,
        .implementation = 0x004583C0,
        .per_ship = 0x004583E0,
    },
    // 0x1D
    .{
        .name = "PositionRelative",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity to position" },
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship/Point to use as relative marker" },
        },
        .description = "Positions an entity relative to a ship/point's movement",
        .flag = 0,
        .implementation = 0x004584D0,
        .per_ship = 0x004584F0,
    },
    // 0x1E
    .{
        .name = "WhenPlayerLastJumped",
        .params = &.{},
        .description = "Returns the number of seconds ago when the player jumped",
        .flag = 0,
        .implementation = 0x00458580,
        .per_ship = null,
    },
    // 0x1F
    .{
        .name = "StartMissileCam",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship that fired missile" },
        },
        .description = "Starts director cam for a missile",
        .flag = 0,
        .implementation = 0x00458B60,
        .per_ship = null,
    },
    // 0x20
    .{
        .name = "StartChaseCam",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x01000000, .label = "Ship to follow" },
        },
        .description = "Starts chase cam",
        .flag = 0,
        .implementation = 0x00458B80,
        .per_ship = null,
    },
    // 0x21
    .{
        .name = "SetPlayerTarget",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Player Ship" },
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship to target" },
        },
        .description = "Sets player's target",
        .flag = 0,
        .implementation = 0x00458C80,
        .per_ship = null,
    },
    // 0x22
    .{
        .name = "SetTargetable",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "true - object targetable, false - not targetable" },
        },
        .description = "Sets an entity to be targetable or not",
        .flag = 0,
        .implementation = 0x00458D50,
        .per_ship = 0x00458D70,
    },
    // 0x23
    .{
        .name = "PlayMusic",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000100)), .extra = 0x00000009, .label = "Name of music file" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "True - Play Immediately, false - Fade old tune first" },
        },
        .description = "Play a Music Track",
        .flag = 0,
        .implementation = 0x00458DF0,
        .per_ship = null,
    },
    // 0x24
    .{
        .name = "StopDirectorCam",
        .params = &.{},
        .description = "Stops the Current Director Camera",
        .flag = 0,
        .implementation = 0x00458E30,
        .per_ship = null,
    },
    // 0x25
    .{
        .name = "SetActionCentre",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Object to action around" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Radius of sphere - 0 for default" },
        },
        .description = "Sets the sphere for the action to be contained in.",
        .flag = 0,
        .implementation = 0x00458E60,
        .per_ship = null,
    },
    // 0x26
    .{
        .name = "Dock",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship to dock" },
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Object ship is to dock to" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Docking port" },
        },
        .description = "Dock Ship.",
        .flag = 0,
        .implementation = 0x00458EB0,
        .per_ship = null,
    },
    // 0x27
    .{
        .name = "DisableTaunts",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "true - Disable bad guy taunts" },
        },
        .description = "Stops bad guys from taunting the player",
        .flag = 0,
        .implementation = 0x00458F40,
        .per_ship = null,
    },
    // 0x28
    .{
        .name = "Fly",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Ship" },
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x01000000, .label = "Point to fly to" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Speed (0 - Default)" },
        },
        .description = "Fly",
        .flag = 0,
        .implementation = 0x00458F50,
        .per_ship = 0x00458F70,
    },
    // 0x29
    .{
        .name = "CommsFromShipOnce",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship sending comm" },
            .{ .kinds = @bitCast(@as(u32, 0x00080000)), .extra = 0x00000004, .label = "Head movement" },
            .{ .kinds = @bitCast(@as(u32, 0x00000100)), .extra = 0x00000002, .label = "Name of speech file" },
        },
        .description = "Play a movie in the comms window (without looping)",
        .flag = 0,
        .implementation = 0x00458FD0,
        .per_ship = null,
    },
    // 0x2A
    .{
        .name = "CommsFromPilotOnce",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00080000)), .extra = 0x00000003, .label = "Ship sending comm" },
            .{ .kinds = @bitCast(@as(u32, 0x00080000)), .extra = 0x00000004, .label = "Head movement" },
            .{ .kinds = @bitCast(@as(u32, 0x00000100)), .extra = 0x00000002, .label = "Name of speech file" },
        },
        .description = "Play a movie in the comms window (without looping)",
        .flag = 0,
        .implementation = 0x00459020,
        .per_ship = null,
    },
    // 0x2B
    .{
        .name = "DisableLights",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "True or False" },
        },
        .description = "Disable Object lights",
        .flag = 0,
        .implementation = 0x00459070,
        .per_ship = 0x00459100,
    },
    // 0x2C
    .{
        .name = "SetEnvironmentFX",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00080000)), .extra = 0x00000001, .label = "Effect type to set" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "On(TRUE) or Off(FALSE)" },
        },
        .description = "Sets an environment effect",
        .flag = 0,
        .implementation = 0x00459170,
        .per_ship = null,
    },
    // 0x2D
    .{
        .name = "MultiPlayerSync",
        .params = &.{},
        .description = "Jay's shit",
        .flag = 0,
        .implementation = 0x004591E0,
        .per_ship = null,
    },
    // 0x2E
    .{
        .name = "DisableGenericComms",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "True - Disable all hard coded comms events" },
        },
        .description = "Stops hard coded comms events from triggering",
        .flag = 0,
        .implementation = 0x004591F0,
        .per_ship = null,
    },
    // 0x2F
    .{
        .name = "DisableGuns",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "TRUE - disable guns, FALSE enable guns" },
        },
        .description = "Disables guns",
        .flag = 0,
        .implementation = 0x00459200,
        .per_ship = 0x00459220,
    },
    // 0x30
    .{
        .name = "SetNavPoint",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity" },
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x01000000, .label = "Nav Point" },
        },
        .description = "Set Nav Point",
        .flag = 0,
        .implementation = 0x00459270,
        .per_ship = 0x00459290,
    },
    // 0x31
    .{
        .name = "SetEscortPoint",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity" },
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x01000000, .label = "Escort Point" },
        },
        .description = "Set Escort Point",
        .flag = 0,
        .implementation = 0x004592F0,
        .per_ship = 0x00459310,
    },
    // 0x32
    .{
        .name = "ResetAfterBurners",
        .params = &.{},
        .description = "Reset the player's afterburner fuel",
        .flag = 1,
        .implementation = 0x004594C0,
        .per_ship = null,
    },
    // 0x33
    .{
        .name = "DisableMissiles",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "TRUE - disable missiles, FALSE enable missiles" },
        },
        .description = "Disables missiles",
        .flag = 0,
        .implementation = 0x00459370,
        .per_ship = 0x00459390,
    },
    // 0x34
    .{
        .name = "DisableEngines",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "TRUE - disable engines, FALSE enable engines" },
        },
        .description = "Disables engines",
        .flag = 0,
        .implementation = 0x004593E0,
        .per_ship = 0x00459400,
    },
    // 0x35
    .{
        .name = "DisableEject",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "TRUE - disable eject, FALSE enable eject" },
        },
        .description = "Disables eject",
        .flag = 0,
        .implementation = 0x00459450,
        .per_ship = 0x00459470,
    },
    // 0x36
    .{
        .name = "SetHostile",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "true - entity(s) hostile, false - friendly" },
        },
        .description = "Sets entity(s) to be hostile or not",
        .flag = 0,
        .implementation = 0x004594F0,
        .per_ship = 0x00459510,
    },
    // 0x37
    .{
        .name = "ResetToSpawnPositions",
        .params = &.{},
        .description = "Resets the player to a random spawn location (deathmatch only)",
        .flag = 0,
        .implementation = 0x004591B0,
        .per_ship = null,
    },
    // 0x38
    .{
        .name = "UpdateEnvironmentFXState",
        .params = &.{},
        .description = "Updates state of environment FX instead of waiting for next jump",
        .flag = 0,
        .implementation = 0x004591A0,
        .per_ship = null,
    },
    // 0x39
    .{
        .name = "SetPrimaryTarget",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x01000000, .label = "Entity" },
        },
        .description = "Set Primary Target",
        .flag = 0,
        .implementation = 0x00459550,
        .per_ship = null,
    },
    // 0x3A
    .{
        .name = "WaitForJumpOrLaunch",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity" },
        },
        .description = "Wait for ships to finish jumping or launching",
        .flag = 0,
        .implementation = 0x004595A0,
        .per_ship = 0x004595E0,
    },
    // 0x3B
    .{
        .name = "DoNotDisturb",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "true - dont disturb, false - can disturb" },
        },
        .description = "Sets entity(s) so comms can/cant disturb them",
        .flag = 0,
        .implementation = 0x00459640,
        .per_ship = 0x00459660,
    },
    // 0x3C
    .{
        .name = "SetEnvironmentFXNebula",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Index of nebula material (0..6)" },
        },
        .description = "Sets the nebula material and lighting",
        .flag = 0,
        .implementation = 0x00459190,
        .per_ship = null,
    },
    // 0x3D
    .{
        .name = "StartShipAnimationReverse",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship to animate" },
            .{ .kinds = @bitCast(@as(u32, 0x00000200)), .extra = 0x00000000, .label = "Animation Name" },
        },
        .description = "Starts a specific animation for a ship in reverse",
        .flag = 0,
        .implementation = 0x004587D0,
        .per_ship = null,
    },
    // 0x3E
    .{
        .name = "SnapToPoint",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship to move" },
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Point to move to" },
        },
        .description = "Snaps a ship to a specific point",
        .flag = 0,
        .implementation = 0x004596A0,
        .per_ship = null,
    },
    // 0x3F
    .{
        .name = "PlayFostersLastStand",
        .params = &.{},
        .description = "Plays the Foster's Last Stand movie!",
        .flag = 1,
        .implementation = 0x00459740,
        .per_ship = null,
    },
    // 0x40
    .{
        .name = "OpenInstrument",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Instrument number to open" },
        },
        .description = "Opens up a window on the HUD",
        .flag = 0,
        .implementation = 0x0045D9D0,
        .per_ship = null,
    },
    // 0x41
    .{
        .name = "CloseInstrument",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Instrument number to close" },
        },
        .description = "Closes a window on the HUD",
        .flag = 0,
        .implementation = 0x0045DA30,
        .per_ship = null,
    },
    // 0x42
    .{
        .name = "DestroySubObject",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "SubObject to destroy" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "true - keep damaged model, false - no damaged model" },
        },
        .description = "Destroys Subobject",
        .flag = 0,
        .implementation = 0x00459750,
        .per_ship = null,
    },
    // 0x43
    .{
        .name = "SetObjective",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Objective number" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "State(0=Inactive, 1=Active, 2=Current)" },
        },
        .description = "Sets a Mission Objective's status",
        .flag = 0,
        .implementation = 0x00459870,
        .per_ship = null,
    },
    // 0x44
    .{
        .name = "SetRescueProbabilities",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Probability of Nanny Rescue    ( 1-100% )" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Probability of Antanov Capture ( 1-100% )" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Probability of being Destroyed ( 1-100% )" },
        },
        .description = "Sets an Ejected pod's chances of survival",
        .flag = 0,
        .implementation = 0x004598D0,
        .per_ship = null,
    },
    // 0x45
    .{
        .name = "IsShipThisPlayer",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship to test" },
        },
        .description = "Returns TRUE if ship is the players ship",
        .flag = 0,
        .implementation = 0x004598F0,
        .per_ship = null,
    },
    // 0x46
    .{
        .name = "SetFlybackMarker",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity concerned" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Range" },
        },
        .description = "Sets a Flyback marker on a ship or a group of ships after a set range",
        .flag = 0,
        .implementation = 0x00459910,
        .per_ship = 0x00459960,
    },
    // 0x47
    .{
        .name = "ResetFlybackMarker",
        .params = &.{},
        .description = "Resets all flyback markers",
        .flag = 0,
        .implementation = 0x004599E0,
        .per_ship = null,
    },
    // 0x48
    .{
        .name = "StopShipAnimation",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship to stop animation for" },
            .{ .kinds = @bitCast(@as(u32, 0x00000200)), .extra = 0x00000000, .label = "Animation Name" },
        },
        .description = "Stops a specific animation for a ship",
        .flag = 0,
        .implementation = 0x00458770,
        .per_ship = null,
    },
    // 0x49
    .{
        .name = "SetShipAvoidance",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity concerned" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "TRUE - Disable Avoidance code, FALSE - Enable avoidance code" },
        },
        .description = "Enables/Disables ship avoidance for the ship(s)",
        .flag = 0,
        .implementation = 0x00459A30,
        .per_ship = 0x00459A50,
    },
    // 0x4A
    .{
        .name = "MatchSpeed",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Entity concerned" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "TRUE - Enable Match Speed, FALSE - Disable Match Speed" },
        },
        .description = "Enables/Disables Match Speed with target",
        .flag = 0,
        .implementation = 0x00459A90,
        .per_ship = null,
    },
    // 0x4B
    .{
        .name = "MovingShipBackupCurve",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000C00)), .extra = 0x02000000, .label = "Entity to follow curve" },
            .{ .kinds = @bitCast(@as(u32, 0x00400000)), .extra = 0x00000000, .label = "The curve for the entity to follow" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Duration of movement (seconds)" },
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x01000000, .label = "Entity for curve to use as its start offset" },
        },
        .description = "Sets an ship/flight group to follow a predefined path",
        .flag = 0,
        .implementation = 0x00458670,
        .per_ship = 0x00458690,
    },
    // 0x4C
    .{
        .name = "WaitForKey",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Key number to wait for" },
        },
        .description = "Stops script until key pressed",
        .flag = 1,
        .implementation = 0x00459AE0,
        .per_ship = null,
    },
    // 0x4D
    .{
        .name = "TerminateMission",
        .params = &.{},
        .description = "End the mission, and drop to death sequence",
        .flag = 1,
        .implementation = 0x00459BB0,
        .per_ship = null,
    },
    // 0x4E
    .{
        .name = "TurretSetTarget",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100400)), .extra = 0x00000000, .label = "Turret" },
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Entity to target" },
        },
        .description = "Sets the target for a ships turret",
        .flag = 0,
        .implementation = 0x00459BD0,
        .per_ship = 0x00459BF0,
    },
    // 0x4F
    .{
        .name = "SetAnyTriggerState",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x02000000, .label = "Entity owning trigger" },
            .{ .kinds = @bitCast(@as(u32, 0x00200000)), .extra = 0x00000000, .label = "Trigger type to enable/disable" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "TRUE for enable; FALSE for disable" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Trigger Type Number(for triggers of same type - Count from 0)" },
        },
        .description = "Enables or disables the state of a trigger",
        .flag = 0,
        .implementation = 0x0045D3A0,
        .per_ship = null,
    },
    // 0x50
    .{
        .name = "WaitForDirectorCam",
        .params = &.{},
        .description = "Waits for director cam to finish",
        .flag = 0,
        .implementation = 0x00459C90,
        .per_ship = null,
    },
    // 0x51
    .{
        .name = "KillAllScriptExecutionExecptMe",
        .params = &.{},
        .description = "DANGER DANGER:Cancels ALL current script execution except the caller",
        .flag = 0,
        .implementation = 0x0045D990,
        .per_ship = null,
    },
    // 0x52
    .{
        .name = "StackDirectorCam",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00400400)), .extra = 0x00000000, .label = "Curve for camera to follow (or Ship for static cam)" },
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x01000000, .label = "Ship for camera to track (can be NULL)" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Duration of camera (seconds)" },
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x01000000, .label = "Tracks curve to this ship's speed (can be NULL)" },
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x01000000, .label = "Ships to disable for duration" },
        },
        .description = "Sets the camera to start following a predefined path",
        .flag = 0,
        .implementation = 0x00458300,
        .per_ship = null,
    },
    // 0x53
    .{
        .name = "Scanner",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x01000000, .label = "Object to scan for - NULL to disable" },
        },
        .description = "Sets the scanner off",
        .flag = 0,
        .implementation = 0x00459CB0,
        .per_ship = null,
    },
    // 0x54
    .{
        .name = "ReplaceSubObject",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "SubObject to replace" },
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Object to replace it with" },
        },
        .description = "Replaces subobject with another object",
        .flag = 0,
        .implementation = 0x00459CF0,
        .per_ship = null,
    },
    // 0x55
    .{
        .name = "Fire",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship to fire" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Duration" },
        },
        .description = "Fires ships guns",
        .flag = 0,
        .implementation = 0x00459DD0,
        .per_ship = null,
    },
    // 0x56
    .{
        .name = "MultiplayerScriptSync",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Sync number" },
        },
        .description = "Syncs scripts",
        .flag = 0,
        .implementation = 0x00459DF0,
        .per_ship = null,
    },
    // 0x57
    .{
        .name = "FriendlyFire",
        .params = &.{},
        .description = "Friendly Fire",
        .flag = 0,
        .implementation = 0x00459F30,
        .per_ship = null,
    },
    // 0x58
    .{
        .name = "Cloak",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00100C00)), .extra = 0x00000000, .label = "Entity to cloak" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "True - Cloak on, False - cloak off" },
        },
        .description = "Cloak",
        .flag = 0,
        .implementation = 0x00459F40,
        .per_ship = 0x00459F60,
    },
    // 0x59
    .{
        .name = "ReplenishWeapons",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Entity to cloak" },
        },
        .description = "Replenish Weapons",
        .flag = 0,
        .implementation = 0x00459FA0,
        .per_ship = null,
    },
    // 0x5A
    .{
        .name = "WillsBlag",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Entity to cloak" },
        },
        .description = "Blag blag blag blag blag",
        .flag = 0,
        .implementation = 0x0045A1C0,
        .per_ship = null,
    },
    // 0x5B
    .{
        .name = "ShowHudIcon",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "Icon" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "0 - off, 1 - on, 2 - flash" },
        },
        .description = "Show Hud Icon",
        .flag = 0,
        .implementation = 0x0045A1F0,
        .per_ship = null,
    },
    // 0x5C
    .{
        .name = "DisableListing",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "true - stop listing, false - enable listing" },
        },
        .description = "Disable Listing",
        .flag = 0,
        .implementation = 0x0045A210,
        .per_ship = null,
    },
    // 0x5D
    .{
        .name = "DisableObjectAtNextJump",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship" },
            .{ .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0x00000000, .label = "true - disable, false - enable" },
        },
        .description = "Disables/enables object (e.g. planet) when the next jump/warp is made",
        .flag = 0,
        .implementation = 0x0045A250,
        .per_ship = null,
    },
    // 0x5E
    .{
        .name = "DarrensNaughtyBlag",
        .params = &.{
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship" },
            .{ .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0x00000000, .label = "Ship" },
        },
        .description = "Darrens Naughty Blag",
        .flag = 0,
        .implementation = 0x0045A290,
        .per_ship = null,
    },
};

/// Looks up the command `0x21 command` calls with `index`.
pub fn find(index: u8) ?Command {
    return if (index < table.len) table[index] else null;
}

test find {
    const std = @import("std");
    try std.testing.expect(find(0) != null);
    try std.testing.expect(find(table.len) == null);
    for (table) |command| try std.testing.expect(command.name.len != 0);
}
