//! The trigger conditions: the kinds of object each applies to and the values its events carry.
//!
//! Generated by `src/tools/vmgen` from the payload executable's condition catalogue at
//! 0x004F6698, 35 entries, which `mission_script_start` installs. Names and labels are the
//! developers' own. Do not edit by hand; run `make vm-conditions`.

const dte = @import("dte.zig");
const Kinds = @import("vm_commands.zig").Kinds;

/// One value an event carries. A thread the event starts has them as its locals, and a
/// trigger's operands follow the same order.
pub const Value = struct {
    label: []const u8,
    kinds: Kinds,
    /// **Unknown.**
    extra: u8,
    /// Whether a trigger's operand for this value is checked against the event's.
    checked: bool,
};

/// Addresses, in the payload executable, of the handlers that can veto an event.
pub const Handlers = struct {
    begin: u32,
    add_member: u32,
    verdict: u32,
};

pub const Condition = struct {
    name: []const u8,
    /// The kinds of object whose triggers can have the condition.
    subjects: dte.Object.KindSet,
    values: []const Value,
    /// Where the matcher keeps each object's last event of this condition, for
    /// `push_event_value`.
    slot: ?u8,
    /// The repeat mode whose triggers fire even when a handler vetoes the event.
    veto_exempt: ?dte.Trigger.Repeat,
    handlers: ?Handlers,
    /// **Unknown.**
    _unknown_04: u16,
};

/// Every condition, indexed by a trigger's condition byte.
pub const table = [_]Condition{
    // 0x00
    .{
        .name = "ShotAt",
        .subjects = .{ .ship = true, .flight_group = true, .squad = true, ._unused = 0 },
        .values = &.{
            .{ .label = "Attacker", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
            .{ .label = "Shield Damage", .kinds = @bitCast(@as(u32, 0x00001000)), .extra = 0xFF, .checked = false },
            .{ .label = "Hull Damage", .kinds = @bitCast(@as(u32, 0x00001000)), .extra = 0xFF, .checked = false },
            .{ .label = "Victim", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
            .{ .label = "Weapon Fired", .kinds = @bitCast(@as(u32, 0x00080000)), .extra = 0x09, .checked = true },
        },
        .slot = 0,
        .veto_exempt = null,
        .handlers = .{ .begin = 0x00452BB0, .add_member = 0x00452BD0, .verdict = 0x00452C00 },
        ._unknown_04 = 0x0000,
    },
    // 0x01
    .{
        .name = "Destroyed",
        .subjects = .{ .ship = true, .flight_group = true, .squad = true, ._unused = 0 },
        .values = &.{
            .{ .label = "Killer", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
            .{ .label = "Victim", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
        },
        .slot = 1,
        .veto_exempt = .always,
        .handlers = .{ .begin = 0x00452C40, .add_member = 0x00452C50, .verdict = 0x00452CA0 },
        ._unknown_04 = 0x0000,
    },
    // 0x02
    .{
        .name = "Launched",
        .subjects = .{ .ship = true, .flight_group = true, .squad = true, ._unused = 0 },
        .values = &.{
            .{ .label = "LaunchedShip", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
        },
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x03
    .{
        .name = "CameraReached",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{},
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x04
    .{
        .name = "ShipReached",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{
            .{ .label = "ReachedShip", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
        },
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x05
    .{
        .name = "CloseProximity",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{
            .{ .label = "ApproachingShip", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
            .{ .label = "Proximity", .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0xFF, .checked = false },
        },
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x06
    .{
        .name = "Proximity",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{
            .{ .label = "ApproachingShip", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
            .{ .label = "Proximity", .kinds = @bitCast(@as(u32, 0x00000080)), .extra = 0xFF, .checked = false },
        },
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x07
    .{
        .name = "ObjectScooped",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{
            .{ .label = "ObjectScooped", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
        },
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x08
    .{
        .name = "PlayerReadyToJump",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{},
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x09
    .{
        .name = "JumpedIn",
        .subjects = .{ .ship = true, .flight_group = true, .squad = true, ._unused = 0 },
        .values = &.{
            .{ .label = "JumpedInShip", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
        },
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x0A
    .{
        .name = "FixedGateJumpedIn",
        .subjects = .{ .ship = true, .flight_group = true, .squad = true, ._unused = 0 },
        .values = &.{
            .{ .label = "ShipJumpedIn", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
        },
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x0B
    .{
        .name = "PlayerReadyToWarp",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{},
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x0C
    .{
        .name = "JumpedThroughHoop",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{},
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x0D
    .{
        .name = "PlayerWantsBackup",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{},
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x0E
    .{
        .name = "RipperGrabbedObject",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{
            .{ .label = "ObjectGrabbed", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
        },
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x0F
    .{
        .name = "RipperDroppedObject",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{
            .{ .label = "ObjectDropped", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
        },
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x10
    .{
        .name = "Cloaked",
        .subjects = .{ .ship = true, .flight_group = true, .squad = true, ._unused = 0 },
        .values = &.{
            .{ .label = "CloakingShip", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
        },
        .slot = null,
        .veto_exempt = .always,
        .handlers = .{ .begin = 0x00452C40, .add_member = 0x0045D800, .verdict = 0x00452CA0 },
        ._unknown_04 = 0x0000,
    },
    // 0x11
    .{
        .name = "Decloaked",
        .subjects = .{ .ship = true, .flight_group = true, .squad = true, ._unused = 0 },
        .values = &.{
            .{ .label = "CloakingShip", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
        },
        .slot = null,
        .veto_exempt = .always,
        .handlers = .{ .begin = 0x00452C40, .add_member = 0x0045D800, .verdict = 0x00452CA0 },
        ._unknown_04 = 0x0000,
    },
    // 0x12
    .{
        .name = "Targetted",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{
            .{ .label = "Aggressor", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
        },
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x13
    .{
        .name = "Player_L1_DoubleTap",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{},
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x14
    .{
        .name = "Player_L2_DoubleTap",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{},
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x15
    .{
        .name = "Player_R1_DoubleTap",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{},
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x16
    .{
        .name = "Player_R2_DoubleTap",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{},
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x17
    .{
        .name = "Player_L1_L2_R1_R2 Pressed",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{},
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x18
    .{
        .name = "Player_L1_R1 Pressed",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{},
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x19
    .{
        .name = "Game Timer Expired",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{},
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x1A
    .{
        .name = "Tractor Beam Locked",
        .subjects = .{ .ship = true, .flight_group = true, .squad = true, ._unused = 0 },
        .values = &.{
            .{ .label = "TractoredShip", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
            .{ .label = "TractoringShip", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
        },
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x1B
    .{
        .name = "Tractor Beam Broken",
        .subjects = .{ .ship = true, .flight_group = true, .squad = true, ._unused = 0 },
        .values = &.{
            .{ .label = "TractoredShip", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
            .{ .label = "TractoringShip", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
        },
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x1C
    .{
        .name = "Inside Object",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{},
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x1D
    .{
        .name = "Outside Object",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{},
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x1E
    .{
        .name = "Docked",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{},
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x1F
    .{
        .name = "UnDocked",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{},
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x20
    .{
        .name = "I'm Being Chased",
        .subjects = .{ .ship = true, .flight_group = true, .squad = true, ._unused = 0 },
        .values = &.{
            .{ .label = "ChasedShip", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
            .{ .label = "Chaser", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
        },
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x21
    .{
        .name = "Player_CallReinforcements",
        .subjects = .{ .ship = true, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{
            .{ .label = "PlayerTargetted", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
        },
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0000,
    },
    // 0x22
    .{
        .name = "ExplosionShip",
        .subjects = .{ .ship = false, .flight_group = false, .squad = false, ._unused = 0 },
        .values = &.{
            .{ .label = "ExplosionShip", .kinds = @bitCast(@as(u32, 0x00000400)), .extra = 0xFF, .checked = true },
        },
        .slot = null,
        .veto_exempt = null,
        .handlers = null,
        ._unknown_04 = 0x0400,
    },
};

/// Looks up the condition a trigger's condition byte names.
pub fn find(condition: u8) ?Condition {
    return if (condition < table.len) table[condition] else null;
}

test find {
    const std = @import("std");
    try std.testing.expect(find(0) != null);
    try std.testing.expect(find(table.len) == null);
    for (table) |condition| try std.testing.expect(condition.name.len != 0);
}
