//! The orders objects follow, numbered as the game numbers them: order `n` is record `n % 100`
//! of group `n / 100` of the order table. `docs/engine/orders.md` describes how objects follow
//! them.
//!
//! Generated by `src/tools/tablegen` from the payload executable's order table at 0x004E06E0,
//! 70 orders in 3 groups. Names are the developers' own. Do not edit by hand; run
//! `make order-tables`.

const std = @import("std");

pub const Flags = @import("../ai.zig").Record.Flags;

/// Every order in the table, by number.
pub const Order = enum(i16) {
    do_nothing = 0,
    fly_aimlessly = 1,
    launch_missile = 2,
    unnamed_3 = 3,
    warp_in = 4,
    warp_out = 5,
    fly = 6,
    run_away = 7,
    land = 8,
    escort = 9,
    find_new_target = 10,
    explode = 11,
    ripper_grabs_target_object = 12,
    object_attach = 13,
    formation_regroup = 14,
    patrol_route = 15,
    toggle_cloak = 16,
    ship_follow_curve = 17,
    slow_rotate = 18,
    jump_in = 19,
    jump_out = 20,
    find_scoop_up = 21,
    random_spin_slow = 22,
    random_spin_medium = 23,
    random_spin_fast = 24,
    fixed_gate_jump_in = 25,
    fixed_gate_jump_out = 26,
    formation = 27,
    fixed_gate_open = 28,
    fixed_gate_close = 29,
    eject = 30,
    fixed_gate_collapse = 31,
    match_speed = 32,
    dark_reign_shoot = 33,
    move_to_spawn_pos = 34,
    turns_object_lights_on = 35,
    make_boridin_section_break_away = 36,
    rotate_boridin_breakaway_warp_projector = 37,
    start_warp_projection_from_boridin = 38,
    make_ripper_drop_what_its_carrying = 39,
    jump_in_40 = 40,
    jump_out_41 = 41,
    turns_object_lights_off = 42,
    huuuuuuuge_explosion = 43,
    immediately_set_ship_to_zero_velocity_and_rotation = 44,
    fly_ship_backwards = 45,
    player_control = 100,
    multiplayer_control = 101,
    avoid_target = 102,
    torpedo = 103,
    launch = 104,
    fight = 105,
    eject_106 = 106,
    scoop_up = 107,
    eject_spin = 108,
    dock = 109,
    dark_reign_shoot_110 = 110,
    ripper_end_drop_object = 111,
    ripper_attach_cargo_pod_to_mammoth = 112,
    eject_fighter_attack = 113,
    disrupted = 114,
    make_capship_list_left = 115,
    make_capship_list_right = 116,
    friendly_fire = 117,
    eject_player = 118,
    ship_follow_curve_backwards = 119,
    mill = 120,
    deathmatch_respawn_effect = 121,
    deathmatch_dark_reign_target = 122,
    unnamed_200 = 200,
    _,
};

pub const Info = struct {
    order: Order,
    /// The developers' name, which may be empty.
    name: []const u8,
    flags: Flags,
    priority: i32,
    /// Addresses in the payload executable of its routines, or null where it has none.
    init: ?u32,
    update: ?u32,
    exit: ?u32,
};

/// A group of the table: the records of the orders numbered from `first`.
pub const Group = struct {
    first: i16,
    /// Where its records are in the payload executable.
    address: u32,
    len: u8,
};

pub const groups = [_]Group{
    .{ .first = 0, .address = 0x004E0050, .len = 46 },
    .{ .first = 100, .address = 0x004E04A0, .len = 23 },
    .{ .first = 200, .address = 0x004E06C8, .len = 1 },
};

/// Every order, by number.
pub const table = [_]Info{
    .{ .order = .do_nothing, .name = "Do Nothing", .flags = @bitCast(@as(u32, 0x00000040)), .priority = 0, .init = null, .update = 0x0040A880, .exit = null },
    .{ .order = .fly_aimlessly, .name = "Fly Aimlessly", .flags = @bitCast(@as(u32, 0x000004C0)), .priority = 0, .init = 0x0040A8C0, .update = 0x0040A980, .exit = null },
    .{ .order = .launch_missile, .name = "Launch Missile", .flags = @bitCast(@as(u32, 0x00000022)), .priority = 0, .init = null, .update = 0x0040B940, .exit = null },
    .{ .order = .unnamed_3, .name = "", .flags = @bitCast(@as(u32, 0x00000022)), .priority = 0, .init = null, .update = 0x0040B990, .exit = null },
    .{ .order = .warp_in, .name = "Warp In", .flags = @bitCast(@as(u32, 0x00000003)), .priority = 1, .init = 0x0041E5C0, .update = 0x0041F260, .exit = null },
    .{ .order = .warp_out, .name = "Warp Out", .flags = @bitCast(@as(u32, 0x00000003)), .priority = 1, .init = 0x0041E550, .update = 0x0041E710, .exit = null },
    .{ .order = .fly, .name = "Fly", .flags = @bitCast(@as(u32, 0x000004C2)), .priority = 0, .init = 0x0040AC00, .update = 0x0040AC20, .exit = null },
    .{ .order = .run_away, .name = "Run Away", .flags = @bitCast(@as(u32, 0x000004C0)), .priority = 0, .init = null, .update = 0x0040ADE0, .exit = null },
    .{ .order = .land, .name = "Land", .flags = @bitCast(@as(u32, 0x00000003)), .priority = 1, .init = 0x0040EAC0, .update = 0x0040EB40, .exit = null },
    .{ .order = .escort, .name = "Escort", .flags = @bitCast(@as(u32, 0x0000048E)), .priority = 0, .init = 0x0040AA80, .update = 0x0040AAD0, .exit = null },
    .{ .order = .find_new_target, .name = "Find New Target", .flags = @bitCast(@as(u32, 0x0000000E)), .priority = 0, .init = null, .update = 0x0040B040, .exit = null },
    .{ .order = .explode, .name = "Explode", .flags = @bitCast(@as(u32, 0x00000003)), .priority = 99, .init = 0x00408610, .update = 0x004086A0, .exit = null },
    .{ .order = .ripper_grabs_target_object, .name = "Ripper grabs target object", .flags = @bitCast(@as(u32, 0x00000482)), .priority = 0, .init = 0x0040FD10, .update = 0x0040FF80, .exit = 0x00410B50 },
    .{ .order = .object_attach, .name = "Object Attach", .flags = @bitCast(@as(u32, 0x00000002)), .priority = 0, .init = 0x0040B4A0, .update = 0x0040B4F0, .exit = null },
    .{ .order = .formation_regroup, .name = "Formation Regroup", .flags = @bitCast(@as(u32, 0x00000010)), .priority = 0, .init = 0x00403C40, .update = 0x00403D00, .exit = null },
    .{ .order = .patrol_route, .name = "Patrol Route", .flags = @bitCast(@as(u32, 0x00000014)), .priority = 0, .init = 0x004038E0, .update = 0x00403940, .exit = null },
    .{ .order = .toggle_cloak, .name = "Toggle Cloak", .flags = @bitCast(@as(u32, 0x00000020)), .priority = 0, .init = null, .update = 0x0040B640, .exit = null },
    .{ .order = .ship_follow_curve, .name = "Ship Follow Curve", .flags = @bitCast(@as(u32, 0x00000412)), .priority = 0, .init = 0x00403340, .update = 0x004033A0, .exit = 0x00403550 },
    .{ .order = .slow_rotate, .name = "Slow Rotate", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = null, .update = 0x0040B660, .exit = null },
    .{ .order = .jump_in, .name = "Jump In", .flags = @bitCast(@as(u32, 0x00000003)), .priority = 1, .init = 0x00416540, .update = 0x00416570, .exit = null },
    .{ .order = .jump_out, .name = "Jump Out", .flags = @bitCast(@as(u32, 0x00000003)), .priority = 1, .init = 0x00416D50, .update = 0x00416E00, .exit = null },
    .{ .order = .find_scoop_up, .name = "Find Scoop Up", .flags = @bitCast(@as(u32, 0x00000482)), .priority = 0, .init = 0x0040B1C0, .update = 0x0040B1E0, .exit = null },
    .{ .order = .random_spin_slow, .name = "Random Spin Slow", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x0040B6A0, .update = 0x004983A0, .exit = null },
    .{ .order = .random_spin_medium, .name = "Random Spin Medium", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x0040B730, .update = 0x004983A0, .exit = null },
    .{ .order = .random_spin_fast, .name = "Random Spin Fast", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x0040B7C0, .update = 0x004983A0, .exit = null },
    .{ .order = .fixed_gate_jump_in, .name = "Fixed Gate Jump In", .flags = @bitCast(@as(u32, 0x00000003)), .priority = 1, .init = 0x00420B80, .update = 0x00420FD0, .exit = null },
    .{ .order = .fixed_gate_jump_out, .name = "Fixed Gate Jump Out", .flags = @bitCast(@as(u32, 0x00000003)), .priority = 1, .init = 0x00420DD0, .update = 0x00421510, .exit = null },
    .{ .order = .formation, .name = "Formation", .flags = @bitCast(@as(u32, 0x000004CE)), .priority = 0, .init = 0x0040B850, .update = 0x0040B8A0, .exit = null },
    .{ .order = .fixed_gate_open, .name = "Fixed Gate Open", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x004218A0, .update = 0x00421940, .exit = null },
    .{ .order = .fixed_gate_close, .name = "Fixed Gate Close", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x00421920, .update = 0x00421A00, .exit = null },
    .{ .order = .eject, .name = "Eject", .flags = @bitCast(@as(u32, 0x00000001)), .priority = 98, .init = 0x00415BD0, .update = 0x00415C50, .exit = null },
    .{ .order = .fixed_gate_collapse, .name = "Fixed Gate Collapse", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x00421AC0, .update = 0x00421B80, .exit = null },
    .{ .order = .match_speed, .name = "Match Speed", .flags = @bitCast(@as(u32, 0x00000002)), .priority = 0, .init = null, .update = 0x0040B9E0, .exit = null },
    .{ .order = .dark_reign_shoot, .name = "Dark Reign shoot", .flags = @bitCast(@as(u32, 0x0000040E)), .priority = 0, .init = null, .update = 0x0040BAD0, .exit = null },
    .{ .order = .move_to_spawn_pos, .name = "Move to spawn pos", .flags = @bitCast(@as(u32, 0x00000403)), .priority = 0, .init = null, .update = 0x004AF590, .exit = null },
    .{ .order = .turns_object_lights_on, .name = "Turns object lights on", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x0040BBD0, .update = 0x0040BC20, .exit = null },
    .{ .order = .make_boridin_section_break_away, .name = "Make Boridin section break away", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x0040BF60, .update = 0x004983A0, .exit = null },
    .{ .order = .rotate_boridin_breakaway_warp_projector, .name = "Rotate Boridin breakaway warp projector", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x0040C100, .update = 0x004983A0, .exit = null },
    .{ .order = .start_warp_projection_from_boridin, .name = "Start warp projection from Boridin", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x004230A0, .update = 0x00423230, .exit = null },
    .{ .order = .make_ripper_drop_what_its_carrying, .name = "Make ripper drop what it's carrying", .flags = @bitCast(@as(u32, 0x00000482)), .priority = 0, .init = 0x00410B90, .update = 0x00410C00, .exit = null },
    .{ .order = .jump_in_40, .name = "Jump In", .flags = @bitCast(@as(u32, 0x00000003)), .priority = 1, .init = 0x00416540, .update = 0x00416570, .exit = null },
    .{ .order = .jump_out_41, .name = "Jump Out", .flags = @bitCast(@as(u32, 0x00000003)), .priority = 1, .init = 0x00416D50, .update = 0x00416E00, .exit = null },
    .{ .order = .turns_object_lights_off, .name = "Turns object lights off", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x004983A0, .update = 0x0040BE90, .exit = null },
    .{ .order = .huuuuuuuge_explosion, .name = "Huuuuuuuge explosion", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x004983A0, .update = 0x004086C0, .exit = null },
    .{ .order = .immediately_set_ship_to_zero_velocity_and_rotation, .name = "Immediately set ship to zero velocity and rotation", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x004983A0, .update = 0x0040C4D0, .exit = null },
    .{ .order = .fly_ship_backwards, .name = "Fly ship backwards", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = null, .update = 0x0040C4E0, .exit = null },
    .{ .order = .player_control, .name = "Player Control", .flags = @bitCast(@as(u32, 0x00000400)), .priority = 0, .init = null, .update = 0x00413410, .exit = null },
    .{ .order = .multiplayer_control, .name = "Multiplayer Control", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = null, .update = 0x00414F70, .exit = null },
    .{ .order = .avoid_target, .name = "Avoid Target", .flags = @bitCast(@as(u32, 0x00000480)), .priority = 0, .init = 0x0040B310, .update = 0x0040B330, .exit = null },
    .{ .order = .torpedo, .name = "Torpedo", .flags = @bitCast(@as(u32, 0x00000400)), .priority = 0, .init = 0x00496F70, .update = 0x00496F90, .exit = null },
    .{ .order = .launch, .name = "Launch", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 1, .init = 0x00418EB0, .update = 0x004191C0, .exit = null },
    .{ .order = .fight, .name = "Fight", .flags = @bitCast(@as(u32, 0x000004C0)), .priority = 0, .init = 0x0040A4D0, .update = 0x0040A5E0, .exit = null },
    .{ .order = .eject_106, .name = "Eject", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 98, .init = 0x00416080, .update = 0x004160A0, .exit = null },
    .{ .order = .scoop_up, .name = "Scoop Up", .flags = @bitCast(@as(u32, 0x00000480)), .priority = 0, .init = 0x0041BBF0, .update = 0x0041BCC0, .exit = 0x0041BC70 },
    .{ .order = .eject_spin, .name = "Eject Spin", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 98, .init = 0x004160D0, .update = 0x00416190, .exit = null },
    .{ .order = .dock, .name = "Dock", .flags = @bitCast(@as(u32, 0x00000480)), .priority = 1, .init = 0x00406B80, .update = 0x00406C30, .exit = 0x00406C50 },
    .{ .order = .dark_reign_shoot_110, .name = "Dark reign shoot", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x0040D020, .update = 0x0040D210, .exit = 0x0040D1E0 },
    .{ .order = .ripper_end_drop_object, .name = "Ripper end drop object", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x00410E60, .update = 0x00410E90, .exit = null },
    .{ .order = .ripper_attach_cargo_pod_to_mammoth, .name = "Ripper attach cargo pod to Mammoth", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x00411200, .update = 0x00411420, .exit = null },
    .{ .order = .eject_fighter_attack, .name = "Eject fighter attack", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = null, .update = 0x004161F0, .exit = null },
    .{ .order = .disrupted, .name = "Disrupted", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x0040C140, .update = 0x0040C370, .exit = 0x0040C390 },
    .{ .order = .make_capship_list_left, .name = "Make capship list left", .flags = @bitCast(@as(u32, 0x00000400)), .priority = 0, .init = 0x0040B1C0, .update = 0x0040C4B0, .exit = null },
    .{ .order = .make_capship_list_right, .name = "Make capship list right", .flags = @bitCast(@as(u32, 0x00000400)), .priority = 0, .init = 0x0040B1C0, .update = 0x0040C4C0, .exit = null },
    .{ .order = .friendly_fire, .name = "Friendly Fire", .flags = @bitCast(@as(u32, 0x00000400)), .priority = 1, .init = 0x00474E60, .update = 0x00474F20, .exit = null },
    .{ .order = .eject_player, .name = "Eject Player", .flags = @bitCast(@as(u32, 0x00000400)), .priority = 97, .init = 0x00416310, .update = 0x00416450, .exit = null },
    .{ .order = .ship_follow_curve_backwards, .name = "Ship Follow Curve Backwards", .flags = @bitCast(@as(u32, 0x00000400)), .priority = 0, .init = 0x004036C0, .update = 0x00403720, .exit = 0x004038C0 },
    .{ .order = .mill, .name = "Mill", .flags = @bitCast(@as(u32, 0x00000480)), .priority = 0, .init = 0x0040A6F0, .update = 0x0040A750, .exit = null },
    .{ .order = .deathmatch_respawn_effect, .name = "Deathmatch Respawn Effect", .flags = @bitCast(@as(u32, 0x00000400)), .priority = 0, .init = 0x004B0DB0, .update = 0x004B0ED0, .exit = 0x004B0E80 },
    .{ .order = .deathmatch_dark_reign_target, .name = "Deathmatch Dark Reign target", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = 0x004983A0, .update = 0x004983A0, .exit = null },
    .{ .order = .unnamed_200, .name = "", .flags = @bitCast(@as(u32, 0x00000000)), .priority = 0, .init = null, .update = null, .exit = null },
};

/// The order numbered `order`, or null for a number the table does not hold.
pub fn info(order: Order) ?Info {
    for (table) |entry| {
        if (entry.order == order) return entry;
    }
    return null;
}

comptime {
    // The table holds each named order once, and the groups tile it in order.
    if (table.len != std.enums.values(Order).len) @compileError("one entry per order");
    var next: usize = 0;
    for (groups) |group| {
        for (table[next..][0..group.len], 0..) |entry, i| {
            if (@intFromEnum(entry.order) - group.first != i) @compileError("orders out of place");
        }
        next += group.len;
    }
    if (next != table.len) @compileError("groups do not cover the table");
}

test info {
    for (table) |entry| try std.testing.expectEqual(entry.order, info(entry.order).?.order);
    try std.testing.expectEqual(null, info(@enumFromInt(-1)));
}
