//! Reads the words of `ship_combat_stats` that the payload holds in its data rather than reading
//! them from `shipstats.bin`: for each ship type, whether its objects can be targeted, the string
//! that names it, its class, its side and the form of the target display that shows it.
//!
//! The table is 256 records, each a `create.ShipCombat`. `stats_load_ships` fills a record's
//! figures from the file, the gun code fills in its gun groups at run time, and the rest stays as
//! the executable has it.

const std = @import("std");
const Io = std.Io;

const openreliant = @import("openreliant");
const create = openreliant.engine.game.create;
const gameobj = openreliant.engine.game.gameobj;
const ShipCombat = create.ShipCombat;

const image = @import("image.zig");
const testing = @import("testing.zig");

/// `ship_combat_stats`.
pub const table: u32 = 0x004FC670;

pub const Static = struct {
    targetable: bool,
    name: u16,
    class: ShipCombat.Class,
    side: gameobj.Side(i16),
    display: ShipCombat.TargetDisplay,
};

pub const Error = image.Error || error{ NotZero, NotFlag };

pub fn read(arena: std.mem.Allocator, reader: image.Reader) (Error || std.mem.Allocator.Error)![]const Static {
    const bytes = try reader.slice(table, create.ship_type_count * @sizeOf(ShipCombat));
    const types = try arena.alloc(Static, create.ship_type_count);
    for (types, std.mem.bytesAsSlice(ShipCombat, bytes)) |*ship_type, record| ship_type.* = try parse(record);
    return types;
}

/// The executable's own words of one record. The gun groups must be empty, as the gun code
/// fills them in at run time, and the targeting word and the display either 0 or 1, or the table
/// is not what this reader knows.
fn parse(record: ShipCombat) Error!Static {
    if (record.gun_groups != 0 or record._unknown_1e != 0 or record.gun_group_table != .null) return error.NotZero;
    if (record.targeting._unknown_1 != 0 or @intFromEnum(record.display) > 1) return error.NotFlag;
    return .{
        .targetable = record.targeting.targetable,
        .name = record.name,
        .class = record.class,
        .side = record.side,
        .display = record.display,
    };
}

/// Writes `combat.zig`.
pub fn emit(w: *Io.Writer, types: []const Static) Io.Writer.Error!void {
    try w.print(
        \\//! The words of `ship_combat_stats` that the executable holds rather than `shipstats.bin`:
        \\//! for each ship type, whether its objects can be targeted, the string that names it, its
        \\//! class, its side and the form of the target display that shows it.
        \\//!
        \\//! Generated by `src/tools/tablegen` from the payload executable's `ship_combat_stats` at
        \\//! 0x{X:0>8}. Do not edit by hand; run `make combat-tables`.
        \\
        \\const create = @import("../create.zig");
        \\const gameobj = @import("../gameobj.zig");
        \\
        \\/// What a ship type's record holds besides its figures from `shipstats.bin`.
        \\pub const Static = struct {{
        \\    /// Whether its objects can be picked as targets (`ShipCombat.Targeting`).
        \\    targetable: bool,
        \\    /// The language string that names it.
        \\    name: u16,
        \\    class: create.ShipCombat.Class,
        \\    /// The side its objects start on.
        \\    side: gameobj.Side(i16),
        \\    display: create.ShipCombat.TargetDisplay,
        \\}};
        \\
        \\/// Every ship type's, by its number.
        \\pub const ship_types = [{d}]Static{{
        \\
    , .{ table, types.len });
    for (types, 0..) |ship_type, index| {
        try w.print("    // 0x{X:0>2}\n    .{{ .targetable = {}, .name = {d}, .class = ", .{ index, ship_type.targetable, ship_type.name });
        try enumValue(w, ship_type.class);
        try w.writeAll(", .side = ");
        try enumValue(w, ship_type.side);
        try w.writeAll(", .display = ");
        try enumValue(w, ship_type.display);
        try w.writeAll(" },\n");
    }
    try w.writeAll(
        \\};
        \\
    );
}

/// A value of a non-exhaustive enum as Zig: its name, or the number where it has none.
fn enumValue(w: *Io.Writer, value: anytype) Io.Writer.Error!void {
    if (std.enums.tagName(@TypeOf(value), value)) |name| {
        try w.print(".{s}", .{name});
    } else {
        try w.print("@enumFromInt({d})", .{@intFromEnum(value)});
    }
}

test parse {
    // The Sabre: targetable, named by string 11, a Coalition fighter.
    var record = std.mem.zeroes(ShipCombat);
    record.targeting.targetable = true;
    record.name = 11;
    record.class = .fighter;
    record.side = .hostile;
    const sabre = try parse(record);
    try std.testing.expect(sabre.targetable);
    try std.testing.expectEqual(11, sabre.name);
    try std.testing.expectEqual(.fighter, sabre.class);
    try std.testing.expectEqual(.hostile, sabre.side);

    // What the gun code fills in at run time must not be set yet, and the flags must be flags.
    record.gun_groups = 1;
    try std.testing.expectError(error.NotZero, parse(record));
    record.gun_groups = 0;
    record.display = @enumFromInt(2);
    try std.testing.expectError(error.NotFlag, parse(record));
}

test read {
    const allocator = std.testing.allocator;
    var arena_state: std.heap.ArenaAllocator = .init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const records = try allocator.alloc(ShipCombat, create.ship_type_count);
    defer allocator.free(records);
    @memset(records, std.mem.zeroes(ShipCombat));
    // The Reliant, type 12: a capital ship of the player's side; and a class the reader doesn't
    // know.
    records[12].targeting.targetable = true;
    records[12].name = 644;
    records[12].class = .capital;
    records[12].display = .large;
    records[13].class = @enumFromInt(99);
    const region: testing.Region = .{ .va = table, .bytes = std.mem.sliceAsBytes(records) };

    const payload = try testing.reader(allocator, &.{region});
    defer testing.freeReader(allocator, payload);
    const types = try read(arena, payload);
    try std.testing.expectEqual(create.ship_type_count, types.len);
    try std.testing.expectEqual(.capital, types[12].class);
    try std.testing.expectEqual(.friendly, types[12].side);
    try std.testing.expectEqual(644, types[12].name);
    try std.testing.expectEqual(.large, types[12].display);
    try std.testing.expect(!types[0].targetable);

    var out: Io.Writer.Allocating = .init(allocator);
    defer out.deinit();
    try emit(&out.writer, types);
    try testing.expectZig(out.written());
    try std.testing.expect(std.mem.indexOf(u8, out.written(), ".class = @enumFromInt(99)") != null);
}
