//! Reads the trigger condition catalogue out of the payload.
//!
//! `mission_script_start` installs the catalogue with two instructions, one storing its address and
//! one its length, and this reader takes both from those instructions. Each descriptor names its
//! condition, the kinds of object the condition applies to and the values its events carry;
//! `src/lancer/vm.zig` gives the layout.

const std = @import("std");
const Io = std.Io;

const openreliant = @import("openreliant");
const Repeat = openreliant.dte.Trigger.Repeat;

const image = @import("image.zig");
const testing = @import("testing.zig");

/// Where `mission_script_start` installs the catalogue: `MOV dword ptr [condition_table], imm32`,
/// then `MOV word ptr [condition_count], imm16`.
pub const install: u32 = 0x0045CBC4;
const condition_table: u32 = 0x0052952C;
const condition_count: u32 = 0x00525F8C;

pub const descriptor_size = 0x1C;
pub const value_size = 0x0C;

/// The values an event can carry: the five locals of a thread, and a trigger's five operands.
pub const max_values = 5;

/// Offsets within a descriptor.
const layout = struct {
    const name = 0x00;
    const unknown_04 = 0x04;
    const subjects = 0x06;
    const values = 0x08;
    const slot = 0x0C;
    const veto_exempt = 0x0D;
    const handlers = 0x10;
};

pub const Value = struct {
    label: []const u8,
    kinds: u32,
    extra: u8,
    checked: bool,
};

pub const Handlers = struct {
    begin: u32,
    add_member: u32,
    verdict: u32,
};

pub const Condition = struct {
    name: []const u8,
    unknown_04: u16,
    subjects: u16,
    values: []const Value,
    slot: u8,
    veto_exempt: u8,
    handlers: ?Handlers,
};

pub const Catalogue = struct {
    address: u32,
    conditions: []const Condition,
};

pub const Error = image.Error || error{ NotTheInstall, TooManyValues, PartialHandlers, BadFlag };

pub fn read(arena: std.mem.Allocator, reader: image.Reader) (Error || std.mem.Allocator.Error)!Catalogue {
    const store = try reader.slice(install, 10);
    if (!std.mem.eql(u8, store[0..2], &.{ 0xC7, 0x05 }) or
        std.mem.readInt(u32, store[2..6], .little) != condition_table)
    {
        return error.NotTheInstall;
    }
    const address = std.mem.readInt(u32, store[6..10], .little);
    const count_store = try reader.slice(install + 10, 9);
    if (!std.mem.eql(u8, count_store[0..3], &.{ 0x66, 0xC7, 0x05 }) or
        std.mem.readInt(u32, count_store[3..7], .little) != condition_count)
    {
        return error.NotTheInstall;
    }
    const count = std.mem.readInt(u16, count_store[7..9], .little);

    const conditions = try arena.alloc(Condition, count);
    for (conditions, 0..) |*condition, index| {
        const at = address + @as(u32, @intCast(index)) * descriptor_size;
        var values: std.ArrayList(Value) = .empty;
        var list = try reader.word(at + layout.values);
        while (list != 0) : (list += value_size) {
            const label = try reader.word(list);
            if (label == 0) break;
            if (values.items.len == max_values) return error.TooManyValues;
            const checked = try reader.int(u8, list + 9);
            if (checked > 1) return error.BadFlag;
            try values.append(arena, .{
                .label = try reader.string(label),
                .kinds = try reader.word(list + 4),
                .extra = try reader.int(u8, list + 8),
                .checked = checked == 1,
            });
        }

        const handlers: Handlers = .{
            .begin = try reader.word(at + layout.handlers),
            .add_member = try reader.word(at + layout.handlers + 4),
            .verdict = try reader.word(at + layout.handlers + 8),
        };
        const any = handlers.begin != 0 or handlers.add_member != 0 or handlers.verdict != 0;
        const all = handlers.begin != 0 and handlers.add_member != 0 and handlers.verdict != 0;
        if (any and !all) return error.PartialHandlers;

        condition.* = .{
            .name = try reader.string(try reader.word(at + layout.name)),
            .unknown_04 = try reader.int(u16, at + layout.unknown_04),
            .subjects = try reader.int(u16, at + layout.subjects),
            .values = try values.toOwnedSlice(arena),
            .slot = try reader.int(u8, at + layout.slot),
            .veto_exempt = try reader.int(u8, at + layout.veto_exempt),
            .handlers = if (all) handlers else null,
        };
    }
    return .{ .address = address, .conditions = conditions };
}

/// Writes `vm/conditions.zig`.
pub fn emit(w: *Io.Writer, catalogue: Catalogue) !void {
    try w.print(
        \\//! The trigger conditions: the kinds of object each applies to and the values its events carry.
        \\//!
        \\//! Generated by `src/tools/tablegen` from the payload executable's condition catalogue at
        \\//! 0x{X:0>8}, {d} entries, which `mission_script_start` installs. Names and labels are the
        \\//! developers' own. Do not edit by hand; run `make vm-conditions`.
        \\
        \\const dte = @import("../../formats/dte.zig");
        \\const Kinds = @import("../game/executor/commands.zig").Kinds;
        \\
        \\/// One value an event carries. A thread the event starts has them as its locals, and a
        \\/// trigger's operands follow the same order.
        \\pub const Value = struct {{
        \\    label: []const u8,
        \\    kinds: Kinds,
        \\    /// **Unknown.**
        \\    extra: u8,
        \\    /// Whether a trigger's operand for this value is checked against the event's.
        \\    checked: bool,
        \\}};
        \\
        \\/// Addresses, in the payload executable, of the handlers that can veto an event.
        \\pub const Handlers = struct {{
        \\    begin: u32,
        \\    add_member: u32,
        \\    verdict: u32,
        \\}};
        \\
        \\pub const Condition = struct {{
        \\    name: []const u8,
        \\    /// The kinds of object whose triggers can have the condition.
        \\    subjects: dte.Object.KindSet,
        \\    values: []const Value,
        \\    /// Where the matcher keeps each object's last event of this condition, for
        \\    /// `push_event_value`.
        \\    slot: ?u8,
        \\    /// The repeat mode whose triggers fire even when a handler vetoes the event.
        \\    veto_exempt: ?dte.Trigger.Repeat,
        \\    handlers: ?Handlers,
        \\    /// **Unknown.**
        \\    _unknown_04: u16,
        \\}};
        \\
        \\/// Every condition, indexed by a trigger's condition byte.
        \\pub const table = [_]Condition{{
        \\
    , .{ catalogue.address, catalogue.conditions.len });

    for (catalogue.conditions, 0..) |condition, index| {
        try w.print("    // 0x{X:0>2}\n    .{{\n", .{index});
        try w.print("        .name = \"{f}\",\n", .{std.zig.fmtString(condition.name)});
        // A bit for each object kind: ship, flight group, squad.
        const subjects = condition.subjects;
        try w.print("        .subjects = .{{ .ship = {}, .flight_group = {}, .squad = {}, ._unused = {d} }},\n", .{
            subjects & 1 != 0, subjects & 2 != 0, subjects & 4 != 0, subjects >> 3,
        });
        if (condition.values.len == 0) {
            try w.writeAll("        .values = &.{},\n");
        } else {
            try w.writeAll("        .values = &.{\n");
            for (condition.values) |value| {
                try w.print(
                    "            .{{ .label = \"{f}\", .kinds = @bitCast(@as(u32, 0x{X:0>8})), .extra = 0x{X:0>2}, .checked = {} }},\n",
                    .{ std.zig.fmtString(value.label), value.kinds, value.extra, value.checked },
                );
            }
            try w.writeAll("        },\n");
        }
        if (condition.slot == 0xFF) {
            try w.writeAll("        .slot = null,\n");
        } else {
            try w.print("        .slot = {d},\n", .{condition.slot});
        }
        if (condition.veto_exempt == 0xFF) {
            try w.writeAll("        .veto_exempt = null,\n");
        } else if (std.enums.tagName(Repeat, @enumFromInt(condition.veto_exempt))) |name| {
            try w.print("        .veto_exempt = .{s},\n", .{name});
        } else {
            try w.print("        .veto_exempt = @enumFromInt({d}),\n", .{condition.veto_exempt});
        }
        if (condition.handlers) |handlers| {
            try w.print(
                "        .handlers = .{{ .begin = 0x{X:0>8}, .add_member = 0x{X:0>8}, .verdict = 0x{X:0>8} }},\n",
                .{ handlers.begin, handlers.add_member, handlers.verdict },
            );
        } else {
            try w.writeAll("        .handlers = null,\n");
        }
        try w.print("        ._unknown_04 = 0x{X:0>4},\n    }},\n", .{condition.unknown_04});
    }

    try w.writeAll(
        \\};
        \\
        \\/// Looks up the condition a trigger's condition byte names.
        \\pub fn find(condition: u8) ?Condition {
        \\    return if (condition < table.len) table[condition] else null;
        \\}
        \\
        \\test find {
        \\    const std = @import("std");
        \\    try std.testing.expect(find(0) != null);
        \\    try std.testing.expect(find(table.len) == null);
        \\    for (table) |condition| try std.testing.expect(condition.name.len != 0);
        \\}
        \\
    );
}

/// A synthetic payload: the two instructions that install the catalogue, and the catalogue with its
/// value lists and strings.
const TestPayload = struct {
    code: [0x40]u8 = @splat(0x90),
    data: [0x400]u8 = @splat(0),

    const code_va = install & ~@as(u32, 0xF);
    const table_va = 0x004F2000;
    const lists = table_va + 0x100;
    const strings = table_va + 0x200;

    fn text(payload: *TestPayload) testing.Region {
        return .{ .va = code_va, .bytes = &payload.code };
    }

    fn table(payload: *TestPayload) testing.Region {
        return .{ .va = table_va, .bytes = &payload.data };
    }

    fn installCatalogue(payload: *TestPayload, count: u16) void {
        const region = payload.text();
        region.put(install, &.{ 0xC7, 0x05 });
        region.putWord(install + 2, condition_table);
        region.putWord(install + 6, table_va);
        region.put(install + 10, &.{ 0x66, 0xC7, 0x05 });
        region.putWord(install + 13, condition_count);
        region.putHalf(install + 17, count);
    }

    /// Descriptor `index`, named `name`, with no values, slot or handlers.
    fn descriptor(payload: *TestPayload, index: u32, name: []const u8) u32 {
        const at = table_va + index * descriptor_size;
        const region = payload.table();
        const name_at = strings + index * 0x20;
        region.putString(name_at, name);
        region.putWord(at + layout.name, name_at);
        region.put(at + layout.slot, &.{ 0xFF, 0xFF });
        return at;
    }

    /// A value list at `list`, ending with an entry whose label is null.
    fn values(payload: *TestPayload, list: u32, labels: []const []const u8, checked: u8) void {
        const region = payload.table();
        for (labels, 0..) |label, i| {
            const at = list + @as(u32, @intCast(i)) * value_size;
            const label_at = strings + 0x100 + @as(u32, @intCast(i)) * 0x10;
            region.putString(label_at, label);
            region.putWord(at, label_at);
            region.putWord(at + 4, 0x400);
            region.put(at + 8, &.{ 0x02, checked });
        }
    }

    fn catalogue(payload: *TestPayload, arena: std.mem.Allocator) !Catalogue {
        return read(arena, try testing.reader(arena, &.{ payload.text(), payload.table() }));
    }
};

test read {
    var arena: std.heap.ArenaAllocator = .init(std.testing.allocator);
    defer arena.deinit();
    var payload: TestPayload = .{};
    payload.installCatalogue(2);
    const first = payload.descriptor(0, "ShipDestroyed");
    const region = payload.table();
    region.putHalf(first + layout.unknown_04, 0x1234);
    region.putHalf(first + layout.subjects, 0b011);
    region.putWord(first + layout.values, TestPayload.lists);
    payload.values(TestPayload.lists, &.{ "Ship", "Killer" }, 1);
    region.put(first + layout.slot, &.{ 3, 0xFF });
    for (0..3) |i| region.putWord(first + layout.handlers + @as(u32, @intCast(i)) * 4, 0x0045E000 + @as(u32, @intCast(i)));
    _ = payload.descriptor(1, "MissionStart");

    const read_catalogue = try payload.catalogue(arena.allocator());
    try std.testing.expectEqual(TestPayload.table_va, read_catalogue.address);
    try std.testing.expectEqual(2, read_catalogue.conditions.len);

    const destroyed = read_catalogue.conditions[0];
    try std.testing.expectEqualStrings("ShipDestroyed", destroyed.name);
    try std.testing.expectEqual(0x1234, destroyed.unknown_04);
    try std.testing.expectEqual(0b011, destroyed.subjects);
    try std.testing.expectEqual(2, destroyed.values.len);
    try std.testing.expectEqualStrings("Killer", destroyed.values[1].label);
    try std.testing.expectEqual(0x400, destroyed.values[1].kinds);
    try std.testing.expectEqual(2, destroyed.values[1].extra);
    try std.testing.expect(destroyed.values[1].checked);
    try std.testing.expectEqual(3, destroyed.slot);
    try std.testing.expectEqual(0x0045E002, destroyed.handlers.?.verdict);

    const start = read_catalogue.conditions[1];
    try std.testing.expectEqualStrings("MissionStart", start.name);
    try std.testing.expectEqual(0, start.values.len);
    try std.testing.expectEqual(null, start.handlers);
}

test "read wants the install instructions" {
    var arena: std.heap.ArenaAllocator = .init(std.testing.allocator);
    defer arena.deinit();
    var payload: TestPayload = .{};
    try std.testing.expectError(error.NotTheInstall, payload.catalogue(arena.allocator()));
}

test "handlers come in threes" {
    var arena: std.heap.ArenaAllocator = .init(std.testing.allocator);
    defer arena.deinit();
    var payload: TestPayload = .{};
    payload.installCatalogue(1);
    const at = payload.descriptor(0, "ShipDestroyed");
    payload.table().putWord(at + layout.handlers, 0x0045E000);
    try std.testing.expectError(error.PartialHandlers, payload.catalogue(arena.allocator()));
}

test "a value is checked or not" {
    var arena: std.heap.ArenaAllocator = .init(std.testing.allocator);
    defer arena.deinit();
    var payload: TestPayload = .{};
    payload.installCatalogue(1);
    const at = payload.descriptor(0, "ShipDestroyed");
    payload.table().putWord(at + layout.values, TestPayload.lists);
    payload.values(TestPayload.lists, &.{"Ship"}, 2);
    try std.testing.expectError(error.BadFlag, payload.catalogue(arena.allocator()));
}

test "an event carries at most five values" {
    var arena: std.heap.ArenaAllocator = .init(std.testing.allocator);
    defer arena.deinit();
    var payload: TestPayload = .{};
    payload.installCatalogue(1);
    const at = payload.descriptor(0, "ShipDestroyed");
    payload.table().putWord(at + layout.values, TestPayload.lists);
    payload.values(TestPayload.lists, &.{ "A", "B", "C", "D", "E", "F" }, 0);
    try std.testing.expectError(error.TooManyValues, payload.catalogue(arena.allocator()));
}

test "emit writes Zig that parses" {
    const values_listed = [_]Value{.{ .label = "Ship", .kinds = 0x400, .extra = 2, .checked = true }};
    const listed = [_]Condition{
        .{ .name = "ShipDestroyed", .unknown_04 = 0, .subjects = 0b011, .values = &values_listed, .slot = 3, .veto_exempt = 0, .handlers = .{ .begin = 1, .add_member = 2, .verdict = 3 } },
        .{ .name = "MissionStart", .unknown_04 = 0x10, .subjects = 0, .values = &.{}, .slot = 0xFF, .veto_exempt = 0xFF, .handlers = null },
        .{ .name = "Odd", .unknown_04 = 0, .subjects = 0, .values = &.{}, .slot = 0xFF, .veto_exempt = 0x7F, .handlers = null },
    };
    var out: Io.Writer.Allocating = .init(std.testing.allocator);
    defer out.deinit();
    try emit(&out.writer, .{ .address = 0x004F2000, .conditions = &listed });
    try testing.expectZig(out.written());
    try std.testing.expect(std.mem.indexOf(u8, out.written(), ".slot = null,") != null);
    try std.testing.expect(std.mem.indexOf(u8, out.written(), ".veto_exempt = @enumFromInt(127),") != null);
}
