//! Reads the control bindings out of the payload: each action's name, and the key, modifier and
//! joystick button the game starts with.
//!
//! The table is data in the image, `ControlBinding` records, and runs to the first record whose
//! name is not an action's: upper-case words.

const std = @import("std");
const Io = std.Io;

const openreliant = @import("openreliant");
const ControlBinding = openreliant.lancer.input.ControlBinding;
const Modifier = ControlBinding.Modifier;

const image = @import("image.zig");
const testing = @import("testing.zig");

/// `control_bindings`, which `control_active` (`0x00412630`) indexes by action.
pub const table: u32 = 0x004E2380;
const record_size = @sizeOf(ControlBinding);
const name_size = @typeInfo(@FieldType(ControlBinding, "name")).array.len;

/// Actions a table this size could hold, as a bound on the scan.
const max_actions = 256;

pub const Binding = struct {
    name: []const u8,
    key: u16,
    modifier: Modifier,
    button: i16,
};

pub const Error = image.Error || error{ Empty, UnknownModifier };

pub fn read(arena: std.mem.Allocator, reader: image.Reader) (Error || std.mem.Allocator.Error)![]const Binding {
    var bindings: std.ArrayList(Binding) = .empty;
    for (0..max_actions) |index| {
        const at = table + @as(u32, @intCast(index)) * record_size;
        const record = try reader.slice(at, record_size);
        const binding = try parse(record[0..record_size]) orelse break;
        try bindings.append(arena, binding);
    }
    if (bindings.items.len == 0) return error.Empty;
    return bindings.toOwnedSlice(arena);
}

/// The binding one record holds, or null when its name is not an action's, which ends the table.
fn parse(record: *const [record_size]u8) error{UnknownModifier}!?Binding {
    const name = std.mem.sliceTo(record[@offsetOf(ControlBinding, "name")..][0..name_size], 0);
    if (!isActionName(name)) return null;
    const modifier: Modifier = @enumFromInt(field(u16, record, "modifier"));
    return .{
        .name = name,
        .key = field(u16, record, "key"),
        .modifier = switch (modifier) {
            .none, .shift, .control, .alt => modifier,
            _ => return error.UnknownModifier,
        },
        .button = field(i16, record, "button"),
    };
}

fn field(comptime T: type, record: *const [record_size]u8, comptime name: []const u8) T {
    return std.mem.readInt(T, record[@offsetOf(ControlBinding, name)..][0..@sizeOf(T)], .little);
}

/// Upper-case words, as every action's name is.
fn isActionName(name: []const u8) bool {
    if (name.len == 0) return false;
    for (name) |c| switch (c) {
        'A'...'Z', '0'...'9', ' ', '-' => {},
        else => return false,
    };
    return true;
}

/// The action's name as a Zig identifier: `NOSE UP` is `nose_up`.
fn identifier(buffer: *[name_size]u8, name: []const u8) []const u8 {
    for (name, buffer[0..name.len]) |c, *out| out.* = switch (c) {
        ' ', '-' => '_',
        else => std.ascii.toLower(c),
    };
    return buffer[0..name.len];
}

/// Writes `controls.zig`.
pub fn emit(w: *Io.Writer, bindings: []const Binding) Io.Writer.Error!void {
    try w.print(
        \\//! The player's actions, and the keys and joystick buttons the game binds them to at first.
        \\//!
        \\//! Generated by `src/tools/tablegen` from the payload executable's control bindings at
        \\//! 0x{X:0>8}, {d} actions. The names are the game's own. Do not edit by hand; run
        \\//! `make control-tables`.
        \\
        \\const std = @import("std");
        \\
        \\/// The modifier held with a key; `docs/engine/controls.md` describes how each counts.
        \\pub const Modifier = @import("../input.zig").ControlBinding.Modifier;
        \\
        \\/// Every action, numbered as the game numbers them.
        \\pub const Action = enum(u32) {{
        \\
    , .{ table, bindings.len });
    var buffer: [name_size]u8 = undefined;
    for (bindings, 0..) |binding, index| {
        try w.print("    {s} = {d},\n", .{ identifier(&buffer, binding.name), index });
    }
    try w.writeAll(
        \\};
        \\
        \\pub const Binding = struct {
        \\    /// The name the game shows.
        \\    name: []const u8,
        \\    /// A DirectInput scan code (`DIK_*`).
        \\    key: u16,
        \\    modifier: Modifier,
        \\    /// A joystick button, or null for none.
        \\    button: ?u8,
        \\};
        \\
        \\/// The bindings the game starts with, indexed by `Action`.
        \\pub const defaults = [_]Binding{
        \\
    );
    for (bindings) |binding| {
        try w.print("    .{{ .name = \"{f}\", .key = 0x{X:0>2}, .modifier = ", .{
            std.zig.fmtString(binding.name), binding.key,
        });
        try writeModifier(w, binding.modifier);
        try w.writeAll(", .button = ");
        if (std.math.cast(u8, binding.button)) |button| {
            try w.print("{d} }},\n", .{button});
        } else {
            try w.writeAll("null },\n");
        }
    }
    try w.writeAll(
        \\};
        \\
        \\pub fn binding(action: Action) Binding {
        \\    return defaults[@intFromEnum(action)];
        \\}
        \\
        \\comptime {
        \\    if (defaults.len != std.enums.values(Action).len) @compileError("one binding per action");
        \\}
        \\
        \\test binding {
        \\    for (std.enums.values(Action)) |action| {
        \\        const name = binding(action).name;
        \\        const tag = @tagName(action);
        \\        try std.testing.expectEqual(name.len, tag.len);
        \\        for (name, tag) |c, t| {
        \\            try std.testing.expectEqual(if (c == ' ' or c == '-') '_' else std.ascii.toLower(c), t);
        \\        }
        \\    }
        \\}
        \\
    );
}

fn writeModifier(w: *Io.Writer, modifier: Modifier) Io.Writer.Error!void {
    switch (modifier) {
        .none => try w.writeAll(".none"),
        .shift => try w.writeAll(".shift"),
        .control => try w.writeAll(".control"),
        .alt => try w.writeAll(".alt"),
        _ => try w.print("@enumFromInt({d})", .{@intFromEnum(modifier)}),
    }
}

fn testRecord(key: u16, modifier: u16, name: []const u8, button: i16) [record_size]u8 {
    var record: [record_size]u8 = @splat(0);
    std.mem.writeInt(u16, record[0..2], key, .little);
    std.mem.writeInt(u16, record[2..4], modifier, .little);
    @memcpy(record[4..][0..name.len], name);
    std.mem.writeInt(i16, record[0x4C..0x4E], button, .little);
    return record;
}

test parse {
    const record = testRecord(0x0F, 1, "REVERSE THRUST", -1);
    const binding = (try parse(&record)).?;
    try std.testing.expectEqualStrings("REVERSE THRUST", binding.name);
    try std.testing.expectEqual(0x0F, binding.key);
    try std.testing.expectEqual(Modifier.shift, binding.modifier);
    try std.testing.expectEqual(-1, binding.button);

    const alt = testRecord(0x2C, 3, "MATCH SPEED", 4);
    try std.testing.expectEqual(Modifier.alt, (try parse(&alt)).?.modifier);
    try std.testing.expectEqual(4, (try parse(&alt)).?.button);
}

test "parse ends the table at a record that is not an action" {
    const lower = testRecord(0x10, 0, "Not an action", -1);
    try std.testing.expectEqual(null, try parse(&lower));
    const empty = testRecord(0, 0, "", 0);
    try std.testing.expectEqual(null, try parse(&empty));
}

test "parse rejects a modifier the game does not know" {
    const record = testRecord(0x10, 4, "FIRE", -1);
    try std.testing.expectError(error.UnknownModifier, parse(&record));
}

test isActionName {
    try std.testing.expect(isActionName("ROLL SHIP ANTI-CLOCKWISE"));
    try std.testing.expect(isActionName("LOOK 2"));
    try std.testing.expect(!isActionName(""));
    try std.testing.expect(!isActionName("Fire"));
    try std.testing.expect(!isActionName("FIRE\x01"));
}

test identifier {
    var buffer: [name_size]u8 = undefined;
    try std.testing.expectEqualStrings("roll_ship_anti_clockwise", identifier(&buffer, "ROLL SHIP ANTI-CLOCKWISE"));
    try std.testing.expectEqualStrings("nose_up", identifier(&buffer, "NOSE UP"));
}

test "emit writes Zig that parses" {
    const bindings = [_]Binding{
        .{ .name = "AFTERBURNERS", .key = 0x0F, .modifier = .none, .button = 2 },
        .{ .name = "REVERSE THRUST", .key = 0x0F, .modifier = .shift, .button = -1 },
    };
    var out: Io.Writer.Allocating = .init(std.testing.allocator);
    defer out.deinit();
    try emit(&out.writer, &bindings);
    const source = out.written();
    try testing.expectZig(source);

    try std.testing.expect(std.mem.indexOf(u8, source, "    reverse_thrust = 1,\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".modifier = .shift, .button = null },\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, ".modifier = .none, .button = 2 },\n") != null);
}
