//! Reads the words of `gun_stats` that the payload holds in its data rather than reading them
//! from `gunstats.bin`: for each gun type, what a shot costs the ship, how large it is drawn and
//! the sound it makes. It reads the steps between a gun's shot sounds, where each type's bolt lies
//! in the shot texture, and how long its muzzle's flash lasts, at the same time.
//!
//! The table is 16 records, each a `guns.Gun`. Type 0 is no gun, so `stats_load_guns` fills the
//! figures of types 1 to 15 from the file and leaves the rest as the executable has it.

const std = @import("std");
const Io = std.Io;

const openreliant = @import("openreliant");
const guns = openreliant.engine.game.guns;

const image = @import("image.zig");
const testing = @import("testing.zig");

/// `gun_stats`.
pub const table: u32 = 0x00500CA4;

/// The steps between the sounds of a firing gun, by gun type.
pub const sound_periods: u32 = 0x00508700;

/// Where each gun type's bolt begins in the shot texture, and how wide it is, both in texels and
/// both by gun type less one (`bullet_build`).
pub const atlas_starts: u32 = 0x00500FB0;
pub const atlas_widths: u32 = 0x00500FEC;

/// How long a muzzle's flash lasts after a shot, in ticks, by gun type less one
/// (`gun_flash_ticks`).
pub const flash_ticks: u32 = 0x00500F64;

pub const Static = struct {
    kind: guns.Kind,
    bolt: [3]f32,
    sound: i32,
    sound_period: i32,
    atlas: [2]i32,
    flash_ticks: i32,
};

pub const Error = image.Error || error{ NotZero, NotKind, NotLoaded, NotPeriod, NotTicks };

pub fn read(arena: std.mem.Allocator, reader: image.Reader) (Error || std.mem.Allocator.Error)![]const Static {
    const records = try reader.records(guns.Gun, table, guns.max_types);
    const periods = try reader.records(i32, sound_periods, guns.max_types);
    // The atlas and flash tables are indexed by gun type less one, so they hold one entry fewer.
    const starts = try reader.records(i32, atlas_starts, guns.max_types - 1);
    const widths = try reader.records(i32, atlas_widths, guns.max_types - 1);
    const flashes = try reader.records(i32, flash_ticks, guns.max_types - 1);
    const types = try arena.alloc(Static, guns.max_types);
    for (types, records, periods, 0..) |*gun_type, record, period, index| {
        const atlas: [2]i32 = if (index == 0) .{ 0, 0 } else .{ starts[index - 1], widths[index - 1] };
        gun_type.* = try parse(record, period, atlas, index == 0);
        if (index == 0) continue;
        const ticks = flashes[index - 1];
        if (ticks < 0) return error.NotTicks;
        gun_type.flash_ticks = ticks;
    }
    return types;
}

/// The executable's own words of one record. Type 0 is no gun, so its record and its period are
/// empty; every other type fires a kind of shot this reader knows, sounds at a period it can
/// divide by, and still holds the figures the file overwrites. The refire interval is left out of
/// that last check: the executable holds 20 for most types and 3 for the last four.
fn parse(record: guns.Gun, period: i32, atlas: [2]i32, empty: bool) Error!Static {
    if (empty) {
        if (std.mem.indexOfNone(u8, std.mem.asBytes(&record), &.{0}) != null) return error.NotZero;
        if (period != 0) return error.NotZero;
    } else {
        if (record.kind != .energy and record.kind != .rounds) return error.NotKind;
        if (record.lifetime != loaded.lifetime or record.speed != loaded.speed) return error.NotLoaded;
        if (!std.meta.eql(record.damage, loaded.damage)) return error.NotLoaded;
        if (record.shot_energy != loaded.shot_energy) return error.NotLoaded;
        if (period < 1) return error.NotPeriod;
    }
    return .{
        .kind = record.kind,
        .bolt = record.bolt,
        .sound = record.sound,
        .sound_period = period,
        .atlas = atlas,
        .flash_ticks = 0,
    };
}

/// What each record holds where `stats_load_guns` writes, before it runs. The refire interval is
/// the one figure the records differ in.
const loaded: guns.Gun = .{
    .kind = .energy,
    .bolt = .{ 0, 0, 0 },
    .sound = 0,
    .lifetime = 200,
    .speed = 800,
    .damage = .{ .shield = 1, .hull = 4 },
    .refire_interval = 20,
    .shot_energy = 1,
};

/// Writes `stats.zig`.
pub fn emit(w: *Io.Writer, types: []const Static) Io.Writer.Error!void {
    try w.print(
        \\//! The words of `gun_stats` that the executable holds rather than `gunstats.bin`: for each
        \\//! gun type, what a shot costs the ship, how large it is drawn, the sound it makes and how
        \\//! often that sound is heard, where its bolt lies in the shot texture, and how long its
        \\//! muzzle's flash lasts.
        \\//!
        \\//! Generated by `src/tools/tablegen` from the payload executable's `gun_stats` at
        \\//! 0x{X:0>8}, its sound periods at 0x{X:0>8}, its texture spans at 0x{X:0>8} and
        \\//! 0x{X:0>8}, and its flashes' lengths at 0x{X:0>8}. Do not edit by hand; run
        \\//! `make gun-tables`.
        \\
        \\const guns = @import("../guns.zig");
        \\
        \\/// What a gun type's record holds besides its figures from `gunstats.bin`.
        \\pub const Static = struct {{
        \\    /// What a shot costs the ship.
        \\    kind: guns.Kind,
        \\    /// How large a shot is drawn: half its width, half its height, and its length
        \\    /// (`guns.boltMesh`).
        \\    bolt: [3]f32,
        \\    /// The sound a shot makes (`bullet_fire`).
        \\    sound: i32,
        \\}};
        \\
        \\/// Every gun type's, by its number. Type 0 is no gun: no muzzle may name it.
        \\pub const gun_types = [{d}]Static{{
        \\
    , .{ table, sound_periods, atlas_starts, atlas_widths, flash_ticks, types.len });
    for (types, 0..) |gun_type, index| {
        try w.print("    // 0x{X:0>2}\n    .{{ .kind = ", .{index});
        try enumValue(w, gun_type.kind);
        try w.print(", .bolt = .{{ {d}, {d}, {d} }}, .sound = {d} }},\n", .{
            gun_type.bolt[0],
            gun_type.bolt[1],
            gun_type.bolt[2],
            gun_type.sound,
        });
    }
    try w.print(
        \\}};
        \\
        \\/// The steps a gun of each type fires between the sounds of its shots: the player's shots
        \\/// are all heard, another ship's one in this many (`guns.heard`).
        \\pub const sound_periods = [{d}]i32{{
        \\
    , .{types.len});
    for (types, 0..) |gun_type, index| {
        try w.print("    {d}, // 0x{X:0>2}\n", .{ gun_type.sound_period, index });
    }
    try w.print(
        \\}};
        \\
        \\/// Where each gun type's bolt lies across the shot texture (`guns.boltTexture`): the texel
        \\/// it begins at and how many it spans. Type 0 is no gun, and a type that begins below zero
        \\/// is not drawn from it.
        \\pub const atlas = [{d}][2]i32{{
        \\
    , .{types.len});
    for (types, 0..) |gun_type, index| {
        try w.print("    .{{ {d}, {d} }}, // 0x{X:0>2}\n", .{ gun_type.atlas[0], gun_type.atlas[1], index });
    }
    try w.print(
        \\}};
        \\
        \\/// How long a muzzle's flash lasts after a shot of each type, in ticks (`guns.flash`). Type
        \\/// 0 is no gun, and a type of none shows none.
        \\pub const flash_ticks = [{d}]i32{{
        \\
    , .{types.len});
    for (types, 0..) |gun_type, index| {
        try w.print("    {d}, // 0x{X:0>2}\n", .{ gun_type.flash_ticks, index });
    }
    try w.writeAll(
        \\};
        \\
    );
}

/// A value of a non-exhaustive enum as Zig: its name, or the number where it has none.
fn enumValue(w: *Io.Writer, value: anytype) Io.Writer.Error!void {
    if (std.enums.tagName(@TypeOf(value), value)) |name| {
        try w.print(".{s}", .{name});
    } else {
        try w.print("@enumFromInt({d})", .{@intFromEnum(value)});
    }
}

test parse {
    // A gun type as the executable holds it: its kind and sound, and the file's figures unwritten.
    var record = loaded;
    record.kind = .rounds;
    record.sound = 7;
    const gun = try parse(record, 4, .{ 0, 32 }, false);
    try std.testing.expectEqual(guns.Kind.rounds, gun.kind);
    try std.testing.expectEqual(7, gun.sound);
    try std.testing.expectEqual(4, gun.sound_period);
    try std.testing.expectEqual([2]i32{ 0, 32 }, gun.atlas);

    // Type 0 is empty, and so is its period.
    try std.testing.expectError(error.NotZero, parse(record, 0, .{ 0, 32 }, true));
    try std.testing.expectError(error.NotZero, parse(std.mem.zeroes(guns.Gun), 1, .{ 0, 32 }, true));
    _ = try parse(std.mem.zeroes(guns.Gun), 0, .{ 0, 32 }, true);

    // A kind the reader doesn't know, a record the file has already filled in, and a period
    // nothing can be counted over.
    record.kind = @enumFromInt(4);
    try std.testing.expectError(error.NotKind, parse(record, 4, .{ 0, 32 }, false));
    record.kind = .energy;
    record.damage.hull = 9;
    try std.testing.expectError(error.NotLoaded, parse(record, 4, .{ 0, 32 }, false));
    record.damage.hull = loaded.damage.hull;
    try std.testing.expectError(error.NotPeriod, parse(record, 0, .{ 0, 32 }, false));
}

test read {
    const allocator = std.testing.allocator;
    var arena_state: std.heap.ArenaAllocator = .init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var records: [guns.max_types]guns.Gun = @splat(loaded);
    var periods: [guns.max_types]i32 = @splat(1);
    records[0] = std.mem.zeroes(guns.Gun);
    periods[0] = 0;
    // Type 1 draws the guns' charge and sounds every third step; type 8 fires rounds.
    records[1].sound = 2;
    periods[1] = 3;
    records[8].kind = .rounds;

    // Type 1's bolt begins at the texture's left edge, and type 2 has none of its own.
    var starts: [guns.max_types - 1]i32 = @splat(32);
    var widths: [guns.max_types - 1]i32 = @splat(32);
    starts[0] = 0;
    starts[1] = -1;
    // Type 1's flash lasts 50 ticks, type 15 shows none.
    var flashes: [guns.max_types - 1]i32 = @splat(30);
    flashes[0] = 50;
    flashes[14] = 0;
    const payload = try testing.reader(allocator, &.{
        .{ .va = table, .bytes = std.mem.sliceAsBytes(records[0..]) },
        .{ .va = sound_periods, .bytes = std.mem.sliceAsBytes(periods[0..]) },
        .{ .va = atlas_starts, .bytes = std.mem.sliceAsBytes(starts[0..]) },
        .{ .va = atlas_widths, .bytes = std.mem.sliceAsBytes(widths[0..]) },
        .{ .va = flash_ticks, .bytes = std.mem.sliceAsBytes(flashes[0..]) },
    });
    defer testing.freeReader(allocator, payload);
    const types = try read(arena, payload);
    try std.testing.expectEqual(guns.max_types, types.len);
    try std.testing.expectEqual(guns.Kind.energy, types[1].kind);
    try std.testing.expectEqual(2, types[1].sound);
    try std.testing.expectEqual(3, types[1].sound_period);
    try std.testing.expectEqual(guns.Kind.rounds, types[8].kind);
    // The atlas tables start at type 1.
    try std.testing.expectEqual([2]i32{ 0, 32 }, types[1].atlas);
    try std.testing.expectEqual([2]i32{ -1, 32 }, types[2].atlas);
    try std.testing.expectEqual([2]i32{ 0, 0 }, types[0].atlas);
    // So does the flash table.
    try std.testing.expectEqual(50, types[1].flash_ticks);
    try std.testing.expectEqual(30, types[2].flash_ticks);
    try std.testing.expectEqual(0, types[15].flash_ticks);
    try std.testing.expectEqual(0, types[0].flash_ticks);

    // A flash can't last less than no time.
    flashes[3] = -1;
    const broken = try testing.reader(allocator, &.{
        .{ .va = table, .bytes = std.mem.sliceAsBytes(records[0..]) },
        .{ .va = sound_periods, .bytes = std.mem.sliceAsBytes(periods[0..]) },
        .{ .va = atlas_starts, .bytes = std.mem.sliceAsBytes(starts[0..]) },
        .{ .va = atlas_widths, .bytes = std.mem.sliceAsBytes(widths[0..]) },
        .{ .va = flash_ticks, .bytes = std.mem.sliceAsBytes(flashes[0..]) },
    });
    defer testing.freeReader(allocator, broken);
    try std.testing.expectError(error.NotTicks, read(arena, broken));

    var out: Io.Writer.Allocating = .init(allocator);
    defer out.deinit();
    try emit(&out.writer, types);
    try testing.expectZig(out.written());
}
