//! Reads the combat maneuvers out of the payload: each maneuver's name, the inputs it may mirror,
//! how long it runs and its script; the handlers of each opcode of the script language; and the
//! lists Fight picks a maneuver from, by where the two ships are.
//!
//! The maneuver table runs to the first record whose name is not a string, and each script to its
//! first line without text.

const std = @import("std");
const Io = std.Io;

const openreliant = @import("openreliant");
const lancer_maneuvers = openreliant.lancer.game.aidefend;
const Record = lancer_maneuvers.Maneuver;
const Opcode = lancer_maneuvers.Opcode;

const image = @import("image.zig");
const testing = @import("testing.zig");

/// `maneuvers`, which `maneuver_run` (`0x004069B0`) indexes.
pub const table_address: u32 = 0x004E1070;
/// `maneuver_handlers`: a start and a run routine for each opcode.
pub const handlers_address: u32 = 0x004E0CC0;
/// `maneuver_choices`: nine pointers to lists, a count and then maneuver numbers, by where the
/// target is from the ship's nose and where the ship is from the target's.
pub const choices_address: u32 = 0x004E1918;

const record_size = @sizeOf(Record);
const opcode_count = std.enums.values(Opcode).len;
const bearings = 3;
const max_maneuvers = 64;
const max_lines = 256;

pub const Maneuver = struct {
    name: []const u8,
    mirror: u8,
    min_ticks: u16,
    max_ticks: u16,
    script_address: u32,
    script: []const []const u8,
};

pub const Handlers = struct { start: u32, run: u32 };

pub const Table = struct {
    maneuvers: []const Maneuver,
    handlers: [opcode_count]Handlers,
    choices: [bearings][bearings][]const u8,
};

pub const Error = image.Error || error{ Empty, ScriptTooLong, BadChoice };

pub fn read(arena: std.mem.Allocator, reader: image.Reader) (Error || std.mem.Allocator.Error)!Table {
    var list: std.ArrayList(Maneuver) = .empty;
    for (0..max_maneuvers) |index| {
        const at = table_address + @as(u32, @intCast(index)) * record_size;
        const name = reader.string(try reader.word(at + @offsetOf(Record, "name"))) catch break;
        if (name.len == 0) break;
        const script_address = try reader.word(at + @offsetOf(Record, "script"));
        try list.append(arena, .{
            .name = name,
            .mirror = try reader.int(u8, at + @offsetOf(Record, "mirror")),
            .min_ticks = try reader.int(u16, at + @offsetOf(Record, "min_ticks")),
            .max_ticks = try reader.int(u16, at + @offsetOf(Record, "max_ticks")),
            .script_address = script_address,
            .script = try readScript(arena, reader, script_address),
        });
    }
    if (list.items.len == 0) return error.Empty;

    var table: Table = .{ .maneuvers = try list.toOwnedSlice(arena), .handlers = undefined, .choices = undefined };
    for (&table.handlers, 0..) |*pair, index| {
        const at = handlers_address + @as(u32, @intCast(index)) * @sizeOf(lancer_maneuvers.Handlers);
        pair.* = .{ .start = try reader.word(at), .run = try reader.word(at + 4) };
    }
    for (&table.choices, 0..) |*row, ours| {
        for (row, 0..) |*choice, theirs| {
            const list_address = try reader.word(choices_address + @as(u32, @intCast(ours * bearings + theirs)) * 4);
            const count = try reader.int(u8, list_address);
            choice.* = try arena.dupe(u8, try reader.slice(list_address + 1, count));
            for (choice.*) |maneuver| {
                if (maneuver >= table.maneuvers.len) return error.BadChoice;
            }
        }
    }
    return table;
}

fn readScript(arena: std.mem.Allocator, reader: image.Reader, address: u32) (Error || std.mem.Allocator.Error)![]const []const u8 {
    var lines: std.ArrayList([]const u8) = .empty;
    for (0..max_lines) |index| {
        const text = try reader.word(address + @as(u32, @intCast(index)) * @sizeOf(lancer_maneuvers.ScriptLine));
        if (text == 0) return lines.toOwnedSlice(arena);
        try lines.append(arena, try reader.string(text));
    } else return error.ScriptTooLong;
}

/// A maneuver's name as a Zig identifier: `loop the loop` is `loop_the_loop`.
pub fn identifier(arena: std.mem.Allocator, name: []const u8) std.mem.Allocator.Error![]const u8 {
    const out = try arena.alloc(u8, name.len);
    for (name, out) |c, *o| o.* = if (c == ' ' or c == '-') '_' else std.ascii.toLower(c);
    return out;
}

/// Writes `maneuvers.zig`.
pub fn emit(arena: std.mem.Allocator, w: *Io.Writer, table: Table) !void {
    try w.print(
        \\//! The combat maneuvers the Fight order runs: each one's name, the inputs it may mirror, how long
        \\//! it runs and its script; the routines each opcode of the script language runs; and the lists
        \\//! Fight picks a maneuver from. `docs/engine/maneuvers.md` describes them.
        \\//!
        \\//! Generated by `src/tools/tablegen` from the payload executable's maneuver table at
        \\//! 0x{X:0>8}, {d} maneuvers, its handler table at 0x{X:0>8} and its choice lists at
        \\//! 0x{X:0>8}. Names and scripts are the developers' own. Do not edit by hand; run
        \\//! `make maneuver-tables`.
        \\
        \\const std = @import("std");
        \\
        \\const script = @import("script.zig");
        \\pub const Opcode = script.Opcode;
        \\pub const Mirror = @import("../aidefend.zig").Mirror;
        \\
        \\/// Where the tables are in the payload executable.
        \\pub const addresses = struct {{
        \\    pub const table: u32 = 0x{X:0>8};
        \\    pub const handlers: u32 = 0x{X:0>8};
        \\    pub const choices: u32 = 0x{X:0>8};
        \\}};
        \\
        \\/// Every maneuver, numbered as the game numbers them.
        \\pub const Maneuver = enum(u16) {{
        \\
    , .{ table_address, table.maneuvers.len, handlers_address, choices_address, table_address, handlers_address, choices_address });
    const names = try arena.alloc([]const u8, table.maneuvers.len);
    for (table.maneuvers, names, 0..) |maneuver, *name, index| {
        name.* = try identifier(arena, maneuver.name);
        try w.print("    {f} = {d},\n", .{ std.zig.fmtId(name.*), index });
    }
    try w.writeAll(
        \\    _,
        \\};
        \\
        \\pub const Info = struct {
        \\    maneuver: Maneuver,
        \\    /// The developers' name.
        \\    name: []const u8,
        \\    /// The inputs it may mirror, a random choice of them each time it starts.
        \\    mirror: Mirror,
        \\    /// How long it runs, in ticks, unless Fight says otherwise.
        \\    min_ticks: u16,
        \\    max_ticks: u16,
        \\    /// Where its script is in the payload executable.
        \\    script_address: u32,
        \\    script: []const []const u8,
        \\};
        \\
        \\/// Every maneuver, by number.
        \\pub const table = [_]Info{
        \\
    );
    for (table.maneuvers, names) |maneuver, name| {
        try w.print(
            "    .{{\n        .maneuver = .{f},\n        .name = \"{f}\",\n        .mirror = @bitCast(@as(u8, 0x{X:0>2})),\n        .min_ticks = {d},\n        .max_ticks = {d},\n        .script_address = 0x{X:0>8},\n        .script = &.{{\n",
            .{ std.zig.fmtId(name), std.zig.fmtString(maneuver.name), maneuver.mirror, maneuver.min_ticks, maneuver.max_ticks, maneuver.script_address },
        );
        for (maneuver.script) |line| try w.print("            \"{f}\",\n", .{std.zig.fmtString(line)});
        try w.writeAll("        },\n    },\n");
    }
    try w.writeAll(
        \\};
        \\
        \\pub const Handlers = struct {
        \\    /// Runs as an instruction starts; true makes it wait.
        \\    start: ?u32,
        \\    /// Runs each update while the instruction waits; true keeps it waiting.
        \\    run: ?u32,
        \\};
        \\
        \\/// What each opcode runs, by address in the payload executable.
        \\pub const handlers: std.EnumArray(Opcode, Handlers) = .init(.{
        \\
    );
    for (std.enums.values(Opcode), table.handlers) |opcode, pair| {
        try w.print("    .{f} = .{{ .start = ", .{std.zig.fmtId(@tagName(opcode))});
        try optional(w, pair.start);
        try w.writeAll(", .run = ");
        try optional(w, pair.run);
        try w.writeAll(" },\n");
    }
    try w.writeAll(
        \\});
        \\
        \\/// Where one ship is from the other's nose: within 60 degrees of it, abeam, or behind.
        \\pub const Bearing = enum { ahead, abeam, behind };
        \\
        \\/// The maneuvers Fight picks from at random, by where its target is from the ship's nose, then
        \\/// where the ship is from the target's.
        \\pub const choices = [3][3][]const Maneuver{
        \\
    );
    for (table.choices) |row| {
        try w.writeAll("    .{\n");
        for (row) |choice| {
            try w.writeAll("        &.{");
            for (choice, 0..) |maneuver, index| {
                try w.print("{s}.{f}", .{ if (index == 0) " " else ", ", std.zig.fmtId(names[maneuver]) });
            }
            try w.writeAll(" },\n");
        }
        try w.writeAll("    },\n");
    }
    try w.writeAll(
        \\};
        \\
        \\/// The maneuver numbered `maneuver`, or null past the table.
        \\pub fn info(maneuver: Maneuver) ?Info {
        \\    const index = @intFromEnum(maneuver);
        \\    return if (index < table.len) table[index] else null;
        \\}
        \\
        \\/// Each maneuver's script, compiled: a line that does not compile fails the build.
        \\pub const compiled = blk: {
        \\    var out: [table.len][]const script.Instruction = undefined;
        \\    for (table, &out) |entry, *instructions| {
        \\        const lines = script.compile(entry.script);
        \\        instructions.* = &lines;
        \\    }
        \\    break :blk out;
        \\};
        \\
        \\comptime {
        \\    if (table.len != std.enums.values(Maneuver).len) @compileError("one entry per maneuver");
        \\    for (table, 0..) |entry, index| {
        \\        if (@intFromEnum(entry.maneuver) != index) @compileError("maneuvers out of place");
        \\    }
        \\}
        \\
        \\test info {
        \\    for (table) |entry| try std.testing.expectEqual(entry.maneuver, info(entry.maneuver).?.maneuver);
        \\    try std.testing.expectEqual(null, info(@enumFromInt(table.len)));
        \\    for (compiled, table) |instructions, entry| try std.testing.expectEqual(entry.script.len, instructions.len);
        \\}
        \\
    );
}

fn optional(w: *Io.Writer, address: u32) Io.Writer.Error!void {
    if (address == 0) try w.writeAll("null") else try w.print("0x{X:0>8}", .{address});
}

/// A synthetic payload: two maneuvers with their scripts, the handler table and the choice lists.
const TestPayload = struct {
    data: [0x2000]u8 = @splat(0),

    const data_va = handlers_address & ~@as(u32, 0xFFF);
    const strings = choices_address + 0x100;

    fn region(payload: *TestPayload) testing.Region {
        return .{ .va = data_va, .bytes = &payload.data };
    }

    fn build(payload: *TestPayload) void {
        const r = payload.region();
        var next_string: u32 = strings;
        const text = struct {
            fn put(into: testing.Region, at: *u32, s: []const u8) u32 {
                const address = at.*;
                into.putString(address, s);
                at.* += @intCast(s.len + 1);
                return address;
            }
        };
        // Scripts go just before the table, where the payload keeps them.
        const scripts = [_][]const []const u8{ &.{ "Cloak(on)", "loop:", "\tGoto loop" }, &.{"EndScript()"} };
        const names = [_][]const u8{ "defend dodge1", "run to ship" };
        var script_at: u32 = handlers_address + opcode_count * 8;
        for (scripts, names, 0..) |lines, name, index| {
            const at = table_address + @as(u32, @intCast(index)) * record_size;
            r.put(at, &.{0x05});
            r.putWord(at + @offsetOf(Record, "script"), script_at);
            r.putWord(at + @offsetOf(Record, "name"), text.put(r, &next_string, name));
            r.putHalf(at + @offsetOf(Record, "min_ticks"), 400);
            r.putHalf(at + @offsetOf(Record, "max_ticks"), 1000);
            for (lines) |line_text| {
                r.putWord(script_at, text.put(r, &next_string, line_text));
                script_at += 8;
            }
            script_at += 8;
        }
        // The third record's name is text, as after the payload's last.
        r.putWord(table_address + 2 * record_size + @offsetOf(Record, "name"), 0x6E757220);
        for (0..opcode_count) |index| r.putWord(handlers_address + @as(u32, @intCast(index)) * 8, 0x00405000 + @as(u32, @intCast(index)));
        // Every choice list holds both maneuvers.
        const list_at = text.put(r, &next_string, &.{ 2, 0, 1 });
        for (0..bearings * bearings) |index| r.putWord(choices_address + @as(u32, @intCast(index)) * 4, list_at);
    }

    fn table(payload: *TestPayload, arena: std.mem.Allocator) !Table {
        return read(arena, try testing.reader(arena, &.{payload.region()}));
    }
};

test read {
    var arena: std.heap.ArenaAllocator = .init(std.testing.allocator);
    defer arena.deinit();
    var payload: TestPayload = .{};
    payload.build();

    const read_table = try payload.table(arena.allocator());
    try std.testing.expectEqual(2, read_table.maneuvers.len);
    const dodge = read_table.maneuvers[0];
    try std.testing.expectEqualStrings("defend dodge1", dodge.name);
    try std.testing.expectEqual(0x05, dodge.mirror);
    try std.testing.expectEqual(400, dodge.min_ticks);
    try std.testing.expectEqual(1000, dodge.max_ticks);
    try std.testing.expectEqual(3, dodge.script.len);
    try std.testing.expectEqualStrings("\tGoto loop", dodge.script[2]);
    try std.testing.expectEqualStrings("EndScript()", read_table.maneuvers[1].script[0]);
    try std.testing.expectEqual(0x00405003, read_table.handlers[3].start);
    try std.testing.expectEqualSlices(u8, &.{ 0, 1 }, read_table.choices[2][1]);
}

test "emit writes Zig that parses" {
    var arena: std.heap.ArenaAllocator = .init(std.testing.allocator);
    defer arena.deinit();
    var payload: TestPayload = .{};
    payload.build();
    const read_table = try payload.table(arena.allocator());

    var out: Io.Writer.Allocating = .init(std.testing.allocator);
    defer out.deinit();
    try emit(arena.allocator(), &out.writer, read_table);
    try testing.expectZig(out.written());
    try std.testing.expect(std.mem.indexOf(u8, out.written(), "    run_to_ship = 1,\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, out.written(), "            \"\\tGoto loop\",\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, out.written(), "        &.{ .defend_dodge1, .run_to_ship },\n") != null);
}
