//! Reads the explosion sequences out of the payload: for each capital ship type that splits in two
//! as its hull is destroyed, the type of its other half, how the split runs, and the sizes and
//! counts of its fireballs and burning bits.
//!
//! The table is `0x2C` bytes a record, 40 of them, which `explode_sequence_find` (`0x00471D30`)
//! walks by the object's own type.

const std = @import("std");
const Io = std.Io;

const image = @import("image.zig");
const testing = @import("testing.zig");

/// The sequence table, and the address its walk stops at.
pub const table: u32 = 0x004FFB50;
pub const table_end: u32 = 0x00500230;

/// A record as the payload lays it out.
const Stored = extern struct {
    type: u32,
    other_half: u32,
    _unknown_08: u32,
    mode: u16,
    _padding_0e: u16,
    fireball: f32,
    big_fireball: f32,
    bit_size: f32,
    bits: i32,
    bodies: f32,
    duration: i32,
    variants: i32,

    comptime {
        std.debug.assert(@sizeOf(Stored) == 0x2C);
    }
};

pub const Record = struct {
    type: u32,
    other_half: ?u32,
    _unknown_08: ?u32,
    mode: u16,
    fireball: f32,
    big_fireball: f32,
    bit_size: f32,
    bits: i32,
    bodies: f32,
    duration: i32,
    variants: i32,
};

/// No type: what `+0x04` and `+0x08` hold where the record names none.
const none: u32 = 0xFFFF_FFFF;

pub const Error = image.Error;

pub fn read(arena: std.mem.Allocator, reader: image.Reader) (Error || std.mem.Allocator.Error)![]const Record {
    const count = (table_end - table) / @sizeOf(Stored);
    const records = try arena.alloc(Record, count);
    for (records, 0..) |*record, index| {
        record.* = parse(try reader.record(Stored, table + @as(u32, @intCast(index)) * @sizeOf(Stored)));
    }
    return records;
}

fn parse(stored: Stored) Record {
    return .{
        .type = stored.type,
        .other_half = if (stored.other_half == none) null else stored.other_half,
        ._unknown_08 = if (stored._unknown_08 == none) null else stored._unknown_08,
        .mode = stored.mode,
        .fireball = stored.fireball,
        .big_fireball = stored.big_fireball,
        .bit_size = stored.bit_size,
        .bits = stored.bits,
        .bodies = stored.bodies,
        .duration = stored.duration,
        .variants = stored.variants,
    };
}

/// Writes `sequences.zig`.
pub fn emit(w: *Io.Writer, records: []const Record) Io.Writer.Error!void {
    try w.print(
        \\//! The explosion sequences: for each capital ship type that splits in two as its hull is
        \\//! destroyed, the type of its other half, how the split runs, and the sizes and counts of its
        \\//! fireballs and burning bits.
        \\//!
        \\//! Generated by `src/tools/tablegen` from the payload executable's sequence table at
        \\//! 0x{X:0>8}, {d} records. Do not edit by hand; run `make explode-tables`.
        \\
        \\pub const Record = struct {{
        \\    /// The object type it is for, the object's own rather than the type it takes its stats
        \\    /// from.
        \\    type: u32,
        \\    /// The type of the other half the split makes (`+0x04`), or none.
        \\    other_half: ?u32,
        \\    /// **Unknown.** A second other half's type (`+0x08`), or none. Nothing reads it.
        \\    _unknown_08: ?u32,
        \\    /// How the split runs (`+0x0C`).
        \\    mode: Mode,
        \\    /// What its fireballs' sizes are reckoned from (`+0x10`).
        \\    fireball: f32,
        \\    /// The size of a sweep's occasional big fireball (`+0x14`); 0 or less for 0.35 of the
        \\    /// ship's radius.
        \\    big_fireball: f32,
        \\    /// The size of its burning bits (`+0x18`).
        \\    bit_size: f32,
        \\    /// What the number of its burning bits is reckoned from (`+0x1C`).
        \\    bits: i32,
        \\    /// The chance a burning bit is a body (`+0x20`).
        \\    bodies: f32,
        \\    /// How long the split runs, in ticks (`+0x24`); its shockwave lasts half as long again.
        \\    duration: i32,
        \\    /// **Unknown.** How many ways the ship can split (`+0x28`); 1 in every record.
        \\    variants: i32,
        \\}};
        \\
        \\pub const Mode = enum(u16) {{
        \\    /// A cut sweeping along the ship, the halves' wrecks showing behind it.
        \\    sweep = 0,
        \\    /// Bursts about the ship, and the wrecks at the end.
        \\    bursts = 1,
        \\    _,
        \\}};
        \\
        \\/// Every record, in the payload's order.
        \\pub const records = [_]Record{{
        \\
    , .{ table, records.len });
    for (records) |record| {
        try w.print("    .{{ .type = 0x{X:0>2}, .other_half = ", .{record.type});
        try optionalType(w, record.other_half);
        try w.writeAll(", ._unknown_08 = ");
        try optionalType(w, record._unknown_08);
        try w.writeAll(", .mode = ");
        try modeName(w, record.mode);
        try w.print(", .fireball = {d}, .big_fireball = {d}, .bit_size = {d}, .bits = {d}, .bodies = {d}, .duration = {d}, .variants = {d} }},\n", .{
            record.fireball,
            record.big_fireball,
            record.bit_size,
            record.bits,
            record.bodies,
            record.duration,
            record.variants,
        });
    }
    try w.writeAll(
        \\};
        \\
    );
}

fn modeName(w: *Io.Writer, mode: u16) Io.Writer.Error!void {
    switch (mode) {
        0 => try w.writeAll(".sweep"),
        1 => try w.writeAll(".bursts"),
        else => try w.print("@enumFromInt({d})", .{mode}),
    }
}

fn optionalType(w: *Io.Writer, value: ?u32) Io.Writer.Error!void {
    if (value) |number| try w.print("0x{X:0>2}", .{number}) else try w.writeAll("null");
}

test parse {
    const record = parse(.{
        .type = 0x37,
        .other_half = 0x75,
        ._unknown_08 = none,
        .mode = 0,
        ._padding_0e = 0,
        .fireball = 2300,
        .big_fireball = -1,
        .bit_size = 0.45,
        .bits = 3,
        .bodies = 0.05,
        .duration = 900,
        .variants = 1,
    });
    try std.testing.expectEqual(0x75, record.other_half.?);
    try std.testing.expectEqual(null, record._unknown_08);
    try std.testing.expectEqual(900, record.duration);
}

test read {
    const allocator = std.testing.allocator;
    var arena_state: std.heap.ArenaAllocator = .init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const bytes = try allocator.alloc(u8, table_end - table);
    defer allocator.free(bytes);
    @memset(bytes, 0);
    const region: testing.Region = .{ .va = table, .bytes = bytes };
    region.putRecord(table, Stored{ .type = 0x21, .other_half = 0x5D, ._unknown_08 = none, .mode = 1, ._padding_0e = 0, .fireball = 500, .big_fireball = 5000, .bit_size = 0.3, .bits = 3, .bodies = 0, .duration = 100, .variants = 1 });
    region.putRecord(table + @sizeOf(Stored), Stored{ .type = 0x1E, .other_half = none, ._unknown_08 = none, .mode = 1, ._padding_0e = 0, .fireball = 500, .big_fireball = -1, .bit_size = 0.3, .bits = 2, .bodies = 0, .duration = 100, .variants = 1 });

    const payload = try testing.reader(allocator, &.{region});
    defer testing.freeReader(allocator, payload);
    const records = try read(arena, payload);
    try std.testing.expectEqual(40, records.len);
    try std.testing.expectEqual(0x5D, records[0].other_half.?);
    try std.testing.expectEqual(null, records[1].other_half);

    var out: Io.Writer.Allocating = .init(allocator);
    defer out.deinit();
    try emit(&out.writer, records);
    try testing.expectZig(out.written());
}
