//! Reads the 3D sounds' table (`sound3d.Definition`, from `0x00507140`): each sound up to the
//! record whose entry is -1, then the voice classes for each size of provider, and how the player's
//! engine sounds for each ship type.

const std = @import("std");
const Io = std.Io;

const openreliant = @import("openreliant");
const sound3d = openreliant.engine.game.sound3d;

const image = @import("image.zig");
const testing = @import("testing.zig");

pub const table: u32 = 0x00507140;

/// The voice classes, right after the table's closing record.
pub const class_table: u32 = 0x005085B4;

/// The engine's rates and volumes by ship type: at no throttle, and what full throttle adds.
pub const engine_tables = [4]u32{ 0x00508740, 0x00508774, 0x005087A8, 0x005087DC };
pub const engine_types = 13;

/// More than the table could hold before it runs into the voice classes.
const max_sounds = 128;

pub const Tables = struct {
    definitions: []const sound3d.Definition,
    classes: [sound3d.class_rows][sound3d.classes_per_row]sound3d.Class,
    engines: [engine_types]sound3d.Engine,
};

pub const Error = image.Error || error{ NoEnd, BadDefinition, BadClass };

pub fn read(arena: std.mem.Allocator, reader: image.Reader) (Error || std.mem.Allocator.Error)!Tables {
    var definitions: std.ArrayList(sound3d.Definition) = .empty;
    for (0..max_sounds) |index| {
        const record = try reader.record(sound3d.Definition, table + @as(u32, @intCast(index)) * @sizeOf(sound3d.Definition));
        if (record.entry == std.math.maxInt(u32)) break;
        try check(record);
        try definitions.append(arena, record);
    } else return error.NoEnd;

    var tables: Tables = .{ .definitions = definitions.items, .classes = undefined, .engines = undefined };
    const rows = try reader.records([sound3d.classes_per_row]u8, class_table, sound3d.class_rows);
    for (&tables.classes, rows) |*row, bytes| {
        for (row, bytes) |*class, byte| {
            if (byte > @intFromEnum(sound3d.Class.flyby)) return error.BadClass;
            class.* = @enumFromInt(byte);
        }
    }
    const columns = [4][]align(1) const i32{
        try reader.records(i32, engine_tables[0], engine_types),
        try reader.records(i32, engine_tables[1], engine_types),
        try reader.records(i32, engine_tables[2], engine_types),
        try reader.records(i32, engine_tables[3], engine_types),
    };
    for (&tables.engines, 0..) |*engine, type_index| engine.* = .{
        .rate = columns[0][type_index],
        .rate_by_throttle = columns[1][type_index],
        .volume = columns[2][type_index],
        .volume_by_throttle = columns[3][type_index],
    };
    return tables;
}

/// A definition this reader understands: named, following something it knows, heard within a
/// distance.
fn check(record: sound3d.Definition) Error!void {
    if (record.nameText().len == 0) return error.BadDefinition;
    if (std.enums.tagName(sound3d.Follows, record.follows) == null or record.follows == .none) return error.BadDefinition;
    if (!(record.min_distance > 0) or !(record.max_distance >= record.min_distance)) return error.BadDefinition;
}

/// Writes `sounds.zig`.
pub fn emit(w: *Io.Writer, tables: Tables) Io.Writer.Error!void {
    try w.print(
        \\//! The 3D sounds' definitions, the voice classes for each size of provider, and how the
        \\//! player's engine sounds for each ship type.
        \\//!
        \\//! Generated by `src/tools/tablegen` from the payload executable's table at 0x{X:0>8},
        \\//! {d} sounds, its voice classes at 0x{X:0>8} and its engine tables at 0x{X:0>8}. Do not
        \\//! edit by hand; run `make sound-tables`.
        \\
        \\const sound3d = @import("../sound3d.zig");
        \\
        \\/// Each sound, by its number, named as the table names it.
        \\pub const Sound = enum(u8) {{
        \\
    , .{ table, tables.definitions.len, class_table, engine_tables[0] });
    for (tables.definitions, 0..) |definition, index| {
        try w.writeAll("    ");
        for (definition.nameText()) |char| try w.writeByte(std.ascii.toLower(char));
        try w.print(" = {d},\n", .{index});
    }
    try w.writeAll(
        \\};
        \\
        \\/// Each sound's definition, by its number.
        \\pub const definitions = [_]sound3d.Definition{
        \\
    );
    for (tables.definitions) |definition| {
        try w.print("    .{{ .entry = {d}, .volume = {d}, .loop_count = {d}, .follows = ", .{ definition.entry, definition.volume, definition.loop_count });
        try enumValue(w, definition.follows);
        try w.print(", .min_distance = {d}, .max_distance = {d}, .cone_inner = {d}, .cone_outer = {d}, .cone_outer_volume = {d}, .name = name(\"{s}\") }},\n", .{
            definition.min_distance,
            definition.max_distance,
            definition.cone_inner,
            definition.cone_outer,
            definition.cone_outer_volume,
            definition.nameText(),
        });
    }
    try w.writeAll(
        \\};
        \\
        \\/// The voice classes: up to 14 voices, up to 30, and more.
        \\pub const classes = [3][32]sound3d.Class{
        \\
    );
    for (tables.classes) |row| {
        try w.writeAll("    .{ ");
        for (row, 0..) |class, index| {
            if (index != 0) try w.writeAll(", ");
            try enumValue(w, class);
        }
        try w.writeAll(" },\n");
    }
    try w.writeAll(
        \\};
        \\
        \\/// How the player's engine sounds, by ship type.
        \\pub const engines = [_]sound3d.Engine{
        \\
    );
    for (tables.engines) |engine| {
        try w.print("    .{{ .rate = {d}, .rate_by_throttle = {d}, .volume = {d}, .volume_by_throttle = {d} }},\n", .{ engine.rate, engine.rate_by_throttle, engine.volume, engine.volume_by_throttle });
    }
    try w.writeAll(
        \\};
        \\
        \\/// A definition's name, padded as the table pads it.
        \\fn name(comptime text: []const u8) [32]u8 {
        \\    var padded: [32]u8 = @splat(0);
        \\    @memcpy(padded[0..text.len], text);
        \\    return padded;
        \\}
        \\
        \\comptime {
        \\    if (@typeInfo(Sound).@"enum".fields.len != definitions.len) @compileError("a sound without a definition");
        \\}
        \\
    );
}

fn enumValue(w: *Io.Writer, value: anytype) Io.Writer.Error!void {
    if (std.enums.tagName(@TypeOf(value), value)) |tag| {
        try w.print(".{s}", .{tag});
    } else {
        try w.print("@enumFromInt({d})", .{@intFromEnum(value)});
    }
}

fn testDefinition(entry: u32, follows: sound3d.Follows, text: []const u8) sound3d.Definition {
    var definition = std.mem.zeroInit(sound3d.Definition, .{
        .entry = entry,
        .volume = 1,
        .loop_count = 1,
        .follows = follows,
        .min_distance = 10000,
        .max_distance = 200000,
        .cone_inner = 120,
        .cone_outer = 210,
        .cone_outer_volume = 100,
    });
    @memcpy(definition.name[0..text.len], text);
    return definition;
}

test read {
    const allocator = std.testing.allocator;
    var arena_state: std.heap.ArenaAllocator = .init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    // Two sounds, then the closing record.
    var records = [_]sound3d.Definition{
        testDefinition(67, .shot, "GUN01"),
        testDefinition(62, .point, "EXPLOSION01"),
        testDefinition(std.math.maxInt(u32), .point_facing, ""),
    };
    var classes: [3][32]u8 = @splat(@splat(0));
    classes[2][0] = 1;
    classes[2][5] = 5;
    var columns: [4][engine_types]i32 = @splat(@splat(10));
    columns[0][2] = 22050;
    const payload = try testing.reader(allocator, &.{
        .{ .va = table, .bytes = std.mem.sliceAsBytes(records[0..]) },
        .{ .va = class_table, .bytes = std.mem.sliceAsBytes(classes[0..]) },
        .{ .va = engine_tables[0], .bytes = std.mem.sliceAsBytes(columns[0..]) },
    });
    defer testing.freeReader(allocator, payload);
    const tables = try read(arena, payload);
    try std.testing.expectEqual(2, tables.definitions.len);
    try std.testing.expectEqualStrings("EXPLOSION01", tables.definitions[1].nameText());
    try std.testing.expectEqual(sound3d.Class.player_guns, tables.classes[2][0]);
    try std.testing.expectEqual(sound3d.Class.player_engines, tables.classes[2][5]);
    try std.testing.expectEqual(22050, tables.engines[2].rate);

    var buffer: [16 << 10]u8 = undefined;
    var out: Io.Writer = .fixed(&buffer);
    try emit(&out, tables);
    try testing.expectZig(out.buffered());
    try std.testing.expect(std.mem.indexOf(u8, out.buffered(), "explosion01 = 1,") != null);
}

test check {
    try check(testDefinition(1, .object, "PSHIP01"));
    try std.testing.expectError(error.BadDefinition, check(testDefinition(1, .object, "")));
    try std.testing.expectError(error.BadDefinition, check(testDefinition(1, @enumFromInt(9), "X")));
    var near = testDefinition(1, .object, "X");
    near.max_distance = 1;
    try std.testing.expectError(error.BadDefinition, check(near));
}
