//! Reads the view table out of the payload: for each view the camera numbers, the string that
//! names it, whether the cinematic bars slide in, and whether it is from the cockpit.
//!
//! The table is four bytes a view: a halfword string id and two flag bytes, each 0 or 1. It runs
//! to the first record whose flags are not, which is where the camera's "Invalid Camera type"
//! assertion text follows it.

const std = @import("std");
const Io = std.Io;

const image = @import("image.zig");
const testing = @import("testing.zig");

/// The view table, which `camera_set_view` (`0x0045F1B0`) reads the flags of and `hud_draw`
/// (`0x004843B0`) the names.
pub const table: u32 = 0x004F72A8;
const record_size = 4;

/// Views a table this size could hold, as a bound on the scan.
const max_views = 256;

pub const Record = struct {
    name: u16,
    bars: bool,
    cockpit: bool,
};

pub const Error = image.Error || error{Empty};

pub fn read(arena: std.mem.Allocator, reader: image.Reader) (Error || std.mem.Allocator.Error)![]const Record {
    var records: std.ArrayList(Record) = .empty;
    for (0..max_views) |index| {
        const at = table + @as(u32, @intCast(index)) * record_size;
        const bytes = reader.slice(at, record_size) catch break;
        const record = parse(bytes[0..record_size]) orelse break;
        try records.append(arena, record);
    }
    if (records.items.len == 0) return error.Empty;
    return records.toOwnedSlice(arena);
}

/// The view one record holds, or null when a flag is neither 0 nor 1, which ends the table.
fn parse(bytes: *const [record_size]u8) ?Record {
    if (bytes[2] > 1 or bytes[3] > 1) return null;
    return .{
        .name = std.mem.readInt(u16, bytes[0..2], .little),
        .bars = bytes[2] == 1,
        .cockpit = bytes[3] == 1,
    };
}

/// Writes `views.zig`.
pub fn emit(w: *Io.Writer, records: []const Record) Io.Writer.Error!void {
    try w.print(
        \\//! The view table: for each view the camera numbers, the language string that names it,
        \\//! whether the cinematic bars slide in, and whether it is from the cockpit.
        \\//!
        \\//! Generated by `src/tools/tablegen` from the payload executable's view table at
        \\//! 0x{X:0>8}, {d} views. Do not edit by hand; run `make view-tables`.
        \\
        \\pub const Record = struct {{
        \\    /// The language string that names the view, which the display shows at the top of the
        \\    /// screen in every view but the one ahead from the cockpit.
        \\    name: u16,
        \\    /// Whether the cinematic bars slide in.
        \\    bars: bool,
        \\    /// Whether it is from the cockpit, so that the object's own model is not drawn.
        \\    cockpit: bool,
        \\}};
        \\
        \\/// Every view, indexed by its number.
        \\pub const records = [_]Record{{
        \\
    , .{ table, records.len });
    for (records, 0..) |record, index| {
        try w.print("    .{{ .name = {d}, .bars = {}, .cockpit = {} }}, // 0x{X:0>2}\n", .{
            record.name, record.bars, record.cockpit, index,
        });
    }
    try w.writeAll(
        \\};
        \\
    );
}

test parse {
    const view = parse(&.{ 0xAA, 0x00, 0x00, 0x01 }).?;
    try std.testing.expectEqual(170, view.name);
    try std.testing.expect(!view.bars and view.cockpit);
    try std.testing.expect(parse(&.{ 0xB5, 0x00, 0x01, 0x00 }).?.bars);
    // Text past the table has flag bytes above 1.
    try std.testing.expectEqual(null, parse(&.{ 'S', 'R', '_', 'S' }));
}

test read {
    const allocator = std.testing.allocator;
    var arena_state: std.heap.ArenaAllocator = .init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const bytes = try allocator.alloc(u8, 0x100);
    defer allocator.free(bytes);
    @memset(bytes, 0);
    const region: testing.Region = .{ .va = table, .bytes = bytes };
    region.put(table, &.{ 0xAA, 0x00, 0x00, 0x01 });
    region.put(table + 4, &.{ 0xB5, 0x00, 0x01, 0x00 });
    region.putString(table + 8, "SR_STR(\"Invalid Camera type %d\", camera_type)");

    const payload = try testing.reader(allocator, &.{region});
    defer testing.freeReader(allocator, payload);
    const records = try read(arena, payload);
    try std.testing.expectEqual(2, records.len);
    try std.testing.expectEqual(181, records[1].name);

    var out: Io.Writer.Allocating = .init(allocator);
    defer out.deinit();
    try emit(&out.writer, records);
    try testing.expectZig(out.written());
}
